import type { WeekDraft } from "./types";

// 4-OY: PHOTOSHOP
export const month4: WeekDraft[] = [
  {
    title: "Interfeys, qatlamlar, fon almashtirish",
    days: [
      {
        title: "Photoshop interfeysi, qatlamlar (layers)",
        kind: "lesson",
        goals: ["Photoshop oynasining asosiy qismlarini tanish", "Qatlam tushunchasini tushunish", "Qatlamlarni yaratish, yashirish, tartibini o'zgartirish"],
        visual: "layers",
        slides: [
          { emoji: "🎨", title: "Photoshop nima?", points: ["**Adobe Photoshop** — rasmlarni tahrirlash va dizayn dasturi.", "Dizaynerlar, fotograflar, reklama ustalari ishlatadi.", "Bepul muqobillari: **Photopea** (photopea.com — brauzerda ishlaydi!), GIMP."], tip: "Darslarimizda Photopea ham ishlaydi — u Photoshop'ga juda o'xshaydi." },
          { emoji: "🧭", title: "Oyna qismlari", points: ["**Asboblar paneli** (chapda) — tanlash, cho'tka, o'chirg'ich, matn...", "**Parametrlar paneli** (tepada) — tanlangan asbob sozlamalari.", "**Kanvas** (o'rtada) — rasm.", "**Qatlamlar paneli** (o'ngda pastda) — eng muhim panel!"] },
          { emoji: "🗂️", title: "Qatlam (Layer) nima?", points: ["Qatlam — **shaffof plyonka**. Ularni ustma-ust qo'yamiz.", "Pastki qatlam — fon, ustidagilar — rasm, matn, stiker.", "Har qatlamni **alohida** tahrirlash mumkin — boshqasi buzilmaydi."] },
          { emoji: "👁️", title: "Qatlamlar bilan ishlash", points: ["👁️ — ko'rsatish/yashirish.", "Sudrab — tartibni o'zgartirish (yuqoridagi oldinda ko'rinadi).", "**Opacity** — shaffoflik.", "Yangi qatlam: **Ctrl + Shift + N**."], code: "Ctrl + Shift + N — yangi qatlam\nCtrl + J — qatlam nusxasi\nCtrl + Z — orqaga" },
        ],
        practice: [
          "Ko'rgazmada qatlamlarni yashirib/ko'rsatib, tartibini ⬆️⬇️ bilan o'zgartiring. Qahramon fon ortida qolsa nima bo'ladi?",
          "Photoshop yoki Photopea'ni oching, yangi hujjat yarating (1080×1080).",
          "3 ta qatlam yarating: fon (rang bilan to'ldiring), shakl, matn.",
          "Har qatlamga tushunarli nom bering (ikki marta bosib).",
          "Qatlamlar tartibini va shaffofligini o'zgartirib tajriba qiling.",
          "Faylni **PSD** formatida saqlang.",
        ],
        homework: "Photopea'da 5 qatlamli \"Mening xonam\" kompozitsiyasini yarating (fon, mebel shakllari, matn). Qatlamlarga nom bering va PSD saqlang.",
        quiz: [
          { q: "Photoshop'ning bepul brauzer muqobili?", options: ["Photopea", "Excel", "Scratch", "CapCut"], correct: 0 },
          { q: "Qatlam nima?", options: ["Shaffof plyonka — ustma-ust qo'yiladi", "Fayl turi", "Rang", "Asbob"], correct: 0 },
          { q: "Qatlamlar panelida qaysi qatlam oldinda ko'rinadi?", options: ["Eng yuqoridagisi", "Eng pastdagisi", "O'rtadagisi", "Tasodifiy"], correct: 0 },
          { q: "Qatlamni yashirish belgisi?", options: ["👁️", "🔒", "🗑️", "➕"], correct: 0 },
          { q: "Qatlamlar saqlanadigan Photoshop formati?", options: ["PSD", "JPG", "MP3", "TXT"], correct: 0 },
          { q: "Qatlam nusxasini olish tugmalari?", options: ["Ctrl + J", "Ctrl + P", "Ctrl + B", "Ctrl + E"], correct: 0 },
        ],
      },
      {
        title: "Rasm kesish, fon almashtirish",
        kind: "lesson",
        goals: ["Crop asbobi bilan rasmni kesish", "Obyektni tanlash asboblari", "Fonni olib tashlash va almashtirish"],
        visual: "layers",
        slides: [
          { emoji: "✂️", title: "Crop — kesish", points: ["**Crop (C)** — rasmning keraksiz chetlarini kesadi.", "Nisbat tanlash: 1:1 (Instagram), 16:9 (YouTube).", "Kompozitsiya: asosiy obyekt markazda yoki 1/3 chiziqda."] },
          { emoji: "🪄", title: "Tanlash asboblari", points: ["**Lasso (L)** — qo'lda chizib tanlash.", "**Magic Wand (W)** — bir xil rangli joyni tanlaydi.", "**Object Selection / Quick Selection** — obyektni aqlli tanlaydi.", "**Select Subject** — bir tugma bilan asosiy obyektni tanlaydi (AI)."] },
          { emoji: "🖼️", title: "Fonni olib tashlash", points: ["Obyektni tanlang → **Layer Mask** 🎭 tugmasi.", "Yoki: **Remove Background** (tez tugma).", "Fon o'rnida **shaxmat kataklar** — bu shaffof joy."] },
          { emoji: "🔄", title: "Yangi fon qo'yish", points: ["Yangi fon rasmini ochib, qatlam sifatida sudrab keling.", "Fon qatlamini obyekt **ostiga** qo'ying.", "O'lcham: **Ctrl + T** (Free Transform)."], tip: "Yorug'lik va ranglar mos bo'lsa, fotomontaj tabiiy ko'rinadi." },
        ],
        practice: [
          "Ko'rgazmada fonni 5 xil variantga almashtiring — qaysi biri qahramonga mos?",
          "O'qituvchi bergan rasmni Crop bilan 1:1 formatga kesing.",
          "Select Subject yoki Quick Selection bilan hayvonni tanlang.",
          "Layer Mask bilan fonni yashiring.",
          "Yangi fon qo'yib, Ctrl+T bilan o'lchamini moslang va PNG saqlang.",
        ],
        homework: "O'z rasmingiz (yoki sevimli o'yinchog'ingiz) fonini olib tashlab, kosmos yoki dengiz foniga joylang.",
        quiz: [
          { q: "Rasmning chetlarini kesadigan asbob?", options: ["Crop", "Brush", "Eraser", "Text"], correct: 0 },
          { q: "Bir xil rangli joyni bir bosishda tanlaydigan asbob?", options: ["Magic Wand", "Lasso", "Crop", "Hand"], correct: 0 },
          { q: "Shaxmat kataklar Photoshop'da nimani bildiradi?", options: ["Shaffof joy", "Qora rang", "Xato", "Matn"], correct: 0 },
          { q: "Obyekt o'lchamini o'zgartirish tugmalari?", options: ["Ctrl + T", "Ctrl + S", "Ctrl + C", "Ctrl + A"], correct: 0 },
          { q: "Yangi fon qatlami qayerda turishi kerak?", options: ["Obyekt qatlami ostida", "Obyekt ustida", "Alohida faylda", "O'chirilgan"], correct: 0 },
          { q: "Instagram post uchun kesish nisbati?", options: ["1:1", "16:9", "4:1", "9:1"], correct: 0 },
        ],
      },
      {
        title: "Mini loyiha — «Surat fonini almashtirish»",
        kind: "project",
        goals: ["Fonni toza ajratish", "Obyekt va fonni moslashtirish", "Natijani eksport qilish"],
        visual: "layers",
        slides: [
          { emoji: "🌍", title: "Vazifa", points: ["Bitta obyekt (odam, hayvon, o'yinchoq) ni tanlang.", "Uni **qiziqarli joyga** \"sayohatga\" jo'nating: Oy, Parij, dengiz tubi, Registon.", "Natija tabiiy ko'rinsin!"] },
          { emoji: "🔍", title: "Toza ajratish", points: ["Maskada **qora cho'tka** — yashiradi, **oq cho'tka** — qaytaradi.", "Cho'tka qattiqligini (Hardness) 50% qiling — chetlar yumshoq.", "Zoom (Ctrl +) bilan mayda joylarni tekshiring."] },
          { emoji: "🌗", title: "Moslashtirish", points: ["Obyekt yorug'ligini fonga moslang: **Image → Adjustments → Brightness/Contrast**.", "Soya qo'shing: yangi qatlam, qora yumshoq cho'tka, Opacity 30%.", "O'lcham va istiqbol mantiqiy bo'lsin."] },
          { emoji: "📤", title: "Eksport", points: ["**File → Export → PNG yoki JPG**.", "Nomi: `ism_sayohat.jpg`.", "PSD ni ham saqlang — keyin tahrirlash uchun."] },
        ],
        practice: [
          "Obyekt rasmi va 2 ta fon variantini tanlang.",
          "Obyektni ajratib, Layer Mask bilan fonni olib tashlang.",
          "Mask chetlarini qora/oq cho'tka bilan tozalang.",
          "Yangi fonni qo'yib, yorug'lik va o'lchamni moslang, soya qo'shing.",
          "JPG va PSD formatda saqlang, sinfga ko'rsating.",
        ],
        homework: "Ikkinchi variant yarating: xuddi shu obyektni butunlay boshqa fonga joylang va ikkalasini solishtiring.",
        rubric: ["Obyekt toza ajratilgan (chetlar tekis)", "Fon mavzuga mos", "Yorug'lik/o'lcham moslashtirilgan", "Soya qo'shilgan", "JPG va PSD saqlangan"],
        quiz: [
          { q: "Maskada qora cho'tka nima qiladi?", options: ["Yashiradi", "Ko'rsatadi", "Bo'yaydi", "O'chiradi"], correct: 0 },
          { q: "Maskada oq cho'tka nima qiladi?", options: ["Yashirilgan joyni qaytaradi", "Qora qiladi", "Faylni saqlaydi", "Kesadi"], correct: 0 },
          { q: "Obyekt yorug'ligini o'zgartirish yo'li?", options: ["Brightness/Contrast", "Crop", "Lasso", "Text"], correct: 0 },
          { q: "Fotomontaj tabiiy ko'rinishi uchun?", options: ["Yorug'lik va o'lcham mos bo'lishi", "Ko'proq stiker", "Faqat qizil rang", "Chetlarni qo'pol qoldirish"], correct: 0 },
          { q: "Keyinchalik tahrirlash uchun qaysi formatni saqlaymiz?", options: ["PSD", "JPG", "PNG", "GIF"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Ranglar, filtrlar, effektlar, poster",
    days: [
      {
        title: "Ranglar va filtrlar",
        kind: "lesson",
        goals: ["Yorqinlik, kontrast, to'yinganlikni sozlash", "Rang tusini o'zgartirish (Hue/Saturation)", "Filtrlar bilan badiiy effektlar"],
        visual: "layers",
        slides: [
          { emoji: "☀️", title: "Asosiy sozlamalar", points: ["**Brightness** — yorqinlik (qorong'i ↔ yorug').", "**Contrast** — kontrast (xira ↔ keskin).", "**Saturation** — to'yinganlik (kulrang ↔ juda rangli)."] },
          { emoji: "🎨", title: "Hue/Saturation", points: ["**Ctrl + U** — rang tusini aylantirish.", "Qizil olma → yashil olma!", "Faqat bitta rangni (masalan, ko'klarni) o'zgartirish mumkin."] },
          { emoji: "🧪", title: "Adjustment Layer", points: ["Sozlamani **alohida qatlam** sifatida qo'shish (qatlamlar pastidagi ◐ belgisi).", "Asl rasm buzilmaydi — istalgan payt o'chirish mumkin.", "Professional dizaynerlar shunday ishlaydi!"] },
          { emoji: "🌫️", title: "Filtrlar", points: ["**Filter → Blur** — xiralashtirish.", "**Filter Gallery** — akvarel, qalam chizma, mozaika.", "**Black & White**, **Sepia** — eski rasm effekti."], tip: "Filtr qo'yishdan oldin qatlam nusxasini oling (Ctrl+J)!" },
        ],
        practice: [
          "Ko'rgazmada har bir filtr slayderini sinab ko'ring: qahramonni oq-qora, fonni sepiya qiling.",
          "Photoshop'da xira rasmni Brightness/Contrast bilan yaxshilang.",
          "Hue/Saturation bilan mashina yoki kiyim rangini o'zgartiring.",
          "Adjustment Layer sifatida Black & White qo'shib, yashirib-ko'rsatib solishtiring.",
          "Filter Gallery'dan 2 ta badiiy effekt sinab ko'ring.",
        ],
        homework: "Bitta rasmning 4 xil versiyasini yarating: asl, oq-qora, sepiya, rangi o'zgartirilgan. Ularni bitta 2×2 kollajga joylang.",
        quiz: [
          { q: "Rasmni kulrang yoki juda rangli qiladigan sozlama?", options: ["Saturation (to'yinganlik)", "Crop", "Blur", "Text"], correct: 0 },
          { q: "Hue/Saturation tugmalari?", options: ["Ctrl + U", "Ctrl + T", "Ctrl + J", "Ctrl + S"], correct: 0 },
          { q: "Adjustment Layer ning afzalligi?", options: ["Asl rasm buzilmaydi", "Fayl kichrayadi", "Rasm o'chadi", "Tezroq saqlanadi"], correct: 0 },
          { q: "Eski rasm effekti?", options: ["Sepia", "Blur", "Crop", "Lasso"], correct: 0 },
          { q: "Filtrdan oldin nima qilgan ma'qul?", options: ["Qatlam nusxasini olish (Ctrl+J)", "Faylni o'chirish", "Photoshop'ni yopish", "Hech narsa"], correct: 0 },
          { q: "Xira rasmni keskinlashtirish uchun?", options: ["Contrast ni oshirish", "Blur qo'shish", "Opacity ni 0 qilish", "Rangni o'chirish"], correct: 0 },
        ],
      },
      {
        title: "Effektlar va yozuv qo'shish",
        kind: "lesson",
        goals: ["Matn asbobi bilan ishlash", "Layer Style: soya, kontur, gradient", "Chiroyli sarlavha yaratish"],
        visual: "layers",
        slides: [
          { emoji: "🔤", title: "Matn asbobi (T)", points: ["**T** tugmasi — kanvasga bosib yozing.", "Shrift, o'lcham, rang — tepadagi panelda.", "Matn o'zi alohida **qatlam** bo'ladi."] },
          { emoji: "✨", title: "Layer Style (fx)", points: ["Qatlamni ikki marta bosing → **Layer Style**.", "**Drop Shadow** — soya.", "**Stroke** — kontur (chiziq).", "**Gradient Overlay** — rang o'tishi.", "**Outer Glow** — nurlanish."] },
          { emoji: "📐", title: "Matn dizayni qoidalari", points: ["Sarlavha — **katta va qalin**.", "Fon bilan kontrast: to'q fonda och matn.", "Ko'pi bilan **2 xil shrift**.", "Matnni rasmning bo'sh joyiga qo'ying."] },
          { emoji: "🌈", title: "Effektli sarlavha", points: ["Qalin shrift + Stroke (oq, 4px) + Drop Shadow = o'yin posteri uslubi!", "Gradient Overlay: sariqdan to'q sariqqa — \"oltin\" matn."], tip: "Effektni ko'paytirib yubormang: 2–3 ta effekt yetarli." },
        ],
        practice: [
          "Ko'rgazmada matn qatlamini tanlab, rangini, soyasini va o'lchamini o'zgartiring.",
          "Photoshop'da fon rasmiga sarlavha yozing: o'z ismingiz.",
          "Layer Style bilan Stroke va Drop Shadow qo'shing.",
          "Gradient Overlay bilan \"oltin\" matn yarating.",
          "Kichik tagsarlavha qo'shing (boshqa shrift, kichikroq).",
        ],
        homework: "Sevimli filmingiz yoki kitobingiz nomini effektli sarlavha qilib yozing (Stroke + Shadow + Gradient). PNG saqlang.",
        quiz: [
          { q: "Matn asbobi qaysi harf bilan ochiladi?", options: ["T", "C", "B", "V"], correct: 0 },
          { q: "Matn atrofiga chiziq (kontur) qo'shish effekti?", options: ["Stroke", "Blur", "Crop", "Sepia"], correct: 0 },
          { q: "Soya effekti?", options: ["Drop Shadow", "Outer Glow", "Stroke", "Hue"], correct: 0 },
          { q: "Layer Style qanday ochiladi?", options: ["Qatlamni ikki marta bosib", "Ctrl + P", "Faylni yopib", "Crop bilan"], correct: 0 },
          { q: "Nechta shrift ishlatish tavsiya etiladi?", options: ["Ko'pi bilan 2", "5–6", "10", "Har so'zga boshqa"], correct: 0 },
          { q: "To'q ko'k fonda qaysi matn yaxshi o'qiladi?", options: ["Oq yoki sariq", "To'q ko'k", "Qora", "To'q binafsha"], correct: 0 },
        ],
      },
      {
        title: "Mini loyiha — «Poster dizayni»",
        kind: "project",
        goals: ["Poster kompozitsiyasini rejalashtirish", "Rasm, matn va effektlarni birlashtirish", "Tayyor posterni chop etishga tayyorlash"],
        visual: "layers",
        slides: [
          { emoji: "🖼️", title: "Poster mavzulari", points: ["🎬 Film yoki multfilm posteri.", "⚽ Sport musobaqasi e'loni.", "🌳 \"Tabiatni asraylik\" ijtimoiy poster.", "🎂 Tug'ilgan kun taklifi."] },
          { emoji: "📐", title: "Kompozitsiya", points: ["**Yuqorida** — katta sarlavha.", "**O'rtada** — asosiy rasm.", "**Pastda** — sana, joy, qo'shimcha ma'lumot.", "Ko'z avval eng katta va yorqin narsaga qaraydi."] },
          { emoji: "📄", title: "O'lcham", points: ["A4 poster: **2480 × 3508 px** (300 dpi).", "Ekran uchun: 1080 × 1350 px.", "Chop etish uchun **PDF** yoki yuqori sifatli JPG."] },
          { emoji: "✅", title: "Tekshirish", points: ["Uzoqdan qarab ko'ring — sarlavha o'qiladimi?", "Imlo xatosi yo'qmi?", "Ranglar 2–3 ta asosiy rangdan iboratmi?"] },
        ],
        practice: [
          "Mavzu tanlab, qog'ozda poster eskizini chizing.",
          "Photoshop'da A4 hujjat yarating, fon qo'ying.",
          "Asosiy rasmni joylang (fonni olib tashlab kerak bo'lsa).",
          "Effektli sarlavha va ma'lumot matnlarini qo'shing.",
          "Ranglarni moslang, PDF/JPG eksport qiling va sinf ko'rgazmasiga qo'ying.",
        ],
        homework: "Posteringizni oilangizga ko'rsating va \"uzoqdan o'qiladimi?\" testini o'tkazing. Kerak bo'lsa tuzating.",
        rubric: ["Aniq mavzu va sarlavha", "Kompozitsiya: tepa-o'rta-past", "Effektli, o'qiladigan matn", "2–3 asosiy rang", "To'g'ri o'lcham va eksport"],
        quiz: [
          { q: "Posterda sarlavha odatda qayerda?", options: ["Yuqorida, katta", "Pastda, kichik", "Burchakda, mayda", "Yo'q"], correct: 0 },
          { q: "Chop etish uchun qaysi format mos?", options: ["PDF", "MP4", "MP3", "DOCX"], correct: 0 },
          { q: "Poster yaxshi ekanini tekshirish usuli?", options: ["Uzoqdan qarab o'qib ko'rish", "Faqat yaqindan ko'rish", "Ko'rmaslik", "O'chirish"], correct: 0 },
          { q: "Ko'z birinchi nimaga qaraydi?", options: ["Eng katta va yorqin narsaga", "Eng kichik matnga", "Bo'sh joyga", "Chetlarga"], correct: 0 },
          { q: "Posterda nechta asosiy rang tavsiya etiladi?", options: ["2–3", "8–10", "1 ta kulrang", "Cheklanmagan"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Chizish, fotomontaj, kollaj",
    days: [
      {
        title: "Photoshop'da chizish",
        kind: "lesson",
        goals: ["Brush (cho'tka) asbobini sozlash", "Qatlamlarda chizish: eskiz, kontur, rang", "Shakllar (Shape) asbobi"],
        visual: "paint",
        slides: [
          { emoji: "🖌️", title: "Cho'tka (B)", points: ["**Size** — o'lcham: [ va ] tugmalari.", "**Hardness** — qattiqlik: 100% — keskin, 0% — yumshoq.", "**Opacity / Flow** — shaffoflik va bo'yoq oqimi."], code: "B — cho'tka\nE — o'chirg'ich\n[ ] — cho'tka o'lchami\nX — asosiy/fon rangini almashtirish" },
          { emoji: "🧱", title: "Qatlamlarda chizish", points: ["1-qatlam: **eskiz** (och kulrang, xom chiziqlar).", "2-qatlam: **kontur** (toza qora chiziqlar).", "3-qatlam: **rang** (kontur ostida).", "Eskiz qatlamini oxirida yashiramiz."] },
          { emoji: "🔷", title: "Shape asbobi (U)", points: ["To'rtburchak, ellips, ko'pburchak, maxsus shakllar.", "Shakl **vektor** — kattalashtirsa ham xira bo'lmaydi.", "Fill (ichi) va Stroke (chizig'i) rangini tanlash."] },
          { emoji: "🪣", title: "Bo'yash", points: ["**Paint Bucket (G)** — yopiq joyni to'ldirish.", "**Gradient (G)** — rang o'tishi: osmon, quyosh botishi.", "Pipetka (I) — rasmdan rang olish."] },
        ],
        practice: [
          "Ko'rgazmadagi mini-Paintda qalinlik va shakllar bilan qizdirilish mashqi.",
          "Photoshop'da 3 qatlam yarating: Eskiz, Kontur, Rang.",
          "Sevimli hayvon yoki multfilm qahramonini eskiz qiling.",
          "Kontur qatlamida toza chiziqlar chizing, Rang qatlamida bo'yang.",
          "Fonga Gradient qo'shing va eskiz qatlamini yashiring.",
        ],
        homework: "Shape asbobi yordamida o'z logotipingizni (ismingizning bosh harfi + shakl) yarating.",
        quiz: [
          { q: "Cho'tka o'lchamini kattalashtirish tugmasi?", options: ["]", "[", "B", "E"], correct: 0 },
          { q: "Hardness 0% qanday chiziq beradi?", options: ["Yumshoq, xira chetli", "Keskin", "Ko'rinmas", "Qora"], correct: 0 },
          { q: "Nima uchun eskiz, kontur va rang alohida qatlamda?", options: ["Bittasini buzmasdan boshqasini tahrirlash uchun", "Fayl kichik bo'lishi uchun", "Majburiy qoida", "Tezroq saqlash uchun"], correct: 0 },
          { q: "Kattalashtirganda xira bo'lmaydigan shakl turi?", options: ["Vektor (Shape)", "Piksel cho'tka", "JPG", "Skrinshot"], correct: 0 },
          { q: "Rang o'tishi (osmon) uchun asbob?", options: ["Gradient", "Lasso", "Crop", "Text"], correct: 0 },
        ],
      },
      {
        title: "Oddiy fotomontaj",
        kind: "lesson",
        goals: ["Bir nechta rasmni bitta kompozitsiyaga birlashtirish", "Blend Mode (aralashtirish rejimlari)", "Qiziqarli syurreal effektlar"],
        visual: "layers",
        slides: [
          { emoji: "🧩", title: "Fotomontaj nima?", points: ["Bir nechta rasmdan **yangi, xayoliy** rasm yaratish.", "Masalan: fil choy piyolasida, mushuk Oyda, uy bulut ustida.", "Kino va reklamada juda ko'p ishlatiladi."] },
          { emoji: "🔀", title: "Blend Mode", points: ["Qatlamlar qanday **aralashishini** belgilaydi.", "**Multiply** — qoraytiradi (soya uchun).", "**Screen** — yoritadi (nur, olov uchun).", "**Overlay** — kontrast va rang boyitadi."] },
          { emoji: "📏", title: "Transform", points: ["**Ctrl + T** — o'lcham va burish.", "O'ng tugma → **Flip Horizontal** — oynadagidek aylantirish.", "**Warp** — egish (masalan, rasmni piyolaga moslash)."] },
          { emoji: "⚖️", title: "Halollik", points: ["Fotomontaj — **ijod**, lekin soxta yangilik yaratmaslik kerak.", "Real odamlarni ular xohlamagan holatda ko'rsatmang.", "Montaj ekanini ochiq ayting."] },
        ],
        practice: [
          "Ko'rgazmada qatlamlarni surib, o'lcham va shaffoflik bilan \"xayoliy\" sahna yarating.",
          "O'qituvchi bergan 3 ta rasmdan \"Kichkina fil piyolada\" montajini qiling.",
          "Ctrl+T bilan o'lchamni moslang, Flip bilan yo'nalishni tanlang.",
          "Blend Mode'larni sinab ko'ring: Multiply, Screen, Overlay.",
          "Soya qo'shib, natijani JPG saqlang.",
        ],
        homework: "\"Mening xayoliy dunyom\" — 3 ta rasmdan syurreal fotomontaj yarating (masalan, baliq osmonda suzadi).",
        quiz: [
          { q: "Fotomontaj nima?", options: ["Bir nechta rasmdan yangi rasm yaratish", "Rasmni o'chirish", "Video montaj", "Matn yozish"], correct: 0 },
          { q: "Soya uchun qaysi Blend Mode mos?", options: ["Multiply", "Screen", "Normal", "Dissolve"], correct: 0 },
          { q: "Nur va olov effektlari uchun?", options: ["Screen", "Multiply", "Darken", "Crop"], correct: 0 },
          { q: "Rasmni oynadagidek aylantirish?", options: ["Flip Horizontal", "Crop", "Blur", "Hue"], correct: 0 },
          { q: "Qaysi biri noto'g'ri harakat?", options: ["Xayoliy san'at asari", "Soxta yangilik rasmini tarqatish", "Syurreal kollaj", "Reklama maketi"], correct: 1 },
        ],
      },
      {
        title: "Mini loyiha — «Mening qiziqarli kollajim»",
        kind: "project",
        goals: ["Kollaj kompozitsiyasini tuzish", "Rasmlar, matn va bezaklarni uyg'unlashtirish", "Mavzuli dizayn yaratish"],
        visual: "layers",
        slides: [
          { emoji: "🖼️", title: "Kollaj", points: ["**Kollaj** — ko'p rasmdan bitta chiroyli kompozitsiya.", "Mavzular: \"Mening yozgi ta'tilim\", \"Sevimli narsalarim\", \"Mening orzularim\".", "Kamida **5 ta rasm**."] },
          { emoji: "🔲", title: "Joylashuv turlari", points: ["**To'r (grid)** — tekis kataklar.", "**Erkin** — rasmlar qiyshiq, ustma-ust (skrapbuk uslubi).", "**Markaziy** — o'rtada katta rasm, atrofida kichiklar."] },
          { emoji: "🎀", title: "Bezaklar", points: ["Ramkalar: Stroke yoki oq fon.", "Stikerlar, shakllar, qo'lda chizilgan elementlar.", "Sarlavha va kichik izohlar."] },
          { emoji: "✅", title: "Talablar", points: ["5+ rasm, bitta mavzu.", "Sarlavha effekt bilan.", "Kamida 1 ta fonsiz (kesilgan) obyekt.", "Ranglar uyg'un."] },
        ],
        practice: [
          "Mavzu va joylashuv turini tanlang.",
          "5–7 ta rasm yig'ing (o'zingizniki yoki o'qituvchi bergan).",
          "Rasmlarni joylang, ramka va soya bering.",
          "Bitta obyektni fonsiz qilib, kollaj ustiga chiqaring.",
          "Sarlavha va bezaklarni qo'shib, eksport qiling.",
        ],
        homework: "Kollajingizni chop eting yoki telefon fon rasmi (1080×1920) formatida qayta saqlang.",
        rubric: ["5+ rasm, yagona mavzu", "Aniq joylashuv turi", "Fonsiz obyekt bor", "Effektli sarlavha", "Uyg'un ranglar"],
        quiz: [
          { q: "Kollaj nima?", options: ["Ko'p rasmdan bitta kompozitsiya", "Bitta rasm", "Video", "Jadval"], correct: 0 },
          { q: "Tekis kataklarga joylash turi?", options: ["To'r (grid)", "Erkin", "Tasodifiy", "Markaziy"], correct: 0 },
          { q: "Rasmga ramka qo'shish uchun qaysi effekt?", options: ["Stroke", "Blur", "Hue", "Crop"], correct: 0 },
          { q: "Telefon fon rasmi o'lchami?", options: ["1080×1920", "100×100", "2480×3508", "16×9"], correct: 0 },
          { q: "Kollajda nechta rasm talab qilingan?", options: ["Kamida 5", "1", "2", "100"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Retush va katta loyiha",
    days: [
      {
        title: "Rasmni retush qilish",
        kind: "lesson",
        goals: ["Dog' va chizishlarni olib tashlash", "Eski rasmni tiklash", "Retush etikasi"],
        visual: "layers",
        slides: [
          { emoji: "🩹", title: "Retush nima?", points: ["**Retush** — rasmdagi kamchiliklarni tuzatish.", "Chang, dog', chizish, qizil ko'z, keraksiz narsalar.", "Eski oilaviy suratlarni tiklash."] },
          { emoji: "🔧", title: "Asboblar", points: ["**Spot Healing Brush (J)** — dog' ustiga bosing — yo'qoladi!", "**Healing Brush** — Alt bilan manba tanlab tuzatish.", "**Clone Stamp (S)** — bir joyni boshqa joyga nusxalash.", "**Content-Aware Fill** — tanlangan narsani aqlli o'chirish (AI)."] },
          { emoji: "📸", title: "Eski rasmni tiklash", points: ["1. Skanerlash yoki suratga olish.", "2. Crop va to'g'rilash.", "3. Chiziq va dog'larni Healing bilan tuzatish.", "4. Kontrastni oshirish, kerak bo'lsa rang berish."] },
          { emoji: "⚖️", title: "Retush etikasi", points: ["Tabiiylikni saqlang — odamni \"boshqa odam\" qilib yubormang.", "Reklamadagi rasmlar ko'pincha retush qilingan — hamma narsaga ishonmang!", "Boshqa odam rasmini ruxsatsiz o'zgartirmang."] },
        ],
        practice: [
          "O'qituvchi bergan \"changli\" rasmdagi dog'larni Spot Healing bilan tozalang.",
          "Clone Stamp bilan rasmdagi keraksiz narsani (masalan, simyog'och) olib tashlang.",
          "Content-Aware Fill bilan kattaroq obyektni o'chirib ko'ring.",
          "Eski oq-qora rasmni tiklab, kontrastini oshiring.",
          "Oldin/keyin solishtiruvini bitta faylga joylang.",
        ],
        homework: "Oila albomidan eski rasm (ota-ona ruxsati bilan) tanlab, uni skanerlab yoki suratga olib retush qiling.",
        quiz: [
          { q: "Dog' ustiga bir bosishda tuzatuvchi asbob?", options: ["Spot Healing Brush", "Crop", "Text", "Gradient"], correct: 0 },
          { q: "Bir joyni boshqa joyga nusxalovchi asbob?", options: ["Clone Stamp", "Lasso", "Eraser", "Hand"], correct: 0 },
          { q: "Tanlangan obyektni aqlli o'chiruvchi funksiya?", options: ["Content-Aware Fill", "Brightness", "Stroke", "Flip"], correct: 0 },
          { q: "Healing Brush'da manba qaysi tugma bilan tanlanadi?", options: ["Alt", "Shift", "Tab", "Enter"], correct: 0 },
          { q: "Retush etikasiga zid harakat?", options: ["Boshqa odam rasmini ruxsatsiz o'zgartirish", "Changni tozalash", "Eski rasmni tiklash", "Kontrastni oshirish"], correct: 0 },
        ],
      },
      {
        title: "Katta loyiha uchun tayyorgarlik",
        kind: "project",
        goals: ["4-oyda o'rganilganlarni takrorlash", "Yakuniy Photoshop loyihasi uchun reja", "Materiallarni yig'ish"],
        visual: "layers",
        slides: [
          { emoji: "🧠", title: "Nimalarni o'rgandik?", points: ["Qatlamlar va maskalar.", "Crop, tanlash, fon almashtirish.", "Ranglar, filtrlar, Layer Style.", "Chizish, fotomontaj, kollaj, retush."] },
          { emoji: "💡", title: "Loyiha: \"O'z suratimni qayta ishlash\"", points: ["O'z rasmingiz (yoki o'yinchoq/uy hayvoni) asosida:", "🦸 Superqahramon posteri", "📰 Jurnal muqovasi", "🎮 O'yin qahramoni kartochkasi", "🌌 Kosmik sayohatchi"] },
          { emoji: "📋", title: "Reja", points: ["Mavzu va g'oya.", "Kerakli rasmlar ro'yxati.", "Qaysi usullar ishlatiladi (fon, filtr, matn...).", "Eskiz (qog'ozda)."] },
          { emoji: "📁", title: "Materiallar", points: ["Papka: `Loyiha_Ism`.", "Ichida: `rasmlar/`, `psd/`, `tayyor/`.", "Rasmlar sifatli bo'lsin (kamida 1000 px)."] },
        ],
        practice: [
          "4-oy mavzularini viktorina shaklida takrorlaymiz.",
          "Loyiha g'oyasini tanlang va reja varag'ini to'ldiring.",
          "Qog'ozda eskiz chizing.",
          "Materiallar papkasini tuzing va rasmlarni yig'ing.",
          "Rejani o'qituvchiga tasdiqlating va PSD faylni boshlang.",
        ],
        homework: "Loyiha uchun o'z rasmingizni oling: yaxshi yorug'lik, oddiy fon (fonni olib tashlash oson bo'lishi uchun).",
        rubric: ["Aniq g'oya", "To'liq reja varag'i", "Eskiz bor", "Materiallar papkasi tartibli"],
        quiz: [
          { q: "Fonni olib tashlash oson bo'lishi uchun rasm qanday bo'lsin?", options: ["Oddiy fon, yaxshi yorug'lik", "Qorong'i va chalkash fon", "Juda kichik", "Xira"], correct: 0 },
          { q: "Loyiha papkasida nima bo'lishi kerak?", options: ["rasmlar, psd, tayyor papkalari", "Faqat bitta JPG", "O'yinlar", "Hech narsa"], correct: 0 },
          { q: "Qaysi usul 4-oyda o'rganilmagan?", options: ["Qatlamlar", "Retush", "Excel formulalar", "Kollaj"], correct: 2 },
          { q: "Loyiha uchun rasm sifati?", options: ["Kamida 1000 px", "50 px", "Farqi yo'q", "Faqat skrinshot"], correct: 0 },
          { q: "Loyihani boshlashdan oldin?", options: ["Reja va eskiz", "Faylni o'chirish", "Filtrlarni tasodifiy qo'yish", "Hech narsa"], correct: 0 },
        ],
      },
      {
        title: "Mini loyiha — «O'z suratimni qayta ishlash»",
        kind: "project",
        goals: ["Barcha Photoshop ko'nikmalarini bitta loyihada qo'llash", "Professional ko'rinishdagi natija yaratish", "Loyihani taqdim etish"],
        visual: "layers",
        slides: [
          { emoji: "🚀", title: "Yakuniy loyiha", points: ["Reja bo'yicha o'z suratingizni qayta ishlaysiz.", "Kamida **5 ta** o'rganilgan usul ishlatilsin.", "Natija: JPG + PSD."] },
          { emoji: "🧰", title: "Ishlatish mumkin bo'lgan usullar", points: ["Fonni almashtirish (mask).", "Rang tuzatish (Adjustment Layer).", "Effektli matn (Layer Style).", "Fotomontaj elementlari (Blend Mode).", "Retush."] },
          { emoji: "⏱️", title: "Vaqt rejasi (80 daqiqa)", points: ["10 daq — reja bilan tanishish.", "50 daq — ish.", "10 daq — tekshirish va eksport.", "10 daq — mini-ko'rgazma."] },
          { emoji: "🎤", title: "Taqdimot", points: ["\"Qaysi usullarni ishlatdim?\"", "\"Eng qiyin qismi nima edi?\"", "\"Yana nima qo'shgan bo'lardim?\""] },
        ],
        practice: [
          "PSD faylni oching va reja bo'yicha ishni davom ettiring.",
          "Fonni almashtiring va rangni moslang.",
          "Effektli sarlavha va bezaklar qo'shing.",
          "Kamida 5 usul ishlatilganini tekshiring.",
          "JPG eksport qiling va sinf ko'rgazmasida taqdim eting.",
        ],
        homework: "Ishingizni oilangizga ko'rsating. Portfolioingiz uchun eng yaxshi 3 ta Photoshop ishingizni `portfolio` papkasiga saqlang — 5-oyda veb-saytingizga qo'yamiz!",
        rubric: ["5+ Photoshop usuli qo'llangan", "Fon toza almashtirilgan", "Rang va yorug'lik uyg'un", "Effektli matn", "Taqdimotda usullarni tushuntira oladi"],
        quiz: [
          { q: "Yakuniy loyihada nechta usul ishlatilishi kerak?", options: ["Kamida 5", "1", "2", "Hech biri"], correct: 0 },
          { q: "Rangni asl rasmni buzmasdan tuzatish uchun?", options: ["Adjustment Layer", "Eraser", "Crop", "Flip"], correct: 0 },
          { q: "Loyihani saqlash formatlari?", options: ["JPG va PSD", "MP3 va MP4", "DOCX", "XLSX"], correct: 0 },
          { q: "5-oyda Photoshop ishlarimizni qayerga qo'yamiz?", options: ["Portfolio veb-saytimizga", "Excel jadvalga", "Scratch'ga", "Hech qayerga"], correct: 0 },
          { q: "Qatlamlar qanday aralashishini belgilovchi sozlama?", options: ["Blend Mode", "Crop", "Brush Size", "Zoom"], correct: 0 },
        ],
      },
    ],
  },
];
