import type { WeekDraft } from "./types";

// 2-OY: VIDEO VA SUN'IY INTELLEKT
export const month2: WeekDraft[] = [
  {
    title: "Videomontaj (CapCut)",
    days: [
      {
        title: "CapCut bilan tanishuv: kesish, matn, musiqa",
        kind: "lesson",
        goals: ["CapCut interfeysini tanish", "Videoni kesish va keraksiz qismni o'chirish", "Matn va musiqa qo'shish"],
        visual: "video-timeline",
        slides: [
          { emoji: "🎬", title: "Videomontaj nima?", points: ["**Montaj** — video bo'laklarini kesib, ulab, bezab bitta tayyor video qilish.", "YouTube, TikTok va filmlardagi hamma videolar montaj qilingan.", "Biz **CapCut** dasturidan foydalanamiz — bepul, kompyuter va telefonda ishlaydi."] },
          { emoji: "🧭", title: "CapCut oynasi", points: ["**Media** — video, rasm va musiqalaringiz.", "**Ko'rish oynasi (Player)** — natijani ko'rish.", "**Vaqt chizig'i (Timeline)** — klip, matn va musiqa treklari.", "**Playhead** — hozir qayerdaligingizni ko'rsatuvchi chiziq."] },
          { emoji: "✂️", title: "Kesish (Split)", points: ["Playhead ni kerakli joyga qo'ying.", "**Split** (✂️) tugmasi yoki **Ctrl + B** — klip ikkiga bo'linadi.", "Keraksiz bo'lakni tanlab **Delete**.", "Klip chetini tortib ham qisqartirish mumkin (Trim)."], code: "Ctrl + B — kesish\nSpace — ijro / pauza\nCtrl + Z — bekor qilish" },
          { emoji: "🔤", title: "Matn qo'shish", points: ["**Text → Default text** — vaqt chizig'iga torting.", "Shrift, rang, soya va animatsiya tanlang.", "Matn qancha vaqt ko'rinishini chetidan tortib o'zgartiring."] },
          { emoji: "🎵", title: "Musiqa qo'shish", points: ["**Audio** bo'limidan musiqa tanlang yoki o'zingiznikini import qiling.", "Musiqa videodan uzun bo'lsa — oxirini kesing.", "**Fade out** — musiqa oxirida sekin pasayadi."], tip: "Mualliflik huquqi: boshqalarning musiqasini ruxsatsiz ishlatmang. CapCut kutubxonasidagi musiqalar xavfsiz." },
        ],
        practice: [
          "Ko'rgazmada 3 ta klip qo'shing, bittasini ✂️ bilan kesib, ortiqcha qismini o'chiring.",
          "CapCut'ni oching va yangi loyiha yarating.",
          "O'qituvchi bergan 3 ta video/rasmni import qilib, vaqt chizig'iga joylang.",
          "Har bir klipni 5–7 soniyaga qisqartiring.",
          "Boshiga sarlavha matni, oxiriga \"Tugadi\" matnini qo'shing.",
          "Musiqa qo'shib, oxiriga Fade out bering va eksport qiling (720p).",
        ],
        homework: "Telefoningizda uydagi 3 ta qisqa video oling (masalan: mushuk, gul, oshxona). CapCut'da ularni birlashtirib, matn va musiqa qo'shing.",
        quiz: [
          { q: "CapCut'da klipni ikkiga bo'lish tugmasi?", options: ["Ctrl + S", "Ctrl + B", "Ctrl + P", "Alt + F4"], correct: 1 },
          { q: "Vaqt chizig'ida hozirgi joyni ko'rsatadigan chiziq nima?", options: ["Playhead", "Trek", "Filtr", "Stiker"], correct: 0 },
          { q: "Montaj nima?", options: ["Videoni o'chirish", "Video bo'laklarini kesib, ulab tayyor video qilish", "Faqat musiqa tinglash", "Kamerani sozlash"], correct: 1 },
          { q: "Musiqa oxirida sekin pasayishi effekti?", options: ["Fade out", "Zoom", "Split", "Crop"], correct: 0 },
          { q: "Qaysi musiqani ishlatish xavfsiz?", options: ["Istalgan mashhur qo'shiq", "CapCut kutubxonasidagi ruxsat berilgan musiqa", "Kinodan yozib olingan", "Do'stning ruxsatisiz qo'shig'i"], correct: 1 },
          { q: "Ijro/pauza qilish tugmasi?", options: ["Enter", "Space", "Tab", "Esc"], correct: 1 },
        ],
      },
      {
        title: "Mini loyiha — \"1 daqiqalik video\"",
        kind: "project",
        goals: ["Ssenariy (reja) tuzish", "60 soniyalik tugallangan video montaj qilish", "O'tishlar va effektlardan o'rinli foydalanish"],
        visual: "video-timeline",
        slides: [
          { emoji: "🎯", title: "Loyiha vazifasi", points: ["Mavzu tanlang: \"Mening kunim\", \"Sevimli hayvonim\", \"Maktabim\", \"Hunarim\".", "Video uzunligi: **50–60 soniya**.", "Boshlanish — asosiy qism — yakun."] },
          { emoji: "📝", title: "Ssenariy (storyboard)", points: ["Qog'ozga 6 ta katak chizing — har biri bitta sahna.", "Har katakka: nima ko'rinadi, qanday matn, necha soniya.", "Reja bo'lsa — montaj 2 marta tezroq!"] },
          { emoji: "🔀", title: "O'tishlar va effektlar", points: ["**Transitions** — klip orasidagi o'tish (Dissolve, Slide).", "**Effects** — video effektlari, ehtiyot bilan ishlating.", "**Filters** — butun videoga bir xil rang kayfiyati."] },
          { emoji: "📤", title: "Eksport", points: ["**Export** → o'lcham 1080p yoki 720p.", "Fayl nomi: `ism_1daqiqa.mp4`.", "Format: MP4 — hamma joyda ochiladi."] },
        ],
        practice: [
          "10 daqiqada 6 sahnali ssenariy chizing.",
          "Kerakli video/rasmlarni tayyorlang (o'qituvchi bergan yoki o'zingiz olgan).",
          "CapCut'da montaj qiling: kesish, matn, musiqa.",
          "Kamida 2 ta o'tish va 1 ta filtr qo'shing.",
          "Video 60 soniyadan oshmasligini tekshiring va eksport qiling.",
          "Sinfda 3–4 ta videoni birga tomosha qilamiz.",
        ],
        homework: "Videongizni oilangizga ko'rsating. Ular bergan 1 ta maslahat asosida videoni yaxshilang va qayta eksport qiling.",
        rubric: ["Ssenariy (reja) tuzilgan", "Video 50–60 soniya", "Boshlanish, asosiy qism, yakun bor", "Matn va musiqa o'rinli", "Kamida 2 ta o'tish, eksport MP4"],
        quiz: [
          { q: "Montajdan oldin nima tayyorlanadi?", options: ["Ssenariy (reja)", "Sertifikat", "Parol", "Jadval"], correct: 0 },
          { q: "Klip orasidagi o'tish effekti inglizcha?", options: ["Transition", "Export", "Split", "Import"], correct: 0 },
          { q: "Video hamma joyda ochilishi uchun qaysi format?", options: ["MP4", "DOCX", "XLSX", "ZIP"], correct: 0 },
          { q: "1 daqiqalik videoda nechta soniya bor?", options: ["30", "60", "100", "120"], correct: 1 },
          { q: "Butun videoga bir xil rang kayfiyati beradigan vosita?", options: ["Filter", "Split", "Text", "Audio"], correct: 0 },
        ],
      },
      {
        title: "Templates (shablonlar) bilan ishlash",
        kind: "lesson",
        goals: ["CapCut shablonlarini topish va ishlatish", "Shablonga o'z rasm/videolarini qo'yish", "Shablon va noldan montajning farqini tushunish"],
        slides: [
          { emoji: "🧩", title: "Shablon nima?", points: ["**Shablon (Template)** — tayyor montaj: musiqa, o'tish, effektlar bor.", "Siz faqat o'z rasm va videolaringizni qo'yasiz.", "Tez va chiroyli natija — 2–3 daqiqada!"] },
          { emoji: "🔍", title: "Shablon topish", points: ["CapCut → **Templates** bo'limi.", "Qidiruv: \"birthday\", \"travel\", \"school\".", "Har shablonda: nechta klip kerakligi va uzunligi yozilgan."] },
          { emoji: "🖼️", title: "Shablonni to'ldirish", points: ["**Use template** tugmasi.", "Kerakli miqdorda rasm/video tanlang.", "Matnlarni o'zingiznikiga almashtiring.", "Preview → Export."] },
          { emoji: "⚖️", title: "Shablon yoki noldan?", points: ["**Shablon** — tez, lekin boshqalarnikiga o'xshash.", "**Noldan** — ko'proq vaqt, lekin o'zingizga xos.", "Yaxshi montajchi ikkalasini ham biladi!"], tip: "Shablondan g'oya oling va keyin o'zingiz noldan takrorlab ko'ring — eng yaxshi mashq." },
        ],
        practice: [
          "CapCut'da Templates bo'limini oching va 3 ta shablonni ko'rib chiqing.",
          "\"Tug'ilgan kun\" yoki \"Sayohat\" shablonini tanlang.",
          "O'qituvchi bergan rasmlar bilan shablonni to'ldiring.",
          "Barcha matnlarni o'zbek tiliga almashtiring.",
          "Natijani eksport qiling va sinfdoshingiznikiga solishtiring.",
        ],
        homework: "Oila albomidan 5 ta rasm tanlab, shablon yordamida \"Oilaviy xotiralar\" videosini tayyorlang.",
        quiz: [
          { q: "Shablon (Template) nima?", options: ["Bo'sh loyiha", "Tayyor montaj — faqat o'z rasmlaringizni qo'yasiz", "Musiqa fayli", "Video kamera"], correct: 1 },
          { q: "Shablonni ishlatish tugmasi?", options: ["Use template", "Delete", "Split", "Crop"], correct: 0 },
          { q: "Shablonning kamchiligi?", options: ["Juda sekin", "Boshqalarnikiga o'xshash bo'lishi mumkin", "Musiqasi yo'q", "Eksport qilib bo'lmaydi"], correct: 1 },
          { q: "Shablondagi matnni nima qilish kerak?", options: ["O'zimiznikiga almashtirish", "O'chirmaslik", "Hech narsa", "Tarjima qilmaslik"], correct: 0 },
          { q: "Tayyor videoni saqlash nima deyiladi?", options: ["Import", "Export", "Template", "Filter"], correct: 1 },
        ],
      },
    ],
  },
  {
    title: "Sun'iy intellekt (matn va rasm)",
    days: [
      {
        title: "ChatGPT / Gemini / Claude kabi AI'dan foydalanish",
        kind: "lesson",
        goals: ["Sun'iy intellekt nima ekanini tushunish", "Yaxshi savol (prompt) yozishni o'rganish", "AI bilan xavfsiz va halol ishlash qoidalari"],
        visual: "prompt-builder",
        visualPreset: "matn",
        slides: [
          { emoji: "🤖", title: "Sun'iy intellekt (AI) nima?", points: ["Kompyuter dasturi, u **juda ko'p matn va rasmlardan o'rgangan**.", "Savolga javob beradi, matn yozadi, tarjima qiladi, rasm chizadi.", "Mashhur AI yordamchilar: **ChatGPT**, **Gemini**, **Claude**."] },
          { emoji: "💬", title: "Prompt nima?", points: ["**Prompt** — AI ga yozadigan buyruq yoki savolingiz.", "Yomon prompt: \"quyosh\".", "Yaxshi prompt: \"10 yoshli bolaga quyosh nima ekanini 5 ta qisqa gap bilan tushuntirib ber\"."] },
          { emoji: "🧱", title: "Yaxshi promptning 5 bo'lagi", points: ["**Rol**: \"Sen mehribon o'qituvchisan\".", "**Vazifa**: \"tushuntirib ber / ertak yoz\".", "**Mavzu**: \"quyosh tizimi haqida\".", "**Kim uchun**: \"10 yoshli bola uchun\".", "**Shakl**: \"5 punkt, emoji bilan\"."] },
          { emoji: "⚠️", title: "AI ham xato qiladi!", points: ["AI ba'zan **noto'g'ri** yoki o'ylab topilgan javob beradi.", "Muhim ma'lumotni kitob yoki o'qituvchidan **tekshiring**.", "Uy vazifasini AI ga to'liq yozdirish — halol emas. AI — yordamchi, sizning o'rningizga o'ylamaydi."] },
          { emoji: "🔐", title: "Xavfsizlik qoidalari", points: ["Hech qachon **parol, manzil, telefon raqam** yozmang.", "Shaxsiy rasmlaringizni yuklamang.", "Ota-ona yoki o'qituvchi ruxsati bilan foydalaning."] },
        ],
        practice: [
          "Ko'rgazmadagi prompt konstruktorida 5 bo'lakli \"Matn\" promptini yig'ing.",
          "O'qituvchi ekranida AI ga bir xil savolni **yomon** va **yaxshi** prompt bilan beramiz — farqini solishtiramiz.",
          "Juftlikda: AI dan \"do'stlik haqida 4 qatorli she'r\" so'rang, keyin uni yaxshilashni so'rang.",
          "AI ga 3 ta savol bering va javobini darslikdan tekshiring: to'g'rimi?",
          "Sinf bilan \"AI xavfsizlik qoidalari\" plakatini tuzamiz.",
        ],
        homework: "Ota-onangiz bilan birga AI dan sevimli hayvoningiz haqida 5 ta qiziqarli fakt so'rang. Faktlardan birini internet yoki kitobdan tekshirib, daftarga yozing.",
        quiz: [
          { q: "AI ga yoziladigan buyruq yoki savol nima deyiladi?", options: ["Parol", "Prompt", "Fayl", "Brauzer"], correct: 1 },
          { q: "Qaysi prompt yaxshiroq?", options: ["\"kosmos\"", "\"10 yoshli bolaga kosmos haqida 5 ta qiziqarli faktni emoji bilan yoz\"", "\"yoz\"", "\"???\""], correct: 1 },
          { q: "AI ga nimani yozish mumkin EMAS?", options: ["Hayvonlar haqida savol", "O'z uy manzilingiz va parolingiz", "She'r so'rash", "Tarjima so'rash"], correct: 1 },
          { q: "AI javobi har doim to'g'rimi?", options: ["Ha, doim", "Yo'q, xato qilishi mumkin — tekshirish kerak", "Faqat kechasi xato qiladi", "Faqat ingliz tilida to'g'ri"], correct: 1 },
          { q: "Qaysi biri AI yordamchi emas?", options: ["ChatGPT", "Gemini", "Claude", "Paint"], correct: 3 },
          { q: "Uy vazifasida AI dan qanday foydalanish halol?", options: ["Hammasini AI yozadi", "Tushunmagan mavzuni tushuntirishni so'rash", "AI javobini o'zimniki deb topshirish", "Umuman foydalanmaslik shart"], correct: 1 },
        ],
      },
      {
        title: "AI yordamida rasm tayyorlash",
        kind: "lesson",
        goals: ["Rasm uchun prompt tuzish", "Uslub, rang va kompozitsiyani boshqarish", "Natijani yaxshilash (iteratsiya)"],
        visual: "prompt-builder",
        visualPreset: "rasm",
        slides: [
          { emoji: "🖼️", title: "Matndan rasm", points: ["AI siz yozgan **tasvirga qarab** yangi rasm chizadi.", "Vositalar: Gemini, ChatGPT, Ideogram, Leonardo va boshqalar.", "Har safar yangi, takrorlanmas rasm chiqadi."] },
          { emoji: "🧩", title: "Rasm promptining formulasi", points: ["**Kim/nima** + **nima qilyapti** + **qayerda** + **uslub** + **rang/kayfiyat**.", "Misol: \"qizil mushukcha kitob o'qiyapti, sehrli o'rmonda, multfilm uslubida, yorqin quvnoq ranglar\"."] },
          { emoji: "🎨", title: "Uslublar", points: ["Multfilm, akvarel, 3D, piksel-art, realistik foto, qalam chizma.", "Bitta promptni turli uslubda sinab ko'ring — natija butunlay o'zgaradi!"] },
          { emoji: "🔁", title: "Yaxshilash", points: ["Birinchi rasm har doim ham zo'r chiqmaydi.", "Aniqroq so'z qo'shing: \"yaqin plan\", \"orqa fonda tog'lar\".", "Keraksiz narsani olib tashlashni so'rang."], tip: "AI ba'zan qo'l barmoqlarini noto'g'ri chizadi — bu uning zaif joyi!" },
        ],
        practice: [
          "Ko'rgazmada 5 yulduzli rasm promptini yig'ib, nusxa oling.",
          "O'qituvchi bilan AI rasm vositasida promptingizni sinab ko'ring.",
          "Xuddi shu promptni 3 xil uslubda (multfilm, akvarel, 3D) yarating.",
          "Eng yoqqan rasmni tanlab, uni yana 1 marta yaxshilang.",
          "Rasmlarni papkangizga saqlang va promptni yonidagi matn faylga yozing.",
        ],
        homework: "\"Kelajakdagi Toshkent\" mavzusida 3 ta turli prompt yozing (daftarga). Keyingi darsda eng yaxshisini AI da sinab ko'ramiz.",
        quiz: [
          { q: "Rasm promptiga nimani qo'shish natijani aniqroq qiladi?", options: ["Uslub va rang", "Parol", "Telefon raqam", "Hech narsa"], correct: 0 },
          { q: "\"Akvarel\", \"3D\", \"piksel-art\" — bular nima?", options: ["Rasm uslublari", "Dasturlar", "Fayl turlari", "Ranglar"], correct: 0 },
          { q: "Birinchi rasm yoqmasa nima qilamiz?", options: ["Kompyuterni o'chiramiz", "Promptni aniqlashtirib, qayta so'raymiz", "AI ni urishamiz", "Rasmni chop etamiz"], correct: 1 },
          { q: "AI rasmlarida ko'p uchraydigan xato?", options: ["Qo'l barmoqlari noto'g'ri", "Rang yo'q", "Rasm yo'q", "Juda kichik"], correct: 0 },
          { q: "Qaysi prompt rasm uchun eng yaxshi?", options: ["\"it\"", "\"it yuguryapti\"", "\"oq kuchukcha qor ustida yuguryapti, tog'lar fonida, multfilm uslubida, iliq ranglar\"", "\"chiroyli rasm\""], correct: 2 },
        ],
      },
      {
        title: "AI rasm: loyiha — \"Mening ertak qahramonim\"",
        kind: "project",
        goals: ["Bir xil qahramonni turli sahnalarda yaratish", "Rasmlardan kichik hikoya (komiks) tuzish", "AI rasm etikasini tushunish"],
        visual: "prompt-builder",
        visualPreset: "rasm",
        slides: [
          { emoji: "🦸", title: "Loyiha", points: ["O'z ertak qahramoningizni o'ylab toping.", "AI yordamida **4 sahnali** rasm-hikoya (komiks) yarating.", "Har rasm tagiga 1 gap yozing."] },
          { emoji: "🔁", title: "Qahramonni bir xil saqlash", points: ["Har promptda qahramonni **bir xil so'zlar** bilan tasvirlang.", "Masalan: \"ko'k shlyapali kichkina robot, katta yashil ko'zlari bor\".", "Faqat joy va harakatni o'zgartiring."] },
          { emoji: "⚖️", title: "AI rasm etikasi", points: ["AI rasmini **\"AI yordamida yaratildi\"** deb belgilang.", "Real odamlarning soxta rasmlarini yaratmang.", "Boshqa rassomlar ishini o'zingizniki deb ko'rsatmang."] },
          { emoji: "📑", title: "Yig'ish", points: ["4 rasmni PowerPoint yoki Canva'da bitta sahifaga joylang.", "Sarlavha: qahramon ismi.", "Pastida: \"AI yordamida yaratildi\"."] },
        ],
        practice: [
          "Qahramon tasvirini 1 gapda yozing (tashqi ko'rinishi).",
          "4 sahnali hikoya rejasini tuzing: boshlanish, muammo, harakat, yakun.",
          "Har sahna uchun prompt yozib, AI da rasm yarating.",
          "Rasmlarni bitta sahifaga joylab, har biriga 1 gap yozing.",
          "Sinfga komiksingizni ko'rsating.",
        ],
        homework: "Komiksingizni ukangiz/singlingiz yoki do'stingizga ertak qilib aytib bering. Ularga qaysi sahna yoqqanini so'rang.",
        rubric: ["Qahramon hamma rasmda o'xshash", "4 sahna mantiqiy hikoya tuzadi", "Har rasmda izoh gap bor", "\"AI yordamida yaratildi\" belgisi qo'yilgan"],
        quiz: [
          { q: "Qahramon hamma rasmda bir xil chiqishi uchun?", options: ["Har safar boshqa tasvirlash", "Uni har promptda bir xil so'zlar bilan tasvirlash", "Faqat 1 so'z yozish", "Uslubni har safar almashtirish"], correct: 1 },
          { q: "AI yaratgan rasmni qanday belgilash kerak?", options: ["\"Men chizdim\"", "\"AI yordamida yaratildi\"", "Hech qanday", "Rassom ismi bilan"], correct: 1 },
          { q: "Qaysi biri noto'g'ri harakat?", options: ["Ertak qahramoni yaratish", "Haqiqiy odamning soxta rasmini yaratib tarqatish", "Komiks tuzish", "Rasmga izoh yozish"], correct: 1 },
          { q: "Hikoya tuzilishi qanday?", options: ["Faqat yakun", "Boshlanish — muammo — harakat — yakun", "Tasodifiy rasmlar", "Faqat sarlavha"], correct: 1 },
          { q: "Promptlar orasida nimani o'zgartiramiz?", options: ["Qahramon tashqi ko'rinishini", "Joy va harakatni", "Hamma narsani", "Hech narsani"], correct: 1 },
        ],
      },
    ],
  },
  {
    title: "AI video va audio generatsiyasi",
    days: [
      {
        title: "QWEN va boshqa AI'lar bilan video tayyorlash",
        kind: "lesson",
        goals: ["Matndan va rasmdan video yaratishni bilish", "Video prompt tuzilishi: qahramon, harakat, kamera", "AI video cheklovlarini tushunish"],
        visual: "prompt-builder",
        visualPreset: "video",
        slides: [
          { emoji: "🎥", title: "AI video", points: ["AI endi **qisqa videolar** ham yarata oladi (5–10 soniya).", "Vositalar: **Qwen**, Kling, Pika va boshqalar.", "Ikki yo'l: **matndan video** va **rasmdan video**."] },
          { emoji: "🧱", title: "Video prompt", points: ["**Qahramon** — kim?", "**Harakat** — nima qilyapti?", "**Kamera** — qanday ko'rinish (yaqinlashish, yuqoridan, ortidan)?", "**Uslub** — multfilm, kino, slow motion.", "**Davomiyligi** — 5 yoki 10 soniya."] },
          { emoji: "🖼️➡️🎞️", title: "Rasmdan video", points: ["Oldingi darsdagi AI rasmingizni yuklang.", "Qanday harakat qilishini yozing: \"robot qo'l silkitadi\".", "Rasm \"jonlanadi\"!"] },
          { emoji: "⏳", title: "Cheklovlar", points: ["Video yaratish **bir necha daqiqa** davom etadi.", "Bepul versiyada kunlik limit bor.", "Murakkab harakatlarda xatolar bo'ladi — sodda harakat tanlang."] },
        ],
        practice: [
          "Ko'rgazmada video promptini yig'ing (5 bo'lak ham tanlansin).",
          "O'qituvchi ekranida Qwen'da matndan video yaratamiz.",
          "Guruhlarda: har guruh bittadan prompt yozadi, o'qituvchi yaratib beradi.",
          "O'z AI rasmingizdan \"jonli rasm\" video yarating.",
          "Natijalarni solishtiring: qaysi prompt yaxshiroq ishladi va nega?",
        ],
        homework: "3 ta qisqa video prompt yozing: biri tabiat, biri hayvon, biri sport haqida. Har birida kamera harakatini ko'rsating.",
        quiz: [
          { q: "AI video odatda qancha davom etadi?", options: ["5–10 soniya", "2 soat", "1 kun", "30 daqiqa"], correct: 0 },
          { q: "Video promptida \"kamera sekin yaqinlashadi\" nimani bildiradi?", options: ["Kamera harakatini", "Musiqani", "Rangni", "Fayl nomini"], correct: 0 },
          { q: "Qaysi biri AI video vositasi?", options: ["Qwen", "Excel", "Paint", "Word"], correct: 0 },
          { q: "AI videoda xato kamroq bo'lishi uchun?", options: ["Juda murakkab harakat yozish", "Sodda va aniq harakat yozish", "Promptsiz yaratish", "Faqat raqam yozish"], correct: 1 },
          { q: "Rasmdan video yaratish nima?", options: ["Rasmni o'chirish", "Rasmni \"jonlantirish\" — harakatga keltirish", "Rasmni chop etish", "Rasmni ZIP qilish"], correct: 1 },
        ],
      },
      {
        title: "AI video: mini film yig'ish",
        kind: "project",
        goals: ["Bir nechta AI klipni bitta videoga birlashtirish", "CapCut'da AI kliplarni montaj qilish", "Ovoz va matn bilan hikoya qilish"],
        visual: "video-timeline",
        slides: [
          { emoji: "🎞️", title: "Mini film", points: ["3–4 ta AI klip (har biri 5 soniya) = **20 soniyalik mini film**.", "Bitta qahramon, bitta hikoya.", "CapCut'da birlashtiramiz."] },
          { emoji: "🗺️", title: "Reja", points: ["1-klip: qahramon bilan tanishuv.", "2-klip: sarguzasht boshlanadi.", "3-klip: qiyin vaziyat.", "4-klip: baxtli yakun."] },
          { emoji: "🔊", title: "Ovoz", points: ["Musiqa: CapCut kutubxonasi yoki keyingi darsdagi AI musiqa.", "Ovozli izoh: CapCut'da **Voiceover** — o'zingiz gapirasiz.", "Subtitr: **Auto captions** — gapingizni matnga aylantiradi."] },
          { emoji: "🏷️", title: "Titrlar", points: ["Boshida: film nomi.", "Oxirida: \"Rejissyor: [ismingiz]\", \"AI yordamida yaratildi\"."] },
        ],
        practice: [
          "4 klipli hikoya rejasini yozing.",
          "Har klip uchun prompt tuzing va AI videolarni yarating (yoki o'qituvchi bergan kliplardan foydalaning).",
          "CapCut'da kliplarni tartib bilan joylang, o'tishlar qo'shing.",
          "Voiceover bilan 1–2 gap gapiring yoki musiqa qo'ying.",
          "Boshlanish va yakuniy titrlarni qo'shib eksport qiling.",
        ],
        homework: "Mini filmingizga Auto captions (avtomatik subtitr) qo'shing va xatolarini qo'lda tuzating.",
        rubric: ["3–4 ta klip bitta hikoyani aytadi", "O'tishlar silliq", "Ovoz yoki musiqa bor", "Boshlanish va yakuniy titr", "\"AI yordamida yaratildi\" belgisi"],
        quiz: [
          { q: "4 ta 5 soniyalik klip necha soniyalik film bo'ladi?", options: ["9", "20", "45", "54"], correct: 1 },
          { q: "CapCut'da o'z ovozingizni yozish funksiyasi?", options: ["Voiceover", "Split", "Filter", "Crop"], correct: 0 },
          { q: "Gapni avtomatik matnga aylantiruvchi funksiya?", options: ["Auto captions", "Transition", "Template", "Export"], correct: 0 },
          { q: "Film oxiridagi \"Rejissyor: ...\" yozuvi nima?", options: ["Titr", "Filtr", "Stiker", "Trek"], correct: 0 },
          { q: "Kliplar qanday tartibda bo'lishi kerak?", options: ["Tasodifiy", "Hikoya rejasi bo'yicha", "Uzunligi bo'yicha", "Alifbo bo'yicha"], correct: 1 },
        ],
      },
      {
        title: "SUNO AI va GEMINI orqali musiqa yaratish",
        kind: "lesson",
        goals: ["AI bilan qo'shiq yaratishni o'rganish", "Janr, kayfiyat va asboblarni tanlash", "Qo'shiq so'zlarini AI bilan birga yozish"],
        visual: "prompt-builder",
        visualPreset: "musiqa",
        slides: [
          { emoji: "🎶", title: "AI musiqa", points: ["**Suno AI** — so'zlar va uslubdan to'liq qo'shiq yaratadi (ovoz bilan!).", "**Gemini** — qo'shiq so'zlarini yozishga yordam beradi.", "Qo'shiq 1–3 daqiqa bo'ladi."] },
          { emoji: "🎼", title: "Musiqa tushunchalari", points: ["**Janr**: pop, rok, bolalar qo'shig'i, xalq uslubi, lo-fi.", "**Temp**: tez (energik) yoki sekin (sokin).", "**Asboblar**: pianino, gitara, doira, rubob, baraban.", "**Naqarat** — qo'shiqning takrorlanadigan qismi."] },
          { emoji: "✍️", title: "So'z yozish", points: ["Gemini ga: \"Maktab va do'stlik haqida 2 bandli va naqaratli bolalar qo'shig'i yoz\".", "So'zlarni o'zingiz tahrir qiling — qofiyasini tekshiring.", "Suno'ga so'zlar + uslub yozing: \"quvnoq bolalar pop, pianino va baraban\"."] },
          { emoji: "©️", title: "Mualliflik", points: ["AI qo'shig'ini maktab loyihasida ishlatish mumkin.", "Mashhur qo'shiqchilar ovozini taqlid qilishni so'ramang.", "Qo'shiq nomi va \"AI yordamida yaratildi\" deb yozing."] },
        ],
        practice: [
          "Ko'rgazmada musiqa promptini yig'ing.",
          "Gemini yordamida sinf qo'shig'i so'zlarini yozamiz (2 band + naqarat).",
          "So'zlarni birga tahrir qilamiz — sinf nomi va o'qituvchi ismini qo'shamiz.",
          "O'qituvchi ekranida Suno'da 2 xil janrda qo'shiq yaratamiz.",
          "Ovoz beramiz: qaysi variant sinf madhiyasi bo'ladi?",
        ],
        homework: "Onangiz yoki buvingiz haqida 4 qatorli qo'shiq so'zi yozing (AI yordamida yoki o'zingiz). Qaysi janrda bo'lishini tanlang.",
        quiz: [
          { q: "Ovoz bilan to'liq qo'shiq yaratadigan AI?", options: ["Suno AI", "Excel", "Paint", "Scratch"], correct: 0 },
          { q: "Qo'shiqning takrorlanadigan qismi nima deyiladi?", options: ["Naqarat", "Titr", "Slayd", "Katak"], correct: 0 },
          { q: "\"Pop\", \"rok\", \"lo-fi\" — bular nima?", options: ["Janrlar", "Asboblar", "Dasturlar", "Fayllar"], correct: 0 },
          { q: "Qaysi so'rov noto'g'ri?", options: ["Quvnoq bolalar qo'shig'i", "Mashhur qo'shiqchi ovozini aynan taqlid qil", "Doira va rubob bilan", "Sokin lo-fi"], correct: 1 },
          { q: "Tez temp qanday kayfiyat beradi?", options: ["Energik", "Uyqu", "G'amgin", "Jim"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Umumiy yakun",
    days: [
      {
        title: "MonkeyType yordamida musobaqa",
        kind: "event",
        goals: ["Tez va to'g'ri yozish ko'nikmasini oshirish", "10 barmoq usuli bilan tanishish", "Do'stona musobaqada qatnashish"],
        visual: "typing",
        slides: [
          { emoji: "⌨️", title: "Nega tez yozish kerak?", points: ["Dasturchi, dizayner, jurnalist — hamma klaviaturada yozadi.", "Tez yozsangiz — vaqtingiz tejaladi.", "O'lchov birligi: **WPM** — daqiqada so'zlar soni."] },
          { emoji: "🖐️", title: "10 barmoq usuli", points: ["Asosiy qator: chap qo'l **A S D F**, o'ng qo'l **J K L ;**.", "**F** va **J** da kichik bo'rtiq bor — ko'rmasdan topasiz.", "Bosh barmoqlar — probel (Space)."], tip: "Klaviaturaga emas, ekranga qarang!" },
          { emoji: "🎯", title: "Tezlik va aniqlik", points: ["Avval **aniqlik**, keyin tezlik!", "95%+ aniqlik — yaxshi natija.", "Har kuni 10 daqiqa mashq — 1 oyda 2 barobar tezroq."] },
          { emoji: "🏆", title: "Musobaqa qoidalari", points: ["**monkeytype.com** — 30 soniyalik test.", "Har ishtirokchi 3 urinish, eng yaxshisi hisoblanadi.", "G'oliblar: eng tez, eng aniq, eng ko'p o'sgan."] },
        ],
        practice: [
          "Ko'rgazmadagi tez yozish testida 30 soniyalik mashq qiling.",
          "Barmoqlarni asosiy qatorga qo'yish mashqi (5 daqiqa).",
          "monkeytype.com da 3 ta urinish — natijalarni daftarga yozing.",
          "Musobaqa: sinf jadvaliga WPM va aniqlikni kiritamiz.",
          "G'oliblarni taqdirlash 🏆.",
        ],
        homework: "Har kuni 10 daqiqa monkeytype.com yoki keybr.com da mashq qiling. Bir haftalik natijalaringizni jadvalga yozing.",
        quiz: [
          { q: "WPM nima?", options: ["Daqiqada so'zlar soni", "Kompyuter xotirasi", "Fayl turi", "Parol"], correct: 0 },
          { q: "Qaysi tugmalarda kichik bo'rtiq bor?", options: ["A va L", "F va J", "Q va P", "Enter va Space"], correct: 1 },
          { q: "Tez yozishda nima birinchi o'rinda?", options: ["Aniqlik", "Faqat tezlik", "Klaviaturaga qarash", "Bitta barmoq"], correct: 0 },
          { q: "Probelni qaysi barmoq bilan bosamiz?", options: ["Ko'rsatkich", "Bosh barmoq", "Jimjiloq", "O'rta barmoq"], correct: 1 },
          { q: "Chap qo'lning asosiy qatori?", options: ["Q W E R", "A S D F", "Z X C V", "J K L ;"], correct: 1 },
        ],
      },
      {
        title: "AI yordamida slayd tayyorlash",
        kind: "lesson",
        goals: ["AI bilan taqdimot rejasi va matnini tayyorlash", "Gamma/Canva AI kabi vositalarda slayd yaratish", "AI natijasini tekshirish va tahrirlash"],
        visual: "prompt-builder",
        visualPreset: "slayd",
        slides: [
          { emoji: "📑", title: "AI + taqdimot", points: ["AI bir necha soniyada **reja, matn va dizayn** tayyorlaydi.", "Vositalar: **Gamma**, **Canva AI**, Gemini (Google Slides).", "Lekin **tekshirish va tahrir** — sizning ishingiz!"] },
          { emoji: "🧾", title: "Slayd uchun prompt", points: ["Nechta slayd? Mavzu? Kim uchun?", "Har slaydda nima bo'lsin?", "Dizayn uslubi.", "Misol: \"4-sinf uchun 'Kosmos sirlari' mavzusida 7 slayd; har slaydda sarlavha, 3 punkt va rasm g'oyasi; yorqin ranglar\"."] },
          { emoji: "🔍", title: "Tekshirish ro'yxati", points: ["Faktlar to'g'rimi? (kitobdan tekshiring)", "Matn juda uzun emasmi?", "Rasmlar mavzuga mosmi?", "Imlo xatolari bormi?"] },
          { emoji: "✋", title: "O'zingiznikini qo'shing", points: ["Kamida 1 ta slaydni **o'zingiz** yozing.", "O'z rasmingiz yoki chizmangizni qo'shing.", "Shunda taqdimot haqiqatan sizniki bo'ladi."] },
        ],
        practice: [
          "Ko'rgazmada slayd promptini yig'ing.",
          "Mavzu tanlang (Kosmos, Hayvonlar, O'zbekiston shaharlari, Sog'lom turmush).",
          "Gamma yoki Canva AI da 5–7 slaydli taqdimot yarating.",
          "Tekshirish ro'yxati bo'yicha 3 ta narsani tuzating.",
          "1 ta slaydni o'zingiz qo'shing va sinfga 1 daqiqa taqdim qiling.",
        ],
        homework: "AI bilan yaratgan taqdimotingizni PowerPoint'ga eksport qiling va ikkita slayddagi matnni o'z so'zlaringiz bilan qayta yozing.",
        quiz: [
          { q: "AI bilan slayd yaratish vositasi?", options: ["Gamma", "Paint", "Kalkulyator", "MonkeyType"], correct: 0 },
          { q: "AI yaratgan taqdimotdan keyin nima qilish shart?", options: ["Darhol topshirish", "Faktlar va matnni tekshirib tahrirlash", "O'chirish", "Hech narsa"], correct: 1 },
          { q: "Slayd promptida nima bo'lishi kerak?", options: ["Slaydlar soni, mavzu, auditoriya", "Faqat \"slayd\" so'zi", "Parol", "Telefon raqami"], correct: 0 },
          { q: "Taqdimot haqiqatan sizniki bo'lishi uchun?", options: ["O'z slaydingiz va fikringizni qo'shish", "AI nomini o'chirish", "Ko'proq animatsiya", "Shriftni kattalashtirish"], correct: 0 },
          { q: "Qaysi biri tekshirish ro'yxatiga kirmaydi?", options: ["Faktlar to'g'riligi", "Imlo xatolari", "Kompyuter narxi", "Matn uzunligi"], correct: 2 },
        ],
      },
      {
        title: "CANVA bilan dizayn",
        kind: "lesson",
        goals: ["Canva interfeysi va shablonlari bilan ishlash", "Poster, taklifnoma yoki sertifikat yaratish", "Dizayn asoslari: rang, shrift, joylashuv"],
        slides: [
          { emoji: "🎨", title: "Canva nima?", points: ["Onlayn dizayn platformasi: **canva.com**.", "Poster, taklifnoma, Instagram post, taqdimot, sertifikat.", "Minglab bepul shablon, rasm va shriftlar."] },
          { emoji: "🧭", title: "Canva oynasi", points: ["Chapda: **Shablonlar, Elementlar, Matn, Yuklamalar**.", "O'rtada: dizayn sahifasi.", "Yuqorida: tanlangan element sozlamalari (rang, shrift, shaffoflik)."] },
          { emoji: "📐", title: "Dizayn qoidalari", points: ["**2–3 ta rang** yetarli.", "**2 xil shrift**: sarlavha uchun va matn uchun.", "Muhim narsa — **katta**, ikkinchi darajali — kichikroq.", "Bo'sh joy (oq joy) qoldiring — nafas olsin!"], tip: "Canva'da Magic Design — AI rasmingizga qarab dizayn taklif qiladi." },
          { emoji: "⬇️", title: "Yuklab olish", points: ["**Share → Download**.", "PNG — rasm, PDF — chop etish uchun.", "Havola bilan ulashish ham mumkin."] },
        ],
        practice: [
          "canva.com ga kiring (o'qituvchi akkaunti yoki o'z akkauntingiz).",
          "\"Poster\" shablonini tanlang: mavzu — \"IT Kids — 2 oyda nimalarni o'rgandim\".",
          "Sarlavha, 4 ta o'rgangan narsangiz va ikonkalarni qo'shing.",
          "Ranglarni 2–3 taga cheklang, shriftlarni tartibga keltiring.",
          "PNG formatda yuklab oling va sinf galereyasiga yuboring.",
        ],
        homework: "Canva'da oilangizdan biriga tabrik kartochkasi yarating (tug'ilgan kun yoki bayram) va PDF qilib yuklab oling.",
        quiz: [
          { q: "Canva nima?", options: ["Onlayn dizayn platformasi", "Antivirus", "O'yin", "Brauzer"], correct: 0 },
          { q: "Dizaynda nechta rang ishlatish tavsiya etiladi?", options: ["1", "2–3", "10", "Qancha ko'p shuncha yaxshi"], correct: 1 },
          { q: "Chop etish uchun qaysi format yaxshi?", options: ["PDF", "MP3", "ZIP", "TXT"], correct: 0 },
          { q: "Nima uchun bo'sh joy qoldiramiz?", options: ["Dizayn toza va o'qishli bo'lishi uchun", "Joy tejash", "Rang yo'qligi uchun", "Xato"], correct: 0 },
          { q: "Canva'da ikonkalar va shakllar qaysi bo'limda?", options: ["Elementlar", "Download", "Share", "Fayl"], correct: 0 },
        ],
      },
    ],
  },
];
