import type { WeekDraft } from "./types";

// 3-OY: SCRATCH DASTURLASH ASOSLARI
// Sinf ishi va uy vazifalari Notion'dagi "Scratch — kunlik amaliy topshiriqlar" sahifasi asosida.
export const month3: WeekDraft[] = [
  {
    title: "Tanishuv va harakat",
    days: [
      {
        title: "Scratch interfeysi, bloklar, sprite'lar",
        kind: "lesson",
        goals: ["scratch.mit.edu da akkaunt ochish", "Sahna, sprite paneli, bloklar palitrasi va kod maydonini tanish", "Sprite va fon tanlash, o'lcham va nomni o'zgartirish"],
        visual: "scratch",
        visualPreset: "motion",
        slides: [
          { emoji: "🐱", title: "Scratch nima?", points: ["**Scratch** — bloklardan dastur tuzish tili. MIT universiteti yaratgan.", "Kod yozish o'rniga **rangli bloklarni** LEGO kabi ulaymiz.", "Scratch'da o'yin, animatsiya, multfilm va viktorina yaratish mumkin."] },
          { emoji: "🧭", title: "Scratch oynasi", points: ["**Sahna** (o'ngda yuqorida) — natija shu yerda ko'rinadi.", "**Sprite paneli** (o'ngda pastda) — qahramonlar ro'yxati.", "**Bloklar palitrasi** (chapda) — rangli bloklar.", "**Kod maydoni** (o'rtada) — bloklarni shu yerga sudraymiz."] },
          { emoji: "🧸", title: "Sprite va fon", points: ["**Sprite** — sahnadagi qahramon yoki buyum (mushuk, it, to'p).", "**Backdrop (fon)** — sahna orqa rasmi.", "Yangi sprite: pastki o'ngdagi 🐱+ tugmasi → kutubxona.", "Sprite nomi va **o'lchami** (Size) ni sprite panelida o'zgartiramiz."] },
          { emoji: "📍", title: "Koordinatalar", points: ["Sahna markazi: **x: 0, y: 0**.", "x — chapga-o'ngga (−240 … 240).", "y — pastga-yuqoriga (−180 … 180)."], tip: "Login va parolni daftarga yozib qo'ying — keyingi darsda kerak bo'ladi!" },
          { emoji: "🎨", title: "Blok ranglari", points: ["🔵 **Harakat** — yurish, burilish.", "🟣 **Ko'rinish** — gapirish, kostyum.", "🩷 **Tovush** — musiqa.", "🟡 **Voqealar** — bayroq bosilganda.", "🟠 **Boshqaruv** — takrorlash, shart, kutish."] },
        ],
        practice: [
          "scratch.mit.edu saytiga kirish, akkaunt ochish (login/parolni daftarga yozib qo'yish).",
          "Interfeys bilan tanishuv: sahna, sprite paneli, bloklar palitrasi, kod maydoni.",
          "Mushukni o'chirib, o'ziga yoqqan 2 ta sprite tanlash (kutubxonadan).",
          "Fon (backdrop) tanlash va sprite'ni sichqoncha bilan sahnada joylashtirish.",
          "Sprite o'lchamini va nomini o'zgartirish.",
          "Ko'rgazmada 1-topshiriqni bajaring: mushuk \"Salom!\" desin va yursin.",
        ],
        homework: "Uyda Scratch'ga kirib, **«Mening sahnam»** loyihasini yaratish: 3 ta sprite + 1 ta fon tanlab, sahnani bezash. Loyiha nomini o'z ismi bilan saqlash.",
        quiz: [
          { q: "Scratch'da sahnadagi qahramon nima deyiladi?", options: ["Sprite", "Backdrop", "Blok", "Kursor"], correct: 0 },
          { q: "Sahna orqa rasmi nima deyiladi?", options: ["Kostyum", "Backdrop (fon)", "Sprite", "Palitra"], correct: 1 },
          { q: "Sahna markazining koordinatalari?", options: ["x: 100, y: 100", "x: 0, y: 0", "x: 240, y: 180", "x: −240, y: 0"], correct: 1 },
          { q: "Harakat bloklari qaysi rangda?", options: ["Ko'k", "Sariq", "Binafsha", "Yashil"], correct: 0 },
          { q: "Bloklarni qayerga sudrab qo'yamiz?", options: ["Sahnaga", "Kod maydoniga", "Sprite paneliga", "Brauzer manzil satriga"], correct: 1 },
          { q: "Scratch'ni kim yaratgan?", options: ["MIT universiteti", "Microsoft", "Google", "Apple"], correct: 0 },
        ],
      },
      {
        title: "Harakat va tovush bloklari",
        kind: "lesson",
        goals: ["Harakat bloklari bilan sprite'ni boshqarish", "Sprite'ni gapirtirish va o'ylatish", "Tovush qo'shish va chalish"],
        visual: "scratch",
        visualPreset: "motion",
        slides: [
          { emoji: "🚶", title: "Harakat bloklari", points: ["«**10 qadam yur**» — sprite qarab turgan tomonga yuradi.", "«**15 gradus buril**» — ↻ o'ngga yoki ↺ chapga.", "«**x: … y: … ga bor**» — aniq nuqtaga sakraydi.", "«**… soniyada x: y: ga sirpan**» — silliq harakat."] },
          { emoji: "⬜", title: "Kvadrat bo'ylab yurish", points: ["Kvadratning 4 tomoni, har burchak 90°.", "Yur 100 → buril 90° → 4 marta takrorlaymiz.", "4 × 90° = 360° — to'liq aylana, sprite joyiga qaytadi!"], code: "🏁 bayroq bosilganda\n  100 qadam yur\n  ↻ 90 gradus buril\n  100 qadam yur\n  ↻ 90 gradus buril\n  ... (yana 2 marta)" },
          { emoji: "💬", title: "Gapirish", points: ["«**Salom! 2 soniya de**» — gap pufagi chiqadi.", "«**Hmm... deb o'yla**» — o'y pufagi.", "Suhbat uchun «kut» bloki bilan navbat qiling."] },
          { emoji: "🔊", title: "Tovush", points: ["**Sounds** yorlig'i → kutubxonadan tovush tanlang.", "«**tovushni chal**» — chaladi va davom etadi.", "«**tovushni oxirigacha chal**» — tugashini kutadi."] },
        ],
        practice: [
          "«10 qadam yur», «15 gradus buril», «x:… y:… ga bor» bloklarini sinash.",
          "Sprite'ni sahna bo'ylab kvadrat shaklida yurgizish (ko'rgazmadagi 2-topshiriq).",
          "«… degin», «… deb o'yla» bloklari bilan sprite'ni gapirtirish.",
          "Tovush qo'shish: kutubxonadan tovush tanlash va «tovushni chal» bloki.",
          "Mini mashq: mushuk yurib borib, devorga yetganda «Voy!» deydi va tovush chiqaradi (ko'rgazmadagi 3-topshiriq).",
        ],
        homework: "Sprite sahnaning **4 burchagiga** navbat bilan borib, har burchakda bittadan gap aytadigan loyiha qilish (masalan, o'zi haqida 4 ta fakt).",
        quiz: [
          { q: "Sprite'ni aniq nuqtaga olib boradigan blok?", options: ["10 qadam yur", "x: … y: … ga bor", "15 gradus buril", "tovushni chal"], correct: 1 },
          { q: "Kvadrat chizish uchun har burchakda necha gradus burilamiz?", options: ["45", "60", "90", "180"], correct: 2 },
          { q: "Gap pufagini chiqaradigan blok qaysi guruhda?", options: ["Harakat", "Ko'rinish", "Tovush", "Voqealar"], correct: 1 },
          { q: "Sprite 4 marta 90° burilsa, jami necha gradus?", options: ["90", "180", "270", "360"], correct: 3 },
          { q: "Tovush tugaguncha kutib, keyin davom etadigan blok?", options: ["tovushni chal", "tovushni oxirigacha chal", "hamma tovushlarni to'xtat", "ovoz balandligini o'rnat"], correct: 1 },
          { q: "Natija: sprite qayerda bo'ladi?", code: "x: 0 y: 0 ga bor\n50 qadam yur  (o'ngga qarab turibdi)", options: ["x: 0", "x: 50", "x: −50", "y: 50"], correct: 1 },
        ],
      },
      {
        title: "Mini loyiha — «Mening birinchi animatsiyam»",
        kind: "project",
        goals: ["Kostyumlar orqali harakat effekti yaratish", "Ikki sprite suhbatini animatsiya qilish", "Fon almashishi bilan sahna o'zgarishi"],
        visual: "scratch",
        visualPreset: "loops",
        slides: [
          { emoji: "👕", title: "Kostyum (Costume)", points: ["Har sprite'da bir nechta **kostyum** — turli holatdagi rasmlari bor.", "«**keyingi kostyum**» — rasmni almashtiradi.", "Tez almashsa — **yurish animatsiyasi** paydo bo'ladi!"], code: "10 marta takrorla\n  keyingi kostyum\n  0.2 soniya kut\n  10 qadam yur" },
          { emoji: "🗣️", title: "Suhbat animatsiyasi", points: ["1-sprite: «Salom! Isming nima? 2 soniya de».", "2-sprite: avval «2 soniya kut», keyin javob beradi.", "Navbatma-navbat — kamida 4 replika."] },
          { emoji: "🌄", title: "Sahna o'zgarishi", points: ["«**fonni … ga almashtir**» — boshqa joyga o'tish.", "Masalan: maktab → park → uy.", "Suhbat davomida fon almashsa — hikoya jonlanadi."] },
          { emoji: "✅", title: "Loyiha talablari", points: ["2 ta sprite, kamida 4 replika.", "Yurish animatsiyasi (kostyum almashishi).", "Kamida 1 marta fon almashishi.", "🏁 bayroq bosilganda boshlanadi."] },
        ],
        practice: [
          "Kostyumlar (costumes) bilan tanishuv: kostyumni almashtirish orqali harakat effekti.",
          "«keyingi kostyum» + «… soniya kut» bloklari bilan yurish animatsiyasi.",
          "Loyiha: 2 ta sprite suhbatlashadi — biri savol beradi, ikkinchisi javob beradi (kamida 4 replika).",
          "Fon almashishi bilan «sahna o'zgarishi» qo'shish.",
          "Darsning oxirida 2-3 bola ishini ekranda ko'rsatadi.",
        ],
        homework: "Animatsiyani davom ettirish: yana 1 ta sprite qo'shib, suhbatga qo'shish. Jami kamida **6 replika** bo'lsin.",
        rubric: ["2+ sprite suhbatlashadi, 4+ replika", "Yurish animatsiyasi (kostyum)", "Fon almashadi", "Bayroq bosilganda to'g'ri boshlanadi"],
        quiz: [
          { q: "Sprite'ning turli holatdagi rasmlari nima deyiladi?", options: ["Kostyumlar", "Fonlar", "Bloklar", "Tovushlar"], correct: 0 },
          { q: "Yurish animatsiyasi uchun qaysi bloklar kerak?", options: ["keyingi kostyum + kut", "tovushni chal", "fonni almashtir", "x: y: ga bor"], correct: 0 },
          { q: "2-sprite 1-spritedan keyin javob berishi uchun?", options: ["Avval «kut» bloki qo'yamiz", "Kattaroq qilamiz", "O'chiramiz", "Rangini o'zgartiramiz"], correct: 0 },
          { q: "Sahna o'zgarishi uchun qaysi blok?", options: ["fonni … ga almashtir", "keyingi kostyum", "10 qadam yur", "de"], correct: 0 },
          { q: "Kostyumlar juda tez almashsa nima bo'ladi?", options: ["Animatsiya juda tez ko'rinadi — kut bloki qo'shish kerak", "Kompyuter o'chadi", "Sprite yo'qoladi", "Hech narsa"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Tsikllar va voqealar",
    days: [
      {
        title: "Voqea bloklari",
        kind: "lesson",
        goals: ["Bayroq, tugma va sprite bosilganda ishlaydigan skriptlar", "Sprite'ni strelka tugmalari bilan boshqarish", "Xabar yuborish orqali sprite'larni bog'lash"],
        visual: "scratch",
        visualPreset: "motion",
        slides: [
          { emoji: "⚡", title: "Voqea (Event) nima?", points: ["**Voqea** — biror narsa sodir bo'lganda skript ishga tushadi.", "Sariq «shlyapa» bloklar — har doim skript **boshida** turadi.", "Bir sprite'da bir nechta voqea skripti bo'lishi mumkin."] },
          { emoji: "🏁", title: "Asosiy voqealar", points: ["«**🏁 bayroq bosilganda**» — o'yin boshlanishi.", "«**… tugmasi bosilganda**» — klaviatura.", "«**bu sprite bosilganda**» — sichqoncha bilan bosish.", "«**fon … ga almashganda**»."] },
          { emoji: "🎮", title: "Strelkalar bilan boshqarish", points: ["→ bosilganda: yo'nalish 90, 10 qadam yur.", "← bosilganda: yo'nalish −90, 10 qadam yur.", "↑ / ↓: «y ni 10 ga o'zgartir» / «y ni −10 ga o'zgartir»."], code: "o'ng strelka bosilganda\n  90 yo'nalishga qara\n  10 qadam yur" },
          { emoji: "📨", title: "Xabarlar", points: ["«**xabar1 yubor**» — boshqa sprite'larga signal.", "«**xabar1 kelganda**» — signalni qabul qilish.", "Misol: 1-sprite bosilganda → «sakra» xabari → 2-sprite sakraydi."] },
        ],
        practice: [
          "«Bayroq bosilganda», «… tugmasi bosilganda», «bu sprite bosilganda» bloklari bilan tajriba.",
          "Sprite'ni 4 ta strelka tugmasi bilan boshqarish (o'ng, chap, yuqori, past).",
          "Sprite bosilganda rang o'zgartirish yoki tovush chiqarish.",
          "«Xabar yubor / xabar kelganda» bloklari bilan 2 sprite'ni bir-biriga bog'lash.",
          "Mini mashq: birinchi sprite bosilganda ikkinchisi sakraydi.",
        ],
        homework: "**«Boshqariladigan qahramon»**: strelkalar bilan yuradigan, probel bosilganda sakraydigan yoki gapiradigan sprite yaratish.",
        quiz: [
          { q: "Voqea bloklari skriptning qayerida turadi?", options: ["Boshida", "O'rtasida", "Oxirida", "Istalgan joyda"], correct: 0 },
          { q: "O'yinni boshlash uchun odatda qaysi voqea ishlatiladi?", options: ["🏁 bayroq bosilganda", "sprite bosilganda", "xabar kelganda", "fon almashganda"], correct: 0 },
          { q: "Sprite chapga qarashi uchun yo'nalish?", options: ["90", "0", "−90", "180"], correct: 2 },
          { q: "Bir sprite boshqasiga signal berishi uchun?", options: ["xabar yubor", "kut", "de", "yur"], correct: 0 },
          { q: "Sprite yuqoriga yurishi uchun?", options: ["x ni 10 ga o'zgartir", "y ni 10 ga o'zgartir", "y ni −10 ga o'zgartir", "15 gradus buril"], correct: 1 },
          { q: "Sichqoncha bilan sprite'ni bosganda ishlaydigan blok?", options: ["bu sprite bosilganda", "bayroq bosilganda", "probel bosilganda", "xabar kelganda"], correct: 0 },
        ],
      },
      {
        title: "Takrorlash bloklari (repeat, forever)",
        kind: "lesson",
        goals: ["«… marta takrorla» bilan kodni qisqartirish", "«doim takrorla» bilan uzluksiz harakat", "«chekkaga tegsa, qayt» bloki"],
        visual: "scratch",
        visualPreset: "loops",
        slides: [
          { emoji: "🔁", title: "Tsikl (takrorlash) nima?", points: ["Bir xil ishni **ko'p marta** qilish uchun.", "Hayotda: \"10 marta o'tirib-tur\" — 10 marta yozmaymiz!", "Scratch'da: sariq-to'q sariq **C shaklidagi** bloklar."] },
          { emoji: "4️⃣", title: "«… marta takrorla»", points: ["Ichidagi bloklar **aniq son** marta bajariladi.", "Kvadrat: 8 blok o'rniga — 3 blok!"], code: "4 marta takrorla\n  100 qadam yur\n  ↻ 90 gradus buril" },
          { emoji: "♾️", title: "«doim takrorla»", points: ["To'xtatmaguncha **cheksiz** takrorlaydi.", "Aylanuvchi shamol tegirmoni, suzuvchi baliq, fon musiqasi.", "To'xtatish: qizil ⏹ tugma."] },
          { emoji: "🏓", title: "Chekkadan qaytish", points: ["«**chekkaga tegsa, qayt**» — sprite devorga urilib, orqaga qaytadi.", "«**aylanish uslubini chap-o'ng qil**» — sprite teskari bo'lib qolmaydi.", "Rang effektini tsiklda o'zgartirsak — **kamalak** effekti 🌈."] },
        ],
        practice: [
          "«… marta takrorla» bloki: kvadrat bo'ylab yurishni 4 blokdan 1 tsiklga qisqartirish (ko'rgazma 1-topshiriq).",
          "«Doim takrorla» bloki: to'xtamasdan aylanadigan sprite.",
          "«Chekkaga tegsa, qayt» bloki bilan sahnada u yoqdan-bu yoqqa uchadigan sprite (ko'rgazma 3-topshiriq).",
          "Rang effektini tsiklda o'zgartirish — «kamalak» effekti.",
          "Mini mashq: baliq akvariumda doim suzib yuradi, chetga tegsa qaytadi.",
        ],
        homework: "**«Akvarium»** loyihasi: 3 ta baliq har xil tezlikda doim suzib yuradi. Bittasi bosilganda tovush chiqaradi.",
        quiz: [
          { q: "Cheksiz takrorlaydigan blok?", options: ["10 marta takrorla", "doim takrorla", "kut", "agar"], correct: 1 },
          { q: "Kvadrat chizish uchun «takrorla» ga qaysi son yoziladi?", options: ["2", "3", "4", "8"], correct: 2 },
          { q: "Sprite devorga tegib orqaga qaytishi uchun?", options: ["chekkaga tegsa, qayt", "x: 0 y: 0 ga bor", "keyingi kostyum", "de"], correct: 0 },
          { q: "Natija: necha qadam yuriladi?", code: "5 marta takrorla\n  20 qadam yur", options: ["20", "25", "100", "5"], correct: 2 },
          { q: "Tsiklning afzalligi?", options: ["Kod qisqa va tushunarli bo'ladi", "Kompyuter sekinlashadi", "Rang o'zgaradi", "Sprite yo'qoladi"], correct: 0 },
          { q: "Sprite qaytganda teskari bo'lib qolmasligi uchun?", options: ["aylanish uslubini chap-o'ng qil", "o'lchamni 200 qil", "yashir", "kut 1"], correct: 0 },
        ],
      },
      {
        title: "Mini loyiha — «Raqsga tushuvchi qahramon»",
        kind: "project",
        goals: ["Musiqa, kostyum va tsikllarni birlashtirish", "Bir vaqtda ishlaydigan bir nechta skript", "Diskoteka effektlari yaratish"],
        visual: "scratch",
        visualPreset: "loops",
        slides: [
          { emoji: "💃", title: "Loyiha vazifasi", points: ["Kamida **2 ta qahramon** birga raqsga tushadi.", "Musiqa to'xtamasdan chaladi.", "Fon rangi o'zgarib turadi — **diskoteka**!"] },
          { emoji: "🎵", title: "Musiqa skripti", points: ["Musiqani **Sahna (Stage)** ga qo'ygan yaxshi.", "«doim takrorla» ichida «tovushni oxirigacha chal».", "Kutubxonadan **Loops** toifasidagi musiqalar mos keladi."], code: "🏁 bayroq bosilganda\ndoim takrorla\n  Dance Around tovushini oxirigacha chal" },
          { emoji: "🕺", title: "Raqs harakatlari", points: ["Kostyum almashishi + kutish.", "Chapga-o'ngga sakrash: «x ni 20 ga o'zgartir», keyin «−20».", "Aylanish: «↻ 15 gradus buril» 24 marta."] },
          { emoji: "🪩", title: "Diskoteka effekti", points: ["Sahnada: «doim takrorla: rang effektini 25 ga o'zgartir, 0.3 kut».", "Bir nechta skript **bir vaqtda** ishlaydi — hammasi bayroqdan boshlanadi."] },
        ],
        practice: [
          "Musiqa tanlash va «tovushni oxirigacha chal» blokini tsiklga qo'yish.",
          "Kostyum almashinuvi + kutish bloklari bilan raqs harakatlari.",
          "Fon rang effektlari bilan «diskoteka» muhiti yaratish.",
          "Kamida 2 ta qahramon birga raqsga tushadi.",
          "Namoyish: har bir bola loyihasini yonidagi sherigiga ko'rsatadi.",
        ],
        homework: "Raqsni yaxshilash: yana 1 ta qahramon, fonlar almashinuvi va o'ziga yoqqan musiqa qo'shish. Keyingi darsda 3 ta eng yaxshi raqs sinfda ko'rsatiladi.",
        rubric: ["2+ qahramon raqsga tushadi", "Musiqa tsiklda to'xtovsiz", "Kostyum + harakat bilan raqs", "Diskoteka (rang) effekti", "Hammasi bayroqdan boshlanadi"],
        quiz: [
          { q: "Musiqa to'xtamasligi uchun qaysi blok ichiga qo'yamiz?", options: ["doim takrorla", "agar", "kut", "de"], correct: 0 },
          { q: "Bir sprite'da ikkita «bayroq bosilganda» skripti bo'lsa?", options: ["Ikkalasi bir vaqtda ishlaydi", "Faqat birinchisi", "Xato chiqadi", "Hech biri"], correct: 0 },
          { q: "Diskoteka effekti uchun qaysi blok?", options: ["rang effektini … ga o'zgartir", "10 qadam yur", "yashir", "fonni almashtir"], correct: 0 },
          { q: "24 marta 15° burilsa, jami necha gradus?", options: ["90", "180", "360", "240"], correct: 2 },
          { q: "Musiqani qayerga qo'ygan qulay?", options: ["Sahna (Stage) ga", "Faqat mushukka", "Hech qayerga", "Brauzerga"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Shartlar va o'zgaruvchilar",
    days: [
      {
        title: "Shart bloklari (if/else), chegaraga tegish",
        kind: "lesson",
        goals: ["«agar … bo'lsa» va «agar … bo'lsa / aks holda» bloklari", "Sensor bloklari: tegdimi?, tugma bosildimi?", "Labirint o'yinining asosi"],
        visual: "scratch",
        visualPreset: "vars",
        slides: [
          { emoji: "🤔", title: "Shart nima?", points: ["**Agar** yomg'ir yog'sa → soyabon ol.", "**Agar** ... **aks holda** ... — ikki yo'l.", "Dastur o'zi **qaror qabul qiladi**!"] },
          { emoji: "🔷", title: "Sensor bloklari", points: ["Olti burchakli ko'k bloklar — **ha/yo'q** javob beradi.", "«**sichqoncha kursoriga tegdimi?**»", "«**… rangiga tegdimi?**»", "«**probel tugmasi bosildimi?**»"] },
          { emoji: "🔀", title: "if / else", points: ["Shart doim tekshirilishi uchun «**doim takrorla**» ichiga qo'yiladi!"], code: "doim takrorla\n  agar <sichqoncha kursoriga tegdimi?> bo'lsa\n    Meni tutding! de\n  aks holda\n    10 qadam yur\n    chekkaga tegsa, qayt" },
          { emoji: "🧩", title: "Labirint", points: ["Fonda labirint chizamiz: devorlar — **qora**, marra — **yashil**.", "Agar qora rangga tegsa → boshlang'ich joyga qayt.", "Agar yashil rangga tegsa → «G'alaba!» de."] },
        ],
        practice: [
          "«Agar … bo'lsa» bloki bilan tanishuv: sensor bloklari («… ga tegdimi?», «tugma bosildimi?»).",
          "Sprite sichqoncha kursoriga tegsa — «Meni tutding!» deydi.",
          "«Agar … bo'lsa / aks holda» bloki: sprite chegaraga tegsa orqaga qaytadi, aks holda yuraveradi.",
          "Labirint asosi: strelkalar bilan yuradigan sprite devor rangiga tegsa, boshiga qaytadi.",
          "Mini mashq: labirintda marraga yetsa «G'alaba!» deydi.",
        ],
        homework: "O'z labirintini chizish (fon sifatida) va qahramonni undan o'tkazish. Devorga tegsa — boshiga qaytsin, marraga yetsa — tabrik chiqsin.",
        quiz: [
          { q: "Sensor bloklari qanday javob beradi?", options: ["Ha yoki yo'q", "Son", "Rasm", "Tovush"], correct: 0 },
          { q: "Shart doim tekshirilib turishi uchun uni qayerga qo'yamiz?", options: ["doim takrorla ichiga", "Skriptdan tashqariga", "Faqat bir marta", "Fonga"], correct: 0 },
          { q: "«aks holda» qismi qachon bajariladi?", options: ["Shart to'g'ri bo'lsa", "Shart noto'g'ri bo'lsa", "Har doim", "Hech qachon"], correct: 1 },
          { q: "Labirintda devorga tegishni qanday aniqlaymiz?", options: ["«… rangiga tegdimi?»", "«kut 1»", "«keyingi kostyum»", "«de»"], correct: 0 },
          { q: "Natija nima?", code: "agar <probel bosildimi?> bo'lsa\n  Sakradim! de\naks holda\n  Kutyapman de\n(probel bosilmagan)", options: ["Sakradim!", "Kutyapman", "Hech narsa", "Ikkalasi"], correct: 1 },
          { q: "Qaysi biri sensor bloki?", options: ["sichqoncha kursoriga tegdimi?", "10 qadam yur", "keyingi kostyum", "tovushni chal"], correct: 0 },
        ],
      },
      {
        title: "O'zgaruvchilar (ball, hisoblagich, hayot soni)",
        kind: "lesson",
        goals: ["O'zgaruvchi yaratish va ko'rsatish", "Qiymatni o'rnatish va o'zgartirish", "O'zgaruvchi bilan shart: hayot = 0 bo'lsa o'yin tugaydi"],
        visual: "scratch",
        visualPreset: "vars",
        slides: [
          { emoji: "📦", title: "O'zgaruvchi nima?", points: ["**O'zgaruvchi** — ichida son yoki so'z saqlanadigan **quti**.", "Qutining **nomi** bor (Ball) va **qiymati** (5).", "O'yin davomida qiymat o'zgaradi — shuning uchun \"o'zgaruvchi\"."] },
          { emoji: "➕", title: "O'zgaruvchi yaratish", points: ["To'q sariq **Variables** bo'limi → «**Make a Variable**».", "Nom: **Ball**. Sahnada ko'rsatkich paydo bo'ladi.", "«**Ball ni 0 ga o'rnat**» — o'yin boshida nollash.", "«**Ball ni 1 ga o'zgartir**» — 1 qo'shish (−1 — ayirish)."] },
          { emoji: "❤️", title: "Hayot soni", points: ["«Hayot» — 3 dan boshlanadi.", "Xato qilganda: «Hayot ni −1 ga o'zgartir».", "«**agar Hayot = 0 bo'lsa — hammasini to'xtat**»."], code: "🏁 bayroq bosilganda\nBall ni 0 ga o'rnat\nHayot ni 3 ga o'rnat\ndoim takrorla\n  agar <Hayot = 0> bo'lsa\n    O'yin tugadi! de\n    hammasini to'xtat" },
          { emoji: "🍎", title: "Olma o'yini", points: ["Olma tepadan tushadi: «y ni −5 ga o'zgartir».", "Savatga tegsa → Ball +1, olma yana tepaga.", "Yerga tushsa (y < −170) → Hayot −1."] },
        ],
        practice: [
          "O'zgaruvchi yaratish: «Ball» — sprite bosilganda ball 1 ga oshadi.",
          "«… ni 0 ga o'rnat» bloki bilan o'yin boshida ballni nollash.",
          "Ikkinchi o'zgaruvchi: «Hayot» — 3 dan boshlanadi, xato qilganda 1 ga kamayadi.",
          "«Agar Hayot = 0 bo'lsa — hammasini to'xtat» sharti.",
          "Mini mashq: olma tepadan tushadi, savatga tushsa +1 ball, yerga tushsa −1 hayot.",
        ],
        homework: "Olma o'yinini uyda qayta yig'ish va bitta yangilik qo'shish: tezlikni oshirish, ikkinchi mevani qo'shish yoki taymer qo'yish.",
        quiz: [
          { q: "O'zgaruvchi nima?", options: ["Qiymat saqlanadigan quti", "Sprite", "Fon", "Tovush"], correct: 0 },
          { q: "O'yin boshida ballni nollash uchun?", options: ["Ball ni 0 ga o'rnat", "Ball ni 1 ga o'zgartir", "Ball ni yashir", "Ball ni o'chir"], correct: 0 },
          { q: "Natija nima?", code: "Ball ni 0 ga o'rnat\n3 marta takrorla\n  Ball ni 2 ga o'zgartir", options: ["2", "3", "5", "6"], correct: 3 },
          { q: "Hayot kamayishi uchun?", options: ["Hayot ni −1 ga o'zgartir", "Hayot ni 1 ga o'zgartir", "Hayot ni 3 ga o'rnat", "Hayot ni ko'rsat"], correct: 0 },
          { q: "Natija nima?", code: "Hayot ni 3 ga o'rnat\nHayot ni −1 ga o'zgartir\nHayot ni −1 ga o'zgartir", options: ["0", "1", "2", "3"], correct: 1 },
          { q: "O'zgaruvchi bloklari qaysi rangda?", options: ["To'q sariq", "Ko'k", "Yashil", "Binafsha"], correct: 0 },
        ],
      },
      {
        title: "Mini loyiha — «Ball to'plash o'yini»",
        kind: "project",
        goals: ["To'liq o'yin yig'ish: boshqaruv, ball, taymer", "Tasodifiy joylashuv bilan ishlash", "O'yin tugashi ekranini yaratish"],
        visual: "scratch",
        visualPreset: "vars",
        slides: [
          { emoji: "🎮", title: "O'yin g'oyasi", points: ["Qahramon strelkalar bilan yuradi.", "Buyum (yulduz, olma) **tasodifiy joyda** paydo bo'ladi.", "Tegsa: ball +1, tovush, buyum yangi joyga o'tadi.", "30 soniyada eng ko'p ball to'plang!"] },
          { emoji: "🎲", title: "Tasodif", points: ["«**istalgan joyga bor**» — buyum tasodifiy joyga sakraydi.", "«**1 dan 10 gacha tasodifiy son**» — har safar boshqa son."] },
          { emoji: "⏱️", title: "Taymer", points: ["O'zgaruvchi «Vaqt» = 30.", "Har soniyada: «1 soniya kut», «Vaqt ni −1 ga o'zgartir».", "Vaqt = 0 → «O'yin tugadi! Balingiz: …»."], code: "Vaqt ni 30 ga o'rnat\nVaqt = 0 bo'lguncha takrorla\n  1 soniya kut\n  Vaqt ni −1 ga o'zgartir\nO'yin tugadi! de\nhammasini to'xtat" },
          { emoji: "🔗", title: "Matnni birlashtirish", points: ["«**… va … ni birlashtir**» (join) bloki.", "«Balingiz: » + Ball → «Balingiz: 12»."] },
        ],
        practice: [
          "To'liq o'yin yig'ish: boshqariladigan qahramon + tasodifiy paydo bo'ladigan buyum («istalgan joyga bor» bloki).",
          "Buyumga tegilganda: ball +1, tovush, buyum yangi joyga o'tadi.",
          "30 soniyalik taymer qo'shish (o'zgaruvchi bilan).",
          "Vaqt tugaganda «O'yin tugadi! Balingiz: …» ekrani.",
          "Bolalar bir-birining o'yinini o'ynab, eng ko'p ball to'plashadi.",
        ],
        homework: "O'yinga «G'alaba» sharti qo'shish: 10 ball to'plansa, maxsus tabrik sahnasi chiqsin. Xohlaganlar qiyinlik darajasi qo'shishi mumkin.",
        rubric: ["Qahramon strelkalar bilan boshqariladi", "Buyum tasodifiy joyda paydo bo'ladi", "Ball to'g'ri hisoblanadi", "30 soniyalik taymer ishlaydi", "O'yin tugashi ekrani bor"],
        quiz: [
          { q: "Buyumni tasodifiy joyga ko'chiradigan blok?", options: ["istalgan joyga bor", "x: 0 y: 0 ga bor", "10 qadam yur", "chekkaga tegsa qayt"], correct: 0 },
          { q: "Taymer uchun nima kerak?", options: ["O'zgaruvchi va kutish bloki", "Faqat fon", "Faqat tovush", "Kostyum"], correct: 0 },
          { q: "«Balingiz: 12» matnini hosil qilish uchun?", options: ["birlashtir (join) bloki", "takrorla", "kut", "yashir"], correct: 0 },
          { q: "Natija nima?", code: "Vaqt ni 5 ga o'rnat\n2 marta takrorla\n  Vaqt ni −1 ga o'zgartir", options: ["2", "3", "5", "7"], correct: 1 },
          { q: "O'yin tugagach hamma skriptni to'xtatadigan blok?", options: ["hammasini to'xtat", "kut 1", "yashir", "de"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Erkin ijod haftasi (Scratch fest)",
    days: [
      {
        title: "G'oya tanlash va reja tuzish",
        kind: "project",
        goals: ["O'tilgan barcha bloklarni takrorlash", "O'z loyihasi g'oyasini tanlash", "Qog'ozda aniq reja tuzish"],
        slides: [
          { emoji: "🧠", title: "Nimalarni bilamiz?", points: ["🔵 **Harakat** — yurish, burilish, koordinatalar.", "🟡 **Voqealar** — bayroq, tugma, xabar.", "🟠 **Tsikllar** — takrorla, doim takrorla.", "🔀 **Shartlar** — agar / aks holda.", "📦 **O'zgaruvchilar** — ball, hayot, taymer."] },
          { emoji: "💡", title: "G'oyalar banki", points: ["🎮 **O'yin**: quvlashmachoq, labirint, olma terish, kosmik jang.", "🎬 **Animatsiya**: multfilm, raqs, tabiat.", "📖 **Interaktiv hikoya**: tanlov bilan davom etadigan ertak.", "❓ **Viktorina**: savol-javob, ball bilan."] },
          { emoji: "📝", title: "Reja savollari", points: ["Qahramonlar kim?", "Sahna qanday?", "Nima sodir bo'ladi? (boshlanish → o'rta → yakun)", "Qaysi bloklar kerak?", "Qanday qilib yutish/tugatish mumkin?"] },
          { emoji: "👥", title: "Ishlash tartibi", points: ["Yakka yoki **juftlikda** ishlash mumkin.", "Rejani o'qituvchiga ko'rsatib **tasdiqlatish**.", "Juda katta g'oya emas — 2 darsda tugaydigan bo'lsin!"] },
        ],
        practice: [
          "O'tilgan barcha bloklarni doskada birga eslash (harakat, voqea, tsikl, shart, o'zgaruvchi).",
          "G'oyalar banki: o'yin, animatsiya, interaktiv hikoya, viktorina — misollar ko'rsatish.",
          "Har bola (yoki juftlik) o'z loyihasini tanlaydi.",
          "Qog'ozda reja: qahramonlar kim? Sahna qanday? Nima sodir bo'ladi? Qaysi bloklar kerak?",
          "Rejani o'qituvchiga ko'rsatib tasdiqlatish, Scratch'da loyiha faylini ochish.",
        ],
        homework: "Loyiha uchun material tayyorlash: sprite va fonlarni tanlash/chizish, birinchi skriptlarni yozib boshlash.",
        rubric: ["Aniq g'oya tanlangan", "Qahramonlar va sahna yozilgan", "Boshlanish-o'rta-yakun rejasi", "Kerakli bloklar ro'yxati", "O'qituvchi tasdiqlagan"],
        quiz: [
          { q: "Loyihani boshlashdan oldin nima qilamiz?", options: ["Reja tuzamiz", "Darhol kod yozamiz", "Kompyuterni o'chiramiz", "Hech narsa"], correct: 0 },
          { q: "Ball va hayot uchun qaysi bloklar kerak?", options: ["O'zgaruvchilar", "Tovush", "Ko'rinish", "Qalam"], correct: 0 },
          { q: "Labirint o'yinida devorga tegishni tekshirish uchun?", options: ["Shart + sensor bloki", "Faqat tovush", "Faqat fon", "Kostyum"], correct: 0 },
          { q: "Qaysi g'oya 2 darsga mos?", options: ["Minecraft'ning to'liq nusxasi", "Olma terish o'yini", "100 darajali o'yin", "3D film"], correct: 1 },
          { q: "Hikoyaning tuzilishi?", options: ["Boshlanish → o'rta → yakun", "Faqat yakun", "Tasodifiy", "Faqat sarlavha"], correct: 0 },
        ],
      },
      {
        title: "Loyihani amalga oshirish",
        kind: "project",
        goals: ["Reja asosida mustaqil dasturlash", "Xatolarni topish va tuzatish (debugging)", "Juftlikda bir-biriga yordam berish"],
        slides: [
          { emoji: "🛠️", title: "Bugun — mustaqil ish", points: ["Butun dars — o'z loyihangiz ustida ishlaysiz.", "O'qituvchi — faqat **yordamchi**.", "Har 20 daqiqada qisqa **checkpoint**."] },
          { emoji: "🐞", title: "Xato (bug) topish", points: ["Dastur kutganingizdek ishlamasa — bu **bug**.", "Skriptni **bittadan blok** bosib tekshiring.", "O'zgaruvchi qiymatini sahnada ko'rsatib kuzating.", "\"Sprite qayerda? Qaysi tomonga qarab turibdi?\" deb so'rang."] },
          { emoji: "🤝", title: "\"Sen menga, men senga\" qoidasi", points: ["Qiynalsangiz — avval sherigingizdan so'rang.", "Sherigingizga yordam berganda **o'zi bossin**, siz tushuntiring.", "3 marta urinib bo'lmasa — o'qituvchini chaqiring."] },
          { emoji: "✅", title: "Dars oxirigacha", points: ["Loyihaning **asosiy qismi ishlashi shart**.", "Saqlashni unutmang: **File → Save now**."] },
        ],
        practice: [
          "Butun dars — mustaqil ish, o'qituvchi faqat yordamchi.",
          "Har 20 daqiqada qisqa «checkpoint»: nima ishlayapti, nima ishlamayapti?",
          "Qiynalganlarga juftlik yordami («sen menga, men senga» qoidasi).",
          "Dars oxirida loyihaning asosiy qismi ishlashi shart.",
        ],
        homework: "Loyihani yakunlash: xatolarni tuzatish, tovush va effektlar qo'shish. Ertaga taqdimot — loyiha haqida 2-3 gap tayyorlab kelish.",
        rubric: ["Reja bo'yicha asosiy qism ishlaydi", "Checkpoint'larda holatini ayta oladi", "Xatolarni o'zi topib tuzatishga harakat qiladi", "Loyiha saqlangan"],
        quiz: [
          { q: "Dasturdagi xato nima deyiladi?", options: ["Bug", "Sprite", "Fon", "Loop"], correct: 0 },
          { q: "Xatoni topishning yaxshi usuli?", options: ["Skriptni qismlarga bo'lib tekshirish", "Hammasini o'chirish", "Kompyuterni urish", "E'tibor bermaslik"], correct: 0 },
          { q: "\"Sen menga, men senga\" qoidasida birinchi kimdan so'raymiz?", options: ["Sherigimizdan", "Direktordan", "Hech kimdan", "Internetdan"], correct: 0 },
          { q: "Scratch loyihasini saqlash?", options: ["File → Save now", "Ctrl + P", "Brauzerni yopish", "F5"], correct: 0 },
          { q: "Sherigingizga qanday yordam berasiz?", options: ["O'zingiz hammasini qilib berasiz", "Tushuntirasiz, u o'zi bosadi", "Kulasiz", "Loyihasini o'chirasiz"], correct: 1 },
        ],
      },
      {
        title: "«Scratch fest» — loyihalar namoyishi",
        kind: "event",
        goals: ["O'z loyihasini sinfga taqdim etish", "Boshqalarning ishini baholash va maqtash", "Loyihani Scratch saytida ulashish"],
        slides: [
          { emoji: "🎪", title: "Scratch fest!", points: ["Har bola/juftlik **3–4 daqiqa** loyihasini ko'rsatadi.", "Sinf savol beradi va o'yinni o'ynab ko'radi."] },
          { emoji: "🎤", title: "Taqdimot rejasi", points: ["1. Loyiha nomi va g'oyasi.", "2. Namoyish (o'ynab ko'rsatish).", "3. Qaysi bloklarni ishlatdim?", "4. Nima qiyin bo'ldi va qanday hal qildim?"] },
          { emoji: "🏅", title: "Nominatsiyalar", points: ["🎮 **Eng qiziqarli o'yin**", "🎨 **Eng chiroyli animatsiya**", "💡 **Eng original g'oya**", "Ovoz berish — o'zingizga ovoz berish mumkin emas 🙂"] },
          { emoji: "🌍", title: "Ulashish", points: ["Scratch'da **Share** tugmasi — loyiha hammaga ko'rinadi.", "Havolani ota-onangizga yuboring.", "Shaxsiy ma'lumot (familiya, maktab raqami) yozmang."] },
        ],
        practice: [
          "Har bola/juftlik loyihasini ekranda ko'rsatadi (3-4 daqiqadan): nima qildi, qaysi bloklar ishlatdi, nima qiyin bo'ldi.",
          "Sinf savol beradi va boshqalarning o'yinini o'ynab ko'radi.",
          "Ovoz berish: «Eng qiziqarli o'yin», «Eng chiroyli animatsiya», «Eng original g'oya» nominatsiyalari.",
          "O'qituvchi har bir loyihaning kuchli tomonini aytib o'tadi.",
        ],
        homework: "Yo'q — bayram! 🎉 Xohlaganlar loyihasini Scratch saytida «Share» qilib, havolasini ota-onasiga ko'rsatishi mumkin.",
        rubric: ["Loyiha ishlaydi", "Taqdimot 4 qismdan iborat", "Ishlatilgan bloklarni tushuntira oladi", "Boshqalarni hurmat bilan tinglaydi"],
        quiz: [
          { q: "Scratch'da loyihani hammaga ko'rsatish tugmasi?", options: ["Share", "Delete", "Stop", "Undo"], correct: 0 },
          { q: "Loyihani ulashganda nimani yozmaslik kerak?", options: ["Loyiha nomini", "Shaxsiy ma'lumotlarni", "O'yin qoidalarini", "Rahmat so'zini"], correct: 1 },
          { q: "Taqdimotda nimani aytish kerak?", options: ["G'oya, namoyish, bloklar, qiyinchiliklar", "Faqat ism", "Hech narsa", "Faqat baho"], correct: 0 },
          { q: "Boshqalarning loyihasiga qanday munosabatda bo'lamiz?", options: ["Hurmat va maqtov bilan", "Kulib", "E'tiborsiz", "Tanqid bilan faqat"], correct: 0 },
          { q: "3-oyda qaysi dasturlash muhitini o'rgandik?", options: ["Scratch", "Photoshop", "Excel", "CapCut"], correct: 0 },
        ],
      },
    ],
  },
];
