import type { WeekDraft } from "./types";

// 1-OY: KOMPYUTER SAVODXONLIGI
export const month1: WeekDraft[] = [
  {
    title: "Kompyuter bilan tanishuv",
    days: [
      {
        title: "Kompyuter qismlari",
        kind: "lesson",
        goals: ["Kompyuterning asosiy qismlarini tanish", "Kiritish va chiqarish qurilmalarini ajratish", "Ichki qismlar vazifasini tushunish"],
        visual: "computer-parts",
        slides: [
          { emoji: "🖥️", title: "Kompyuter nima?", points: ["Kompyuter — ma'lumotni **qabul qiladigan**, **qayta ishlaydigan** va **natija beradigan** aqlli mashina.", "U hisoblaydi, rasm chizadi, video ko'rsatadi, o'yin o'ynaydi.", "Kompyuter turlari: stol kompyuteri, noutbuk, planshet, smartfon."], tip: "Smartfon ham kichkina kompyuter!" },
          { emoji: "⌨️", title: "Kiritish qurilmalari", points: ["Kompyuterga ma'lumot **kiritadi**.", "**Klaviatura** — harf va raqamlar.", "**Sichqoncha** — kursorni boshqarish.", "Mikrofon, kamera, skaner ham kiritish qurilmalari."] },
          { emoji: "📺", title: "Chiqarish qurilmalari", points: ["Kompyuter natijasini bizga **ko'rsatadi yoki eshittiradi**.", "**Monitor** — rasm va matn.", "**Karnay / quloqchin** — ovoz.", "**Printer** — qog'ozga chop etish."] },
          { emoji: "🧠", title: "Tizim bloki ichida", points: ["**Protsessor (CPU)** — kompyuter miyasi, hamma hisobni bajaradi.", "**RAM** — vaqtinchalik xotira, o'chsa tozalanadi.", "**HDD/SSD** — doimiy xotira, fayllar saqlanadi.", "**Videokarta** — rasm va o'yinlarni chizadi.", "**Ona plata** — hammasini bog'laydi."] },
          { emoji: "📏", title: "Xotira o'lchovlari", points: ["1 bayt — bitta harf.", "1 KB ≈ 1000 bayt, 1 MB ≈ 1000 KB.", "1 GB ≈ 1000 MB — taxminan 250 ta qo'shiq.", "1 TB ≈ 1000 GB — juda katta shkaf!"], tip: "Telefoningiz xotirasi necha GB ekanini uyda tekshirib ko'ring." },
        ],
        practice: [
          "Ko'rgazmada har bir qismni bosib, vazifasini ovoz chiqarib o'qing.",
          "\"Top-chi!\" o'yinini o'ynab, kamida 5 ball to'plang.",
          "Daftarga jadval chizing: **Kiritish** / **Chiqarish** / **Ichki qism** va har biriga 3 tadan misol yozing.",
          "Sinfdagi kompyuterda monitor, klaviatura, sichqoncha va tizim blokini qo'l bilan ko'rsating.",
          "Juftlikda: biri qism nomini aytadi, ikkinchisi vazifasini tushuntiradi.",
        ],
        homework: "Uydagi (yoki telefon) qurilmangizning qismlarini rasmga chizib, har biriga nom yozing. Kiritish va chiqarish qurilmalarini turli rangda belgilang.",
        quiz: [
          { q: "Kompyuterning \"miyasi\" qaysi qism?", options: ["Monitor", "Protsessor (CPU)", "Sichqoncha", "Karnay"], correct: 1, explain: "Protsessor barcha hisob-kitoblarni bajaradi." },
          { q: "Qaysi biri kiritish qurilmasi?", options: ["Printer", "Monitor", "Klaviatura", "Karnay"], correct: 2, explain: "Klaviatura orqali kompyuterga ma'lumot kiritamiz." },
          { q: "Kompyuter o'chganda qaysi xotira tozalanadi?", options: ["SSD", "HDD", "RAM", "Fleshka"], correct: 2, explain: "RAM — vaqtinchalik xotira." },
          { q: "Fayllar doimiy saqlanadigan joy qaysi?", options: ["HDD / SSD", "Monitor", "Videokarta", "Sichqoncha"], correct: 0 },
          { q: "Printer qanday qurilma?", options: ["Kiritish", "Chiqarish", "Xotira", "Protsessor"], correct: 1, explain: "Printer natijani qog'ozga chiqaradi." },
          { q: "O'yin va videolarni ekranga chizib beradigan qism?", options: ["Quvvat bloki", "RAM", "Videokarta", "Klaviatura"], correct: 2 },
          { q: "1 GB taxminan nechta MB?", options: ["10", "100", "1000", "1 000 000"], correct: 2 },
        ],
      },
      {
        title: "Windows bilan ishlash",
        kind: "lesson",
        goals: ["Kompyuterni to'g'ri yoqish va o'chirish", "Ish stoli, Start menyu va Taskbar bilan ishlash", "Oynalarni ochish, yopish, kichraytirish"],
        visual: "file-explorer",
        slides: [
          { emoji: "🔌", title: "Yoqish va o'chirish", points: ["Yoqish: tizim blokidagi **quvvat tugmasi** ⏻ ni bir marta bosing.", "O'chirish: **Start → ⏻ → Завершение работы / Shut down**.", "Hech qachon kompyuterni rozetkadan sug'urib o'chirmang — fayllar buzilishi mumkin!"], tip: "Qayta yuklash (Restart) — kompyuter qotib qolganda yordam beradi." },
          { emoji: "🪟", title: "Ish stoli (Desktop)", points: ["Kompyuter yoqilganda ko'rinadigan asosiy ekran.", "**Yorliqlar (ikonkalar)** — dasturlarni tez ochish uchun.", "**Savatcha (Korzina)** — o'chirilgan fayllar shu yerga tushadi.", "Fon rasmini o'zgartirish: o'ng tugma → **Personalizatsiya**."] },
          { emoji: "🏁", title: "Start menyu va Taskbar", points: ["**Start** tugmasi — barcha dasturlar ro'yxati.", "**Taskbar** — pastdagi panel: ochiq dasturlar, soat, til, ovoz.", "Qidiruv: Start ni bosib, dastur nomini yozing (masalan, Paint)."], code: "⊞ Win — Start menyu\nWin + D — ish stoliga qaytish\nAlt + Tab — oynalar orasida o'tish" },
          { emoji: "🗔", title: "Oynalar bilan ishlash", points: ["Har bir dastur **oynada** ochiladi.", "Yuqori o'ng burchak: **—** kichraytirish, **☐** kattalashtirish, **✕** yopish.", "Oynani sarlavhasidan ushlab surish mumkin."] },
          { emoji: "📁", title: "Papkalar", points: ["**Papka** — fayllar uchun quti.", "Yangi papka: ish stolida o'ng tugma → **Yaratish → Papka** (Ctrl+Shift+N).", "Papkani ochish — ikki marta bosish."] },
        ],
        practice: [
          "Kompyuterni to'g'ri yoqing va parolsiz kirish ekranini kuzating.",
          "Start menyudan **Paint** va **Kalkulyator** ni oching, Alt+Tab bilan ular orasida o'ting.",
          "Oynani kichraytiring, kattalashtiring, keyin yoping.",
          "Ish stolida o'z ismingiz bilan papka yarating.",
          "Ko'rgazmadagi fayl boshqaruvchisida birinchi 2 ta topshiriqni bajaring.",
          "Dars oxirida kompyuterni Start orqali to'g'ri o'chiring.",
        ],
        homework: "Uyda (yoki ota-onangiz kompyuterida) ish stoli fonini o'zingizga yoqqan rasmga almashtiring va Start menyudagi 5 ta dastur nomini daftarga yozing.",
        quiz: [
          { q: "Kompyuterni qanday to'g'ri o'chiramiz?", options: ["Rozetkadan sug'uramiz", "Start → ⏻ → Shut down", "Monitorni o'chiramiz", "Quvvat tugmasini 10 soniya bosamiz"], correct: 1 },
          { q: "Ekran pastidagi dasturlar va soat ko'rinadigan panel nima?", options: ["Taskbar", "Savatcha", "Papka", "Brauzer"], correct: 0 },
          { q: "Oynani yopish tugmasi qaysi?", options: ["—", "☐", "✕", "⏻"], correct: 2 },
          { q: "Alt + Tab nima qiladi?", options: ["Kompyuterni o'chiradi", "Oynalar orasida o'tkazadi", "Matnni nusxalaydi", "Papka yaratadi"], correct: 1 },
          { q: "O'chirilgan fayllar avval qayerga tushadi?", options: ["Start menyuga", "Savatchaga", "Taskbarga", "Internetga"], correct: 1 },
          { q: "Yangi papka yaratish uchun qaysi tugmalar?", options: ["Ctrl + Shift + N", "Ctrl + P", "Alt + F4", "Win + D"], correct: 0 },
        ],
      },
      {
        title: "Fayllar bilan ishlash",
        kind: "lesson",
        goals: ["Faylni nusxalash, ko'chirish, o'chirish va qayta nomlash", "Tezkor tugmalarni (Ctrl+C, Ctrl+V) ishlatish", "ZIP arxiv yaratish va ochish"],
        visual: "file-explorer",
        slides: [
          { emoji: "📄", title: "Fayl nima?", points: ["**Fayl** — kompyuterdagi bitta hujjat, rasm, qo'shiq yoki video.", "Har faylning **nomi** va **kengaytmasi** bor: `mushuk.jpg`, `insho.docx`, `qo'shiq.mp3`.", "Kengaytma fayl turini bildiradi."] },
          { emoji: "📋", title: "Nusxalash va ko'chirish", points: ["**Copy (Ctrl+C)** — nusxa olish, asl fayl joyida qoladi.", "**Cut (Ctrl+X)** — kesib olish, fayl ko'chadi.", "**Paste (Ctrl+V)** — qo'yish.", "Sichqoncha bilan sudrab ham ko'chirish mumkin."], code: "Ctrl + C — nusxa\nCtrl + X — kesish\nCtrl + V — qo'yish\nCtrl + Z — bekor qilish" },
          { emoji: "✏️", title: "Qayta nomlash va o'chirish", points: ["Qayta nomlash: faylni tanlab **F2** yoki o'ng tugma → **Rename**.", "O'chirish: **Delete** — savatchaga tushadi.", "Savatchadan **Tiklash (Restore)** mumkin.", "**Shift + Delete** — butunlay o'chiradi (ehtiyot bo'ling!)."] },
          { emoji: "🗜️", title: "ZIP arxiv", points: ["**Arxiv** — ko'p fayllarni bitta \"sumka\"ga joylash.", "Hajmi kichrayadi, yuborish oson.", "Yaratish: o'ng tugma → **Send to → Compressed (zip) folder**.", "Ochish: o'ng tugma → **Extract All**."], tip: "Emailga 10 ta rasm yuborish o'rniga bitta ZIP yuboring!" },
        ],
        practice: [
          "Ko'rgazmadagi 5 ta topshiriqni to'liq bajaring (hammasi ✅ bo'lsin).",
          "Haqiqiy kompyuterda: ismingizdagi papka ichida **Rasmlar** va **Hujjatlar** papkalarini yarating.",
          "Internetdan yoki kompyuterdagi 3 ta rasmni **Rasmlar** papkasiga nusxalang.",
          "Bitta rasmni qayta nomlang: `mening_mushugim.jpg`.",
          "**Rasmlar** papkasini ZIP ga aylantiring, keyin ZIP ni boshqa joyga ochib (Extract) ko'ring.",
        ],
        homework: "Tezkor tugmalar kartochkasini tayyorlang: Ctrl+C, Ctrl+X, Ctrl+V, Ctrl+Z, F2, Delete — har birining vazifasini yozing va keyingi darsga olib keling.",
        quiz: [
          { q: "Faylni nusxalash tugmalari?", options: ["Ctrl + V", "Ctrl + C", "Ctrl + X", "Ctrl + Z"], correct: 1 },
          { q: "Ctrl + X dan keyin Ctrl + V bosilsa nima bo'ladi?", options: ["Fayl nusxalanadi", "Fayl ko'chadi", "Fayl o'chadi", "Hech narsa"], correct: 1 },
          { q: "Faylni qayta nomlash uchun qaysi tugma?", options: ["F2", "F5", "Esc", "Tab"], correct: 0 },
          { q: "`rasm.jpg` faylidagi `.jpg` nima?", options: ["Papka nomi", "Kengaytma (fayl turi)", "Parol", "Dastur"], correct: 1 },
          { q: "Ko'p faylni bitta siqilgan faylga joylash nima deyiladi?", options: ["Arxivlash (ZIP)", "Formatlash", "Chop etish", "Qayta yuklash"], correct: 0 },
          { q: "Xato o'chirilgan faylni qayerdan tiklaymiz?", options: ["Start menyu", "Savatcha", "Taskbar", "Kalkulyator"], correct: 1 },
          { q: "Oxirgi amalni bekor qilish tugmasi?", options: ["Ctrl + Z", "Ctrl + A", "Ctrl + S", "Ctrl + P"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Paint va Word",
    days: [
      {
        title: "Paint — chizish (tabiat, uy)",
        kind: "lesson",
        goals: ["Paint asboblarini tanish", "Shakllar va ranglar bilan rasm chizish", "Rasmni saqlash"],
        visual: "paint",
        slides: [
          { emoji: "🎨", title: "Paint dasturi", points: ["Windows'dagi oddiy chizish dasturi.", "Ochish: **Start → Paint** deb yozing.", "Yuqorida — asboblar paneli, o'rtada — oq qog'oz (kanvas)."] },
          { emoji: "✏️", title: "Asosiy asboblar", points: ["**Qalam** — erkin chizish.", "**Cho'tka** — qalin va turli uslubda.", "**O'chirg'ich** — xatoni o'chirish.", "**Chelak (Fill)** — yopiq joyni bo'yash.", "**Pipetka** — rasmdagi rangni olish."] },
          { emoji: "🔷", title: "Shakllar", points: ["To'rtburchak, aylana, uchburchak, yulduz, yurak...", "**Shift** bosib chizsangiz — tekis kvadrat va doira chiqadi.", "Uy = to'rtburchak + uchburchak (tom) + kichik kvadratlar (derazalar)."], tip: "Chelak bilan bo'yash uchun shakl chiziqlari to'liq yopiq bo'lishi kerak!" },
          { emoji: "💾", title: "Saqlash", points: ["**Ctrl + S** yoki Fayl → Saqlash.", "Nom bering: `mening_uyim.png`.", "PNG — sifatli rasm formati, JPG — kichikroq hajm."] },
        ],
        practice: [
          "Ko'rgazmadagi mini-Paintda aylana, to'rtburchak va chiziq bilan tajriba qiling.",
          "Paint dasturida **uy** chizing: devor, tom, eshik, 2 ta deraza.",
          "Uy atrofiga **tabiat** qo'shing: quyosh, daraxt, bulut, o'tlar.",
          "Chelak bilan hamma qismlarni bo'yang.",
          "Rasmni o'z papkangizga `tabiat_uy.png` nomi bilan saqlang.",
        ],
        homework: "Paint (yoki telefondagi chizish ilovasi)da \"Mening orzuimdagi uy\" rasmini chizing. Kamida 5 xil shakl va 6 xil rang ishlating.",
        rubric: ["Uy va tabiat elementlari bor", "Kamida 5 xil shakl ishlatilgan", "Ranglar chelak bilan to'g'ri bo'yalgan", "Fayl to'g'ri nom bilan saqlangan"],
        quiz: [
          { q: "Yopiq shaklni bir bosishda bo'yaydigan asbob?", options: ["Qalam", "Chelak (Fill)", "O'chirg'ich", "Lupa"], correct: 1 },
          { q: "Tekis doira chizish uchun qaysi tugmani bosib turamiz?", options: ["Ctrl", "Alt", "Shift", "Tab"], correct: 2 },
          { q: "Rasmdagi rangni \"olib\" beradigan asbob?", options: ["Pipetka", "Cho'tka", "Matn", "Tanlash"], correct: 0 },
          { q: "Rasmni saqlash tugmalari?", options: ["Ctrl + P", "Ctrl + S", "Ctrl + O", "Ctrl + N"], correct: 1 },
          { q: "Uy chizish uchun tom qaysi shakl bo'ladi?", options: ["Aylana", "Uchburchak", "Yulduz", "Chiziq"], correct: 1 },
          { q: "Chelak bilan bo'yaganda butun fon bo'yalib ketdi. Sabab?", options: ["Rang noto'g'ri", "Shakl chizig'i yopiq emas edi", "Kompyuter eski", "Fayl saqlanmagan"], correct: 1 },
        ],
      },
      {
        title: "Word — matn yozish, shriftlar, ranglar",
        kind: "lesson",
        goals: ["Word'da matn terish va tahrirlash", "Shrift, o'lcham, rang va uslubni o'zgartirish", "Matnni tekislash"],
        slides: [
          { emoji: "📝", title: "Microsoft Word", points: ["Matnli hujjatlar yaratish dasturi: insho, xat, taklifnoma.", "Oq sahifa — qog'oz varag'i.", "Yozish joyi — miltillovchi **kursor** |."] },
          { emoji: "⌨️", title: "Matn terish qoidalari", points: ["**Shift** + harf — bosh harf.", "**Enter** — yangi xatboshi.", "**Backspace** — chapdagi harfni o'chiradi, **Delete** — o'ngdagini.", "So'zlar orasida faqat **bitta probel**!"] },
          { emoji: "🔤", title: "Shrift va o'lcham", points: ["Matnni avval **belgilang** (sichqoncha bilan sudrab).", "Shrift turi: Times New Roman, Arial, Comic Sans...", "O'lchami: 14 — oddiy matn, 20–28 — sarlavha.", "**Ж** — qalin (Ctrl+B), **К** — qiya (Ctrl+I), **Ч** — tagiga chizilgan (Ctrl+U)."], code: "Ctrl + B — qalin\nCtrl + I — qiya\nCtrl + U — tagiga chizish\nCtrl + A — hammasini belgilash" },
          { emoji: "🌈", title: "Rang va tekislash", points: ["**A** tugmasi — harf rangi, marker — fon rangi.", "Tekislash: chapga, markazga (Ctrl+E), o'ngga, ikki tomonga.", "Sarlavhalarni markazga qo'yish chiroyli ko'rinadi."] },
        ],
        practice: [
          "Word'ni oching va \"Mening sevimli hayvonim\" mavzusida 5–6 gapdan iborat matn yozing.",
          "Sarlavhani belgilang: o'lcham 24, qalin, markazda, ko'k rang.",
          "Matnda 3 ta muhim so'zni **qalin**, 2 tasini qiya qiling.",
          "Hayvon nomini rangli marker bilan belgilang.",
          "Butun matn shriftini Arial 14 ga o'zgartiring (Ctrl+A).",
          "Hujjatni `sevimli_hayvon.docx` nomi bilan saqlang.",
        ],
        homework: "Word'da tug'ilgan kun taklifnomasi yozing: sarlavha, sana, manzil va taklif matni. Turli shrift, rang va o'lchamlardan foydalaning.",
        quiz: [
          { q: "Matnni qalin qilish tugmalari?", options: ["Ctrl + I", "Ctrl + B", "Ctrl + U", "Ctrl + E"], correct: 1 },
          { q: "Butun matnni belgilash uchun?", options: ["Ctrl + A", "Ctrl + S", "Ctrl + C", "Ctrl + Z"], correct: 0 },
          { q: "Yangi xatboshiga o'tish uchun qaysi tugma?", options: ["Space", "Enter", "Shift", "Tab"], correct: 1 },
          { q: "Shriftni o'zgartirishdan oldin nima qilish kerak?", options: ["Faylni saqlash", "Matnni belgilash", "Word'ni yopish", "Rasm qo'yish"], correct: 1 },
          { q: "Sarlavha uchun qaysi o'lcham mos?", options: ["8", "11", "24", "72 dan katta"], correct: 2 },
          { q: "Kursordan chapdagi harfni o'chiradigan tugma?", options: ["Delete", "Backspace", "Enter", "Esc"], correct: 1 },
        ],
      },
      {
        title: "Word — rasm joylash, jadval qo'shish",
        kind: "lesson",
        goals: ["Hujjatga rasm qo'yish va joylashuvini sozlash", "Jadval yaratish va to'ldirish", "Chiroyli hujjat tayyorlash"],
        slides: [
          { emoji: "🖼️", title: "Rasm qo'yish", points: ["**Вставка / Insert → Рисунки / Pictures**.", "Kompyuterdan yoki internetdan rasm tanlash.", "Burchaklaridagi doirachalar bilan o'lchamini o'zgartirish."] },
          { emoji: "↔️", title: "Rasmni matn bilan joylash", points: ["Rasmni bosing → **Обтекание текстом / Wrap Text**.", "**Квадрат (Square)** — matn rasm atrofida aylanadi.", "**Перед текстом** — rasmni erkin surish mumkin."], tip: "Rasmni burchagidan torting — shunda u cho'zilib ketmaydi." },
          { emoji: "▦", title: "Jadval", points: ["**Вставка → Таблица** — kataklarni tanlang (masalan 3×4).", "**Tab** — keyingi katakka o'tish.", "Jadval **qator** (gorizontal) va **ustun** (vertikal) dan iborat.", "Konstruktor bo'limidan rangli uslub tanlash mumkin."] },
          { emoji: "📅", title: "Jadval misoli: dars jadvali", points: ["1-ustun: Hafta kunlari.", "2–4-ustunlar: 1-, 2-, 3-darslar.", "Sarlavha qatorini qalin va rangli qiling."] },
        ],
        practice: [
          "Oldingi darsdagi \"Sevimli hayvonim\" hujjatini oching.",
          "Hayvon rasmini qo'shing, o'lchamini kichraytiring va **Квадрат** joylashuvini tanlang.",
          "Hujjat oxiriga 3 ustun × 4 qatorli jadval qo'shing: **Xususiyat | Qiymat | Izoh** (masalan: rangi, ovqati, yashash joyi).",
          "Jadvalga tayyor rangli uslub bering.",
          "Hujjatni saqlang va sinfdoshingizga ko'rsating.",
        ],
        homework: "Word'da haftalik dars jadvalingizni tuzing: 6 kun × 5 dars. Sarlavha qo'shing va jadval tepasiga maktabingiz rasmini qo'ying.",
        quiz: [
          { q: "Word'da rasm qo'shish qaysi bo'limda?", options: ["Главная / Home", "Вставка / Insert", "Вид / View", "Файл"], correct: 1 },
          { q: "Jadvalda keyingi katakka o'tish tugmasi?", options: ["Enter", "Tab", "Shift", "Ctrl"], correct: 1 },
          { q: "Jadvaldagi gorizontal chiziq nima deyiladi?", options: ["Ustun", "Qator", "Katak", "Chegara"], correct: 1 },
          { q: "Matn rasm atrofidan aylanib o'tishi uchun qaysi sozlama?", options: ["Обтекание текстом → Квадрат", "Shrift", "Tekislash", "Saqlash"], correct: 0 },
          { q: "Rasm cho'zilib ketmasligi uchun uni qayeridan tortamiz?", options: ["O'rtasidan", "Burchagidan", "Chap tomonidan", "Tepasidan"], correct: 1 },
          { q: "3×4 jadvalda nechta katak bor?", options: ["7", "12", "34", "10"], correct: 1 },
        ],
      },
    ],
  },
  {
    title: "PowerPoint",
    days: [
      {
        title: "Slayd yaratish, matn va rasm joylash",
        kind: "lesson",
        goals: ["PowerPoint oynasini tanish", "Yangi slayd qo'shish va maket tanlash", "Slaydga matn va rasm joylash"],
        slides: [
          { emoji: "📊", title: "Taqdimot nima?", points: ["**Taqdimot** — mavzuni slaydlar orqali ko'rsatish.", "**Slayd** — taqdimotning bitta sahifasi.", "Dastur: Microsoft PowerPoint (yoki Google Slides)."] },
          { emoji: "➕", title: "Yangi slayd", points: ["**Главная → Создать слайд** (Ctrl+M).", "**Maket** tanlang: Sarlavha, Sarlavha + matn, Ikki ustun...", "Chapda — slaydlar ro'yxati, o'rtada — tahrirlanayotgan slayd."] },
          { emoji: "🎨", title: "Dizayn", points: ["**Дизайн** bo'limida tayyor mavzular (temalar).", "Bitta mavzu — butun taqdimot bir xil uslubda.", "Fon rangini o'zgartirish: **Формат фона**."] },
          { emoji: "✍️", title: "Yaxshi slayd qoidalari", points: ["Bir slaydda **kam matn** — 3–5 punkt.", "Katta shrift: kamida 24.", "Har slaydda **bitta rasm** yaxshi ko'rinadi.", "Ranglar kontrastli bo'lsin: qora fonga oq matn."], tip: "Qoida 6×6: bir slaydda 6 qatordan, bir qatorda 6 so'zdan oshmasin." },
          { emoji: "▶️", title: "Ko'rsatish", points: ["**F5** — boshidan namoyish.", "**Shift + F5** — joriy slayddan.", "**Esc** — namoyishdan chiqish."] },
        ],
        practice: [
          "PowerPoint'ni oching va dizayn mavzusini tanlang.",
          "1-slayd: sarlavha \"Mening sevimli mashg'ulotim\" va ismingiz.",
          "2–3-slaydlar: mashg'ulot haqida 3 ta punkt va bittadan rasm.",
          "4-slayd: \"Rahmat!\" yakuniy slaydi.",
          "F5 bosib taqdimotni ko'rib chiqing va faylni saqlang.",
        ],
        homework: "\"Mening maktabim\" mavzusida 4 slaydli taqdimot tayyorlang: sarlavha, maktab haqida, sevimli fanim, rahmat slaydi.",
        quiz: [
          { q: "Yangi slayd qo'shish tugmalari?", options: ["Ctrl + M", "Ctrl + N", "Ctrl + S", "F5"], correct: 0 },
          { q: "Taqdimotni boshidan ko'rsatish tugmasi?", options: ["F1", "F2", "F5", "Esc"], correct: 2 },
          { q: "Slaydda nechta punkt bo'lgani yaxshi?", options: ["1", "3–5", "15–20", "Qancha ko'p bo'lsa shuncha yaxshi"], correct: 1 },
          { q: "Butun taqdimotni bir uslubga keltiradigan bo'lim?", options: ["Дизайн", "Вставка", "Рецензирование", "Файл"], correct: 0 },
          { q: "Namoyishdan chiqish tugmasi?", options: ["Enter", "Esc", "Space", "Tab"], correct: 1 },
          { q: "Qaysi rang juftligi slaydda yaxshi o'qiladi?", options: ["Sariq fonda oq matn", "Qora fonda oq matn", "Ko'k fonda ko'k matn", "Qizil fonda pushti matn"], correct: 1 },
        ],
      },
      {
        title: "Animatsiya va o'tishlar",
        kind: "lesson",
        goals: ["Slaydlar orasiga o'tish (transition) qo'shish", "Obyektlarga animatsiya berish", "Animatsiya tartibi va vaqtini sozlash"],
        slides: [
          { emoji: "🔄", title: "O'tishlar (Переходы)", points: ["Bir slayddan keyingisiga **qanday o'tish** effekti.", "Masalan: Выцветание (so'nish), Сдвиг (surilish), Куб.", "**Применить ко всем** — hamma slaydga bir xil o'tish."] },
          { emoji: "✨", title: "Animatsiya", points: ["Slayd ichidagi **matn yoki rasm** harakati.", "4 xil tur: **Вход** (paydo bo'lish), **Выделение** (ajratish), **Выход** (yo'qolish), **Пути перемещения** (yo'l bo'ylab harakat).", "Obyektni tanlang → **Анимация** bo'limi."] },
          { emoji: "⏱️", title: "Vaqt va tartib", points: ["**Область анимации** — barcha animatsiyalar ro'yxati.", "Boshlanishi: bosganda, oldingisi bilan, oldingisidan keyin.", "Davomiylik: 0.5–1 soniya yetarli."], tip: "Juda ko'p animatsiya tomoshabinni charchatadi — o'lchov bilan ishlating!" },
          { emoji: "🎯", title: "Yaxshi animatsiya qoidalari", points: ["Har punkt navbat bilan paydo bo'lsin.", "Bir taqdimotda 1–2 xil effekt yetarli.", "Ovoz effektlaridan kam foydalaning."] },
        ],
        practice: [
          "Uy vazifasidagi \"Mening maktabim\" taqdimotini oching.",
          "Hamma slaydlarga bir xil o'tish qo'llang (Применить ко всем).",
          "Sarlavhaga **Вход → Вылет** animatsiyasini bering.",
          "Punktlarni navbat bilan (bosganda) paydo bo'ladigan qiling.",
          "Rasmga **Пути перемещения** bilan harakat yo'lini chizing.",
          "F5 bilan tekshiring va sherigingizga ko'rsating.",
        ],
        homework: "Taqdimotingizga yana 2 slayd qo'shing va har bir slaydga turli animatsiya bering. Animatsiyalar tartibini Область анимации orqali tekshiring.",
        quiz: [
          { q: "Slaydlar orasidagi effekt nima deyiladi?", options: ["Animatsiya", "O'tish (Переход)", "Dizayn", "Maket"], correct: 1 },
          { q: "Obyekt slaydda paydo bo'lishi qaysi animatsiya turi?", options: ["Вход", "Выход", "Выделение", "Переход"], correct: 0 },
          { q: "Barcha animatsiyalar ro'yxati qayerda ko'rinadi?", options: ["Область анимации", "Taskbar", "Дизайн", "Savatcha"], correct: 0 },
          { q: "Hamma slaydlarga bir xil o'tish qo'yish tugmasi?", options: ["Применить ко всем", "Сохранить", "Создать слайд", "Удалить"], correct: 0 },
          { q: "Qaysi biri yaxshi amaliyot?", options: ["Har so'zga alohida animatsiya", "1–2 xil effekt ishlatish", "Har slaydda ovoz effekti", "10 soniyalik animatsiyalar"], correct: 1 },
          { q: "Rasm ekranda chizilgan yo'l bo'ylab harakatlanishi uchun?", options: ["Пути перемещения", "Выцветание", "Формат фона", "Макет"], correct: 0 },
        ],
      },
      {
        title: "Mini loyiha — \"Mening oilam\" taqdimoti",
        kind: "project",
        goals: ["O'rganilgan bilimlarni loyihada qo'llash", "Mustaqil taqdimot tayyorlash", "Sinf oldida ishni namoyish qilish"],
        slides: [
          { emoji: "👨‍👩‍👧‍👦", title: "Loyiha vazifasi", points: ["\"Mening oilam\" mavzusida **6–8 slaydli** taqdimot.", "Har bir oila a'zosi haqida alohida slayd.", "Oxirida — oilaviy an'analar yoki sevimli mashg'ulot."] },
          { emoji: "🗂️", title: "Slaydlar rejasi", points: ["1. Sarlavha: \"Mening oilam\" + ism.", "2. Oilam haqida qisqacha.", "3–6. Oila a'zolari: ismi, kasbi, sevimli ishi.", "7. Oilaviy an'ana / sayohat.", "8. Rahmat!"] },
          { emoji: "✅", title: "Talablar", points: ["Bitta dizayn mavzusi.", "Har slaydda rasm (yoki emoji/chizma).", "O'tishlar va kamida 3 ta animatsiya.", "Matn qisqa va xatosiz."], tip: "Oila a'zolari rasmini ishlatishdan oldin ulardan ruxsat so'rang!" },
          { emoji: "🎤", title: "Taqdimot qilish", points: ["2 daqiqa gapiring.", "Slayddagi matnni o'qimang — o'z so'zlaringiz bilan ayting.", "Tomoshabinlarga qarang va tabassum qiling 🙂"] },
        ],
        practice: [
          "Qog'ozda 8 slaydlik reja tuzing (10 daqiqa).",
          "PowerPoint'da dizayn tanlab, slaydlarni yarating.",
          "Matn, rasm, o'tish va animatsiyalarni qo'shing.",
          "Sherigingiz bilan taqdimotlarni almashib, 1 ta maslahat bering.",
          "Sinf oldida 2 daqiqalik taqdimot qiling.",
        ],
        homework: "Taqdimotni oilangizga ko'rsating va ularning fikrini yozib keling. Kerak bo'lsa, xatolarni tuzating.",
        rubric: ["6–8 slayd, reja bo'yicha", "Bir xil dizayn va o'qiladigan shrift", "Har slaydda rasm", "O'tishlar va kamida 3 animatsiya", "Taqdimotda ravon gapirish"],
        quiz: [
          { q: "Taqdimotni boshlashdan oldin nima qilish kerak?", options: ["Darhol animatsiya qo'shish", "Reja tuzish", "Faylni o'chirish", "Kompyuterni qayta yuklash"], correct: 1 },
          { q: "Taqdimot vaqtida qanday gapirgan yaxshi?", options: ["Slayddan so'zma-so'z o'qish", "O'z so'zlarim bilan, tomoshabinga qarab", "Juda tez", "Orqa o'girib"], correct: 1 },
          { q: "Oila a'zosining rasmini qo'yishdan oldin?", options: ["Ruxsat so'rash kerak", "Hech narsa kerak emas", "Internetga joylash kerak", "Rasmni o'chirish kerak"], correct: 0 },
          { q: "Qaysi biri taqdimot talablariga kirmaydi?", options: ["Bir xil dizayn", "Har slaydda rasm", "Har slaydda 20 qator matn", "O'tishlar"], correct: 2 },
          { q: "Sherigingiz taqdimotiga qanday fikr bildiramiz?", options: ["Faqat kamchiliklarni aytamiz", "Yaxshi tomoni + 1 ta maslahat", "Hech narsa demaymiz", "Kulamiz"], correct: 1 },
        ],
      },
    ],
  },
  {
    title: "Excel",
    days: [
      {
        title: "Excel — jadval yaratish, oddiy hisoblash",
        kind: "lesson",
        goals: ["Katak, qator, ustun va formula satrini tanish", "Ma'lumot kiritish va jadvalni formatlash", "Oddiy formulalar: + − * /"],
        visual: "excel",
        visualPreset: "basic",
        slides: [
          { emoji: "📊", title: "Excel nima uchun kerak?", points: ["Jadval, ro'yxat va **hisob-kitob** dasturi.", "Misollar: o'yinchoqlar ro'yxati, cho'ntak puli, sinf ballari.", "Excel siz uchun **avtomatik hisoblaydi** — bu sehr! ✨"] },
          { emoji: "🔲", title: "Katak, qator, ustun", points: ["**Ustun** — harf bilan: A, B, C...", "**Qator** — raqam bilan: 1, 2, 3...", "**Katak (yacheyka)** — ustun + qator: **A1**, **B3**.", "**Formula satri** (fx) — katak ichidagi narsani ko'rsatadi."] },
          { emoji: "⌨️", title: "Ma'lumot kiritish", points: ["Katakni bosing va yozing.", "**Enter** — pastga, **Tab** — o'ngga o'tish.", "Matn chapga, sonlar o'ngga tekislanadi.", "Ustun kengligi: harflar orasidagi chiziqni ikki marta bosing."] },
          { emoji: "➕", title: "Formulalar", points: ["Formula har doim **=** bilan boshlanadi!", "Qo'shish `=A1+B1`, ayirish `=A1-B1`.", "Ko'paytirish `=A1*B1`, bo'lish `=A1/B1`.", "Kataklardagi son o'zgarsa — natija **o'zi yangilanadi**."], code: "=B2*C2   → narx × soni\n=D2+D3+D4 → jami" },
          { emoji: "🖌️", title: "Jadvalni bezash", points: ["Sarlavha qatorini **qalin** va rangli qiling.", "**Chegaralar (Границы)** — jadval chiziqlari.", "Katak rangi — chelak belgisi."] },
        ],
        practice: [
          "Ko'rgazmadagi \"Do'kon ro'yxati\" mashqlarining hammasini bajaring.",
          "Excel'da o'z jadvalingizni yarating: **O'yinchoq | Narxi | Soni | Jami** — 5 ta o'yinchoq.",
          "**Jami** ustunini formula bilan hisoblang: `=B2*C2`.",
          "Oxirgi qatorga umumiy summani formula bilan toping.",
          "Sarlavhani qalin, rangli qiling va barcha chegaralarni qo'ying.",
          "Bir narxni o'zgartirib, jami qanday yangilanishini kuzating.",
        ],
        homework: "\"Mening haftalik cho'ntak pulim\" jadvalini tuzing: kunlar, olgan pul, sarflagan pul, qolgan pul (`=B2-C2`). Jadvalni rangli qiling.",
        quiz: [
          { q: "B ustun va 3-qator kesishgan katak nomi?", options: ["3B", "B3", "BC", "33"], correct: 1 },
          { q: "Excel'da formula nima bilan boshlanadi?", options: ["+", "=", "#", "fx"], correct: 1 },
          { q: "A1 va B1 ni ko'paytiruvchi formula?", options: ["=A1xB1", "=A1*B1", "=A1+B1", "A1*B1"], correct: 1 },
          { q: "Natija nima bo'ladi?", code: "A1 = 12, B1 = 3\n=A1/B1", options: ["36", "15", "4", "9"], correct: 2 },
          { q: "Katakdan o'ngga o'tish tugmasi?", options: ["Enter", "Tab", "Esc", "Shift"], correct: 1 },
          { q: "Formula ishlatilgan katakdagi son o'zgarsa?", options: ["Natija o'zgarmaydi", "Natija avtomatik yangilanadi", "Xato chiqadi", "Fayl yopiladi"], correct: 1 },
          { q: "Natija nima bo'ladi?", code: "B2 = 5000 (narx), C2 = 3 (soni)\n=B2*C2", options: ["5003", "15000", "1667", "8000"], correct: 1 },
        ],
      },
      {
        title: "Excel — murakkab hisob-kitoblar (funksiyalar)",
        kind: "lesson",
        goals: ["SUM, AVERAGE, MAX, MIN, COUNT funksiyalarini ishlatish", "Diapazon (A1:A5) tushunchasi", "Formulani sudrab nusxalash (avtoto'ldirish)"],
        visual: "excel",
        visualPreset: "functions",
        slides: [
          { emoji: "🧮", title: "Funksiya nima?", points: ["**Funksiya** — tayyor formula. Ko'p kataklarni bir zumda hisoblaydi.", "Ko'rinishi: `=NOMI(diapazon)`.", "**Diapazon** — kataklar oralig'i: `B2:B6` = B2, B3, B4, B5, B6."] },
          { emoji: "➕", title: "SUM va AVERAGE", points: ["`=SUM(B2:B6)` — yig'indi (ruscha: **СУММ**).", "`=AVERAGE(B2:B6)` — o'rtacha (ruscha: **СРЗНАЧ**).", "Avtosumma tugmasi **Σ** — SUM ni tez qo'yadi."] },
          { emoji: "🏔️", title: "MAX, MIN, COUNT", points: ["`=MAX(B2:B6)` — eng katta (**МАКС**).", "`=MIN(B2:B6)` — eng kichik (**МИН**).", "`=COUNT(B2:B6)` — nechta son bor (**СЧЁТ**)."], code: "=SUM(B2:B6)\n=AVERAGE(B2:B6)\n=MAX(B2:B6)\n=MIN(B2:B6)\n=COUNT(B2:B6)" },
          { emoji: "🪄", title: "Avtoto'ldirish", points: ["Katakning o'ng pastki burchagidagi **kichik kvadrat**ni pastga torting.", "Formula har qatorga o'zi moslashadi: `=SUM(B2:C2)` → `=SUM(B3:C3)`.", "Raqamlar ketma-ketligi ham: 1, 2 → 3, 4, 5..."] },
          { emoji: "📈", title: "Diagramma", points: ["Jadvalni belgilang → **Вставка → Диаграмма**.", "**Ustunli diagramma** — solishtirish uchun eng tushunarli.", "Masalan: sinfdoshlarning sevimli mevalari statistikasi."] },
        ],
        practice: [
          "Ko'rgazmadagi \"Sinf ballari\" mashqlarini bajaring.",
          "Excel'da 5 ta do'stingizning 3 fandan baholari jadvalini tuzing.",
          "Har o'quvchi uchun **Jami** (SUM) va **O'rtacha** (AVERAGE) ni hisoblang — avtoto'ldirish bilan!",
          "Har fan uchun MAX va MIN ni toping.",
          "Jadvalni ism bo'yicha alifbo tartibida saralang (Сортировка).",
          "O'rtacha ballar asosida ustunli diagramma yarating.",
        ],
        homework: "Oilangizdagi 5 kishining bo'yi (sm) jadvalini tuzing. Eng baland, eng past, o'rtacha bo'yni funksiyalar bilan toping va diagramma chizing.",
        quiz: [
          { q: "B2 dan B6 gacha bo'lgan sonlar yig'indisi?", options: ["=SUM(B2:B6)", "=SUM(B2+B6)", "=B2:B6", "SUM B2-B6"], correct: 0 },
          { q: "O'rtacha qiymat funksiyasi?", options: ["MAX", "AVERAGE", "COUNT", "MIN"], correct: 1 },
          { q: "`B2:B6` diapazonida nechta katak bor?", options: ["2", "4", "5", "6"], correct: 2 },
          { q: "Natija nima?", code: "A1=4, A2=9, A3=2\n=MAX(A1:A3)", options: ["2", "4", "9", "15"], correct: 2 },
          { q: "Natija nima?", code: "A1=4, A2=6, A3=8\n=AVERAGE(A1:A3)", options: ["6", "18", "8", "3"], correct: 0 },
          { q: "СЧЁТ funksiyasining inglizcha nomi?", options: ["SUM", "COUNT", "ROUND", "IF"], correct: 1 },
          { q: "Formulani pastki qatorlarga tez nusxalash usuli?", options: ["Qayta yozish", "Avtoto'ldirish (kichik kvadratni tortish)", "Ctrl + P", "Faylni qayta ochish"], correct: 1 },
        ],
      },
      {
        title: "Excel — shartga ko'ra hisoblash",
        kind: "lesson",
        goals: ["IF (ЕСЛИ) bilan shartli natija chiqarish", "COUNTIF va SUMIF bilan shart bo'yicha sanash/qo'shish", "Shartli formatlash bilan ranglash"],
        visual: "excel",
        visualPreset: "if",
        slides: [
          { emoji: "🤔", title: "Shart nima?", points: ["Hayotda: **agar** yomg'ir yog'sa — soyabon olaman, **aks holda** — kepka.", "Excel'da ham xuddi shunday: `=IF(shart; ha bo'lsa; yo'q bo'lsa)`.", "Ruscha: **ЕСЛИ**."], code: "=IF(C2>=90; \"A'lo\"; \"Yaxshi\")" },
          { emoji: "⚖️", title: "Taqqoslash belgilari", points: ["`>` katta, `<` kichik.", "`>=` katta yoki teng, `<=` kichik yoki teng.", "`=` teng, `<>` teng emas.", "Matn qo'shtirnoq ichida yoziladi: `\"A'lo\"`."] },
          { emoji: "🔢", title: "COUNTIF va SUMIF", points: ["`=COUNTIF(C2:C6;\">=90\")` — nechta 90+ ball bor (**СЧЁТЕСЛИ**).", "`=SUMIF(B2:B6;\"qiz\";C2:C6)` — faqat qizlarning ballari yig'indisi (**СУММЕСЛИ**).", "`=ROUND(AVERAGE(C2:C6);1)` — o'rtachani 1 xonagacha yaxlitlash (**ОКРУГЛ**)."] },
          { emoji: "🚦", title: "Shartli formatlash", points: ["**Главная → Условное форматирование**.", "Masalan: 90 dan yuqori — yashil, 60 dan past — qizil.", "Jadvaldagi muhim ma'lumot darhol ko'zga tashlanadi."] },
          { emoji: "📒", title: "Loyiha: Sinf jurnali", points: ["30 o'quvchi, 4 fan: Matematika, Ona tili, Tabiiyot, Jismoniy tarbiya.", "Jami (SUM), o'rtacha (ROUND+AVERAGE), baho (IF), o'rin (RANK).", "Statistika varag'ida MAX, MIN, COUNTIF, SUMIF bilan savollarga javob."] },
        ],
        practice: [
          "Ko'rgazmadagi \"Shartli hisoblash\" mashqlarini bajaring.",
          "O'qituvchi bergan **Sinf jurnali** faylini oching (30 o'quvchi).",
          "**Baho** ustuniga IF yozing: o'rtacha ≥ 85 — \"A'lo\", aks holda \"Yaxshi\".",
          "**Statistika** varag'idagi 8 ta savolga formulalar bilan javob toping.",
          "Ballarga shartli formatlash qo'ying: 90+ yashil, 60 dan past qizil.",
          "Javoblaringizni o'qituvchining **Javoblar** varag'i bilan solishtiring.",
        ],
        homework: "\"Sport musobaqasi natijalari\" jadvalini tuzing (8 ishtirokchi, ball). IF bilan \"G'olib\"/\"Ishtirokchi\" chiqaring (ball ≥ 80), COUNTIF bilan g'oliblar sonini toping.",
        quiz: [
          { q: "IF funksiyasining ruscha nomi?", options: ["СУММ", "ЕСЛИ", "МАКС", "СЧЁТ"], correct: 1 },
          { q: "Natija nima?", code: "C2 = 75\n=IF(C2>=90;\"A'lo\";\"Yaxshi\")", options: ["A'lo", "Yaxshi", "75", "XATO"], correct: 1 },
          { q: "\"Teng emas\" belgisi Excel'da qanday yoziladi?", options: ["!=", "<>", "=/=", "><"], correct: 1 },
          { q: "90 va undan yuqori ballar sonini qaysi funksiya topadi?", options: ["SUMIF", "COUNTIF", "AVERAGE", "ROUND"], correct: 1 },
          { q: "Natija nima?", code: "C2:C5 = 95, 80, 91, 60\n=COUNTIF(C2:C5;\">=90\")", options: ["1", "2", "3", "4"], correct: 1 },
          { q: "Faqat qizlarning ballari yig'indisi uchun?", options: ["SUMIF", "COUNT", "MAX", "IF"], correct: 0 },
          { q: "Ballarni rang bilan ajratish vositasi?", options: ["Shartli formatlash", "Saralash", "Avtoto'ldirish", "Diagramma"], correct: 0 },
        ],
      },
    ],
  },
];
