import type { WeekDraft } from "./types";

// 6-OY: WEB + AMALIY LOYIHALAR
export const month6: WeekDraft[] = [
  {
    title: "Media va hosting",
    days: [
      {
        title: "Veb-sahifaga rasm va video joylash",
        kind: "lesson",
        goals: ["`<video>` va `<audio>` teglari", "YouTube videoni `<iframe>` bilan qo'yish", "Rasm formatlari va hajmini optimallashtirish"],
        visual: "code",
        visualPreset: "media",
        slides: [
          { emoji: "🎥", title: "Video tegi", points: ["`<video src=\"kino.mp4\" controls></video>`.", "`controls` — ijro tugmalari.", "`width=\"400\"` — o'lcham.", "`autoplay muted loop` — avtomatik, ovozsiz, takroriy."], code: "<video src=\"video/sayohat.mp4\" controls width=\"400\"></video>" },
          { emoji: "🎵", title: "Audio tegi", points: ["`<audio src=\"qoshiq.mp3\" controls></audio>`.", "2-oyda Suno'da yaratgan qo'shig'ingizni qo'yish mumkin!"] },
          { emoji: "📺", title: "YouTube video", points: ["YouTube → **Share → Embed** → kodni nusxalang.", "`<iframe>` kodini sahifaga qo'ying.", "Video YouTube'da qoladi — saytingiz yengil bo'ladi."] },
          { emoji: "🗜️", title: "Hajmni kichraytirish", points: ["Katta rasm → sayt sekin ochiladi.", "Rasm kengligi 1200 px dan oshmasin.", "JPG — foto, PNG — shaffof, **WebP** — eng yengil.", "Video uchun 720p yetarli."], tip: "tinypng.com — rasm hajmini 70% gacha kamaytiradi." },
        ],
        practice: [
          "Jonli muharrirda \"Rasm va video\" namunasini oching va ishlashini kuzating.",
          "Portfolioingizga 2-oyda yaratgan videoingizni `<video>` bilan qo'ying.",
          "AI qo'shig'ingizni `<audio>` bilan qo'shing.",
          "Bitta YouTube ta'lim videosini `<iframe>` bilan joylang.",
          "Rasmlaringizni tinypng.com da kichraytiring va farqini solishtiring.",
        ],
        homework: "Portfolioga \"Media\" bo'limini qo'shing: 1 video, 1 audio va hover effektli 3 ta rasmdan iborat galereya.",
        quiz: [
          { q: "Video ijro tugmalarini ko'rsatuvchi atribut?", options: ["controls", "play", "buttons", "show"], correct: 0 },
          { q: "YouTube videoni saytga qo'yish tegi?", options: ["<iframe>", "<img>", "<a>", "<table>"], correct: 0 },
          { q: "Audio fayl tegi?", options: ["<audio>", "<sound>", "<music>", "<mp3>"], correct: 0 },
          { q: "Eng yengil zamonaviy rasm formati?", options: ["WebP", "BMP", "PSD", "TIFF"], correct: 0 },
          { q: "Katta rasmlar saytga qanday ta'sir qiladi?", options: ["Sayt sekin ochiladi", "Sayt tezlashadi", "Hech qanday", "Rang o'zgaradi"], correct: 0 },
          { q: "Kodda nima yetishmaydi?", code: "<video src=\"kino.mp4\"></video>\n(tugmalar ko'rinmayapti)", options: ["controls atributi", "alt atributi", "href", "<body>"], correct: 0 },
        ],
      },
      {
        title: "Veb-sahifani hostingga joylash",
        kind: "lesson",
        goals: ["Hosting va domen tushunchalari", "Saytni bepul hostingga (GitHub Pages / Netlify) joylash", "Havolani ulashish"],
        slides: [
          { emoji: "🏠", title: "Hosting nima?", points: ["**Hosting** — saytingiz fayllari turadigan internetdagi kompyuter (server).", "Hosting bo'lsa — sayt **24/7** hamma uchun ochiq.", "Bepul hostinglar: **GitHub Pages**, **Netlify Drop**, Vercel."] },
          { emoji: "🔤", title: "Domen nima?", points: ["**Domen** — sayt manzili: `ali-portfolio.netlify.app`.", "Bepul: subdomen (`.netlify.app`, `.github.io`).", "Pullik: o'z nomingiz (`ali.uz`)."] },
          { emoji: "🪂", title: "Netlify Drop — eng oson yo'l", points: ["1. app.netlify.com/drop saytini oching.", "2. `portfolio` papkangizni sichqoncha bilan tashlang.", "3. Bir necha soniyada havola tayyor!", "4. Akkaunt bilan kirib, sayt nomini o'zgartiring."] },
          { emoji: "🐙", title: "GitHub Pages", points: ["github.com da repozitoriy yarating.", "Fayllarni yuklang (Upload files).", "**Settings → Pages → Deploy from branch → main**.", "Manzil: `ism.github.io/portfolio`."], tip: "Asosiy sahifa albatta `index.html` deb nomlangan bo'lishi kerak!" },
          { emoji: "🔐", title: "Xavfsizlik", points: ["Saytda shaxsiy ma'lumot yo'qligini yana tekshiring.", "Akkaunt parolini hech kimga bermang.", "Ota-ona ruxsati bilan akkaunt oching."] },
        ],
        practice: [
          "Portfolio papkasida `index.html` borligini va havolalar to'g'riligini tekshiring.",
          "O'qituvchi bilan Netlify Drop orqali saytni joylang.",
          "Olingan havolani telefonda oching — ishlayaptimi?",
          "Sayt nomini o'zgartiring (masalan, `ism-itkids`).",
          "Havolani sinf ro'yxatiga qo'shing.",
        ],
        homework: "Sayt havolangizni ota-onangizga yuboring. Saytga 1 ta o'zgartirish kiritib, qayta joylang (yangilash).",
        quiz: [
          { q: "Hosting nima?", options: ["Sayt fayllari turadigan internetdagi server", "Brauzer", "Rasm dasturi", "Parol"], correct: 0 },
          { q: "Domen nima?", options: ["Sayt manzili", "Rasm", "Shrift", "Teg"], correct: 0 },
          { q: "Qaysi biri bepul hosting?", options: ["Netlify", "Photoshop", "Excel", "Word"], correct: 0 },
          { q: "Bosh sahifa fayli qanday nomlanishi kerak?", options: ["index.html", "home.doc", "sayt.png", "main.mp4"], correct: 0 },
          { q: "Saytni joylashdan oldin nima tekshiriladi?", options: ["Shaxsiy ma'lumot yo'qligi va havolalar", "Kompyuter narxi", "Monitor o'lchami", "Hech narsa"], correct: 0 },
          { q: "`ali.github.io` — qanday domen?", options: ["Bepul subdomen", "Pullik .uz domen", "Email", "Fayl"], correct: 0 },
        ],
      },
      {
        title: "Mini loyiha — «Onlayn galereya»",
        kind: "project",
        goals: ["Rasm galereyasi sahifasini yaratish", "Grid va hover effektlari", "Galereyani internetga joylash"],
        visual: "code",
        visualPreset: "media",
        slides: [
          { emoji: "🖼️", title: "Loyiha", points: ["Photoshop, Paint, AI va Canva ishlaringizdan **onlayn galereya**.", "Kamida **8 ta rasm**, har biri nom bilan.", "Internetga joylangan bo'lsin!"] },
          { emoji: "▦", title: "Galereya CSS", points: ["`display: grid;` + `grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));`", "Bu — ekran kengligiga qarab ustunlar soni **o'zi** o'zgaradi!", "`object-fit: cover;` — rasmlar bir xil o'lchamda."], code: ".galereya {\n  display: grid;\n  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));\n  gap: 12px;\n}\n.galereya img {\n  width: 100%;\n  height: 180px;\n  object-fit: cover;\n  border-radius: 12px;\n}" },
          { emoji: "✨", title: "Effektlar", points: ["Hover: `transform: scale(1.05)`.", "`transition: .3s` — silliq.", "Rasm ostida `<figcaption>` — izoh."] },
          { emoji: "🌍", title: "Joylash", points: ["Galereyani portfolio saytingizga qo'shing.", "Netlify'da qayta joylang.", "Havolani sinf chatiga (o'qituvchi orqali) yuboring."] },
        ],
        practice: [
          "8+ ta rasmni tanlab, kichraytiring va `rasmlar/` papkasiga joylang.",
          "galereya.html sahifasini grid bilan yarating.",
          "Har rasmga izoh (`figcaption`) va hover effekt bering.",
          "Menyuga \"Galereya\" havolasini qo'shing.",
          "Saytni qayta joylang va telefonda tekshiring.",
        ],
        homework: "Galereyaga \"Oldin/Keyin\" bo'limini qo'shing: Photoshop retush ishingizning asl va tayyor holati yonma-yon.",
        rubric: ["8+ rasm, izohlar bilan", "Moslashuvchan grid", "Hover effekt", "Menyuda havola", "Internetga joylangan"],
        quiz: [
          { q: "Rasmlar bir xil o'lchamda kesilib ko'rinishi uchun?", options: ["object-fit: cover;", "font-size: 12px;", "display: none;", "color: red;"], correct: 0 },
          { q: "Ekranga qarab ustunlar soni o'zgarishi uchun?", options: ["repeat(auto-fill, minmax(200px, 1fr))", "repeat(3, 1fr)", "flex: 1", "width: 200px"], correct: 0 },
          { q: "Rasm ostidagi izoh tegi?", options: ["<figcaption>", "<caption-img>", "<alt>", "<title>"], correct: 0 },
          { q: "Silliq animatsiya uchun?", options: ["transition", "position", "display", "margin"], correct: 0 },
          { q: "Galereyada nechta rasm talab qilingan?", options: ["Kamida 8", "1", "3", "100"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Formalar",
    days: [
      {
        title: "HTML formalar (ism, email)",
        kind: "lesson",
        goals: ["`<form>`, `<input>`, `<label>`, `<button>` teglari", "Input turlari: text, email, number, password, checkbox, radio", "Majburiy maydonlar (required)"],
        visual: "code",
        visualPreset: "form",
        slides: [
          { emoji: "📝", title: "Forma nima?", points: ["Foydalanuvchidan ma'lumot **yig'ish** uchun: ro'yxatdan o'tish, so'rovnoma, qidiruv.", "`<form>` — forma idishi.", "`<button type=\"submit\">` — yuborish tugmasi."] },
          { emoji: "⌨️", title: "Input turlari", points: ["`type=\"text\"` — oddiy matn.", "`type=\"email\"` — email (@ ni tekshiradi).", "`type=\"number\"` — faqat son.", "`type=\"password\"` — yashirin ●●●.", "`type=\"date\"`, `type=\"color\"` — sana va rang tanlash."] },
          { emoji: "🏷️", title: "Label va placeholder", points: ["`<label>` — maydon nomi. Bossangiz maydon faollashadi.", "`placeholder=\"Ismingiz\"` — kulrang maslahat matn.", "`required` — to'ldirmasa yuborilmaydi!"], code: "<label>Ism:\n  <input type=\"text\" placeholder=\"Ali\" required>\n</label>" },
          { emoji: "☑️", title: "Tanlovlar", points: ["`checkbox` — bir nechtasini tanlash (qiziqishlar).", "`radio` — faqat bittasini (sinf). Bir xil `name` bering!", "`<select>` + `<option>` — ochiladigan ro'yxat.", "`<textarea>` — ko'p qatorli matn."] },
        ],
        practice: [
          "Jonli muharrirda \"Forma\" namunasini oching va har bir maydonni sinab ko'ring.",
          "Email maydoniga @ siz matn yozib, yuborishga urining — nima bo'ladi?",
          "Formaga \"Sinfingiz\" uchun 3 ta radio tugma qo'shing.",
          "\"Qiziqishlaringiz\" uchun 4 ta checkbox qo'shing.",
          "`<textarea>` bilan \"Izoh\" maydonini qo'shing va ism/email ni required qiling.",
        ],
        homework: "\"Sevimli kitobim\" so'rovnomasi formasini yarating: ism, yosh (number), kitob nomi, janr (select), baho (radio 1–5), izoh (textarea).",
        quiz: [
          { q: "Email kiritish uchun input turi?", options: ["type=\"email\"", "type=\"text-mail\"", "type=\"@\"", "type=\"letter\""], correct: 0 },
          { q: "Parolni ●●● ko'rinishida yashiradigan tur?", options: ["password", "hidden-text", "secret", "text"], correct: 0 },
          { q: "Maydon to'ldirilmasa forma yuborilmasligi uchun?", options: ["required", "placeholder", "label", "name"], correct: 0 },
          { q: "Faqat bittasini tanlash mumkin bo'lgan variantlar?", options: ["radio", "checkbox", "textarea", "password"], correct: 0 },
          { q: "Ko'p qatorli matn maydoni?", options: ["<textarea>", "<input type=\"text\">", "<p>", "<label>"], correct: 0 },
          { q: "Maydondagi kulrang maslahat matn?", code: "<input type=\"text\" ________=\"Ismingiz\">", options: ["placeholder", "value", "alt", "title"], correct: 0 },
        ],
      },
      {
        title: "Formani CSS bilan stillash",
        kind: "lesson",
        goals: ["Input va tugmalarni chiroyli qilish", ":focus va :hover holatlari", "Flexbox bilan forma joylashuvi"],
        visual: "code",
        visualPreset: "form",
        slides: [
          { emoji: "🎨", title: "Input dizayni", points: ["`padding: 10px;` — ichki joy.", "`border: 1px solid #94a3b8;` — chegara.", "`border-radius: 8px;` — yumaloq.", "`width: 100%;` — to'liq kenglik."] },
          { emoji: "🔦", title: ":focus holati", points: ["Foydalanuvchi maydonga bosganda.", "`outline: none; border-color: #6366f1;` — chiroyli ramka.", "Qayerga yozayotgani aniq ko'rinadi."], code: "input:focus {\n  outline: none;\n  border-color: #6366f1;\n  box-shadow: 0 0 0 3px #c7d2fe;\n}" },
          { emoji: "🔘", title: "Tugma", points: ["Yorqin fon, oq matn, `cursor: pointer;`.", "`:hover` — rang to'qroq.", "`:active` — bosilganda biroz kichrayadi: `transform: scale(.97)`."] },
          { emoji: "📐", title: "Joylashuv", points: ["`display: flex; flex-direction: column; gap: 12px;` — maydonlar ustma-ust.", "`max-width: 400px; margin: auto;` — markazda.", "Forma fonini oq karta qiling: padding + soya."] },
        ],
        practice: [
          "Uy vazifasidagi so'rovnoma formasini oching.",
          "Formani markazdagi oq kartaga aylantiring (padding, border-radius, soya).",
          "Barcha input'larga bir xil dizayn va :focus effekti bering.",
          "Yuborish tugmasini yorqin qiling, :hover va :active qo'shing.",
          "Telefon ko'rinishida tekshiring.",
        ],
        homework: "Formangiz uchun 2 xil rang mavzusi (och va to'q) yarating. Qaysi biri yaxshiroq ekanini oilangizdan so'rang.",
        quiz: [
          { q: "Maydon bosilgan (faol) holati?", options: [":focus", ":hover", ":click", ":active-input"], correct: 0 },
          { q: "Sichqoncha ustiga kelgandagi holat?", options: [":hover", ":focus", ":visited", ":checked"], correct: 0 },
          { q: "Tugma ustida qo'l belgisi chiqishi uchun?", options: ["cursor: pointer;", "hand: yes;", "pointer: on;", "mouse: hand;"], correct: 0 },
          { q: "Maydonlarni ustma-ust joylash?", options: ["flex-direction: column;", "flex-direction: row;", "display: inline;", "float: left;"], correct: 0 },
          { q: "Formani markazga qo'yish?", options: ["max-width + margin: auto", "text-align: left", "position: absolute; left: 0", "display: none"], correct: 0 },
        ],
      },
      {
        title: "Mini loyiha — «Ro'yxatdan o'tish formasi»",
        kind: "project",
        goals: ["To'liq, chiroyli va qulay forma yaratish", "Formani ma'lumot qabul qiladigan qilish (Formspree / Google Forms)", "Foydalanuvchi uchun qulaylik (UX)"],
        visual: "code",
        visualPreset: "form",
        slides: [
          { emoji: "🧾", title: "Loyiha", points: ["\"IT Kids to'garagiga ro'yxatdan o'tish\" formasi.", "Maydonlar: ism, familiya, yosh, email, sinf (radio), qiziqishlar (checkbox), izoh.", "Chiroyli CSS dizayn."] },
          { emoji: "📬", title: "Ma'lumot qayerga boradi?", points: ["HTML formaning o'zi ma'lumotni saqlamaydi — **server** kerak.", "Oson yo'l: **Formspree** — `action=\"https://formspree.io/f/...\"` va `method=\"POST\"`.", "Yoki Google Forms'ni `<iframe>` bilan qo'yish."] },
          { emoji: "😊", title: "Qulaylik (UX)", points: ["Har maydonda aniq `label`.", "Majburiy maydonlar `*` bilan belgilangan.", "Tugma matni aniq: \"Ro'yxatdan o'tish\".", "Xato bo'lsa — tushunarli xabar."] },
          { emoji: "🔐", title: "Ma'lumot xavfsizligi", points: ["Hech qachon formada **parol** yoki **karta raqami** so'ramang (mashq formasida).", "Yig'ilgan ma'lumotni boshqalarga ko'rsatmang."] },
        ],
        practice: [
          "Forma maydonlarini rejalashtiring (7 ta maydon).",
          "HTML kodini yozing: label, placeholder, required.",
          "CSS bilan karta dizayni, :focus va :hover bering.",
          "O'qituvchi bilan Formspree'ga ulab, test yuborib ko'ring.",
          "Formani portfolioga \"Aloqa\" sahifasi sifatida qo'shing va qayta joylang.",
        ],
        homework: "Formangizni oilangizdan 2 kishiga to'ldirtiring. Nima noqulay bo'ldi? 1 ta yaxshilash kiriting.",
        rubric: ["7 ta maydon, label bilan", "required va to'g'ri input turlari", "Chiroyli CSS, focus/hover", "Ma'lumot yuboriladi (Formspree yoki Google Forms)", "Portfolioga qo'shilgan"],
        quiz: [
          { q: "HTML forma ma'lumotni o'zi saqlaydimi?", options: ["Yo'q, server yoki xizmat kerak", "Ha, doim", "Faqat rasmni", "Faqat parolni"], correct: 0 },
          { q: "Forma ma'lumotini yuborish usuli atributi?", options: ["method=\"POST\"", "send=\"yes\"", "href=\"post\"", "type=\"send\""], correct: 0 },
          { q: "Ma'lumot qayerga yuborilishini belgilovchi atribut?", options: ["action", "src", "href", "alt"], correct: 0 },
          { q: "Mashq formasida nimani so'ramaslik kerak?", options: ["Karta raqami va parol", "Ism", "Yosh", "Qiziqishlar"], correct: 0 },
          { q: "Yaxshi tugma matni?", options: ["\"Ro'yxatdan o'tish\"", "\"Bos\"", "\"???\"", "\"OK123\""], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Yakuniy loyiha",
    days: [
      {
        title: "Yakuniy loyiha uchun g'oyalar",
        kind: "project",
        goals: ["6 oyda o'rganilganlarni tahlil qilish", "Yakuniy loyiha g'oyasini tanlash", "Loyiha rejasi va jadvalini tuzish"],
        slides: [
          { emoji: "🧭", title: "6 oyda nimalarni o'rgandik?", points: ["🖥️ Kompyuter, Word, PowerPoint, Excel.", "🎬 CapCut va AI (matn, rasm, video, musiqa).", "🐱 Scratch dasturlash.", "🎨 Photoshop.", "🌐 HTML/CSS va hosting."] },
          { emoji: "💡", title: "Loyiha turlari", points: ["🌐 **Sayt**: mavzuli sayt (sevimli sport, shahrim, hayvonlar ensiklopediyasi).", "🎮 **O'yin**: Scratch'da murakkab o'yin (darajalar, ball, taymer).", "🤖 **AI loyiha**: AI yordamida ertak-kitob, komiks yoki qisqa film.", "🔗 **Aralash**: sayt + ichida o'yin/video/galereya."] },
          { emoji: "📋", title: "Loyiha rejasi", points: ["Nomi va g'oyasi (1–2 gap).", "Kim uchun? (auditoriya)", "Qaysi dasturlar?", "3 ta asosiy qism.", "Muvaffaqiyat mezoni: \"tayyor\" nimani anglatadi?"] },
          { emoji: "🗓️", title: "Vaqt jadvali", points: ["23-hafta 1-kun: g'oya va reja.", "23-hafta 2-kun: asosiy ish.", "23-hafta 3-kun: yakunlash.", "24-hafta 1-kun: taqdimot!"] },
        ],
        practice: [
          "6 oylik ishlaringizni ko'rib chiqing: qaysi biri eng qiziq bo'ldi?",
          "\"G'oyalar bozori\": har kim 1 daqiqa o'z g'oyasini aytadi.",
          "Loyiha turini tanlang (yakka yoki juftlikda).",
          "Reja varag'ini to'ldiring va eskiz chizing.",
          "O'qituvchi bilan rejani tasdiqlang.",
        ],
        homework: "Loyiha uchun materiallarni yig'ing: matnlar, rasmlar, AI promptlar. Hammasini `yakuniy_loyiha` papkasiga joylang.",
        rubric: ["Aniq g'oya va auditoriya", "Dasturlar tanlangan", "3 asosiy qism rejalashtirilgan", "Muvaffaqiyat mezoni yozilgan", "O'qituvchi tasdiqlagan"],
        quiz: [
          { q: "Loyiha rejasida nima bo'lishi kerak?", options: ["G'oya, auditoriya, dasturlar, qismlar", "Faqat nom", "Faqat rasm", "Hech narsa"], correct: 0 },
          { q: "\"Auditoriya\" nima?", options: ["Loyiha kim uchun ekanligi", "Kompyuter xonasi", "Dastur nomi", "Fayl turi"], correct: 0 },
          { q: "Scratch'da darajali o'yin qaysi loyiha turiga kiradi?", options: ["O'yin", "Sayt", "AI loyiha", "Excel"], correct: 0 },
          { q: "Loyihani qancha vaqtda tugatamiz?", options: ["3 dars + taqdimot", "1 daqiqa", "1 yil", "Muddatsiz"], correct: 0 },
          { q: "Muvaffaqiyat mezoni nima uchun kerak?", options: ["Loyiha qachon \"tayyor\" ekanini bilish uchun", "Baho olish uchun faqat", "Kerak emas", "Rang tanlash uchun"], correct: 0 },
        ],
      },
      {
        title: "Loyihani ishlab chiqish (sayt / o'yin / AI rasm)",
        kind: "project",
        goals: ["Reja asosida mustaqil ishlash", "Muammolarni o'zi hal qilish", "Oraliq natijani tekshirish"],
        visual: "code",
        visualPreset: "portfolio",
        slides: [
          { emoji: "🛠️", title: "Ish kuni", points: ["Butun dars — loyihangiz ustida.", "Har 25 daqiqada **checkpoint**: nima tayyor, nima qoldi?", "O'qituvchi — maslahatchi."] },
          { emoji: "🔎", title: "Muammo bo'lsa", points: ["1. Xato xabarini diqqat bilan o'qing.", "2. Kodni qismlarga bo'lib tekshiring.", "3. Sherigingizdan so'rang.", "4. AI yordamchidan **tushuntirishni** so'rang (to'liq yozdirmang!).", "5. O'qituvchini chaqiring."] },
          { emoji: "📸", title: "Jarayonni yozib boring", points: ["Skrinshotlar oling — taqdimotda \"qanday qildim\" ni ko'rsatasiz.", "Qiyin joylarni daftarga yozing."] },
          { emoji: "✅", title: "Dars oxiriga", points: ["Loyihaning **asosiy qismi** ishlashi kerak.", "Hammasini saqlang (va zaxira nusxa!)."] },
        ],
        practice: [
          "Reja bo'yicha 1-qismni yakunlang.",
          "Checkpoint: 25-daqiqada o'qituvchiga holatingizni ayting.",
          "2-qismni boshlang, muammolarni 5 qadamli usulda hal qiling.",
          "Jarayondan 3 ta skrinshot oling.",
          "Loyihani saqlang va zaxira nusxasini fleshka/bulutga joylang.",
        ],
        homework: "Loyihaning 3-qismini boshlang. Taqdimot uchun \"Loyihamning hikoyasi\" — 5 gap yozing.",
        rubric: ["1- va 2-qismlar tayyor", "Checkpoint'da holatini tushuntiradi", "Muammolarni 5 qadamli usulda hal qiladi", "3 ta jarayon skrinshoti", "Zaxira nusxa olingan"],
        quiz: [
          { q: "Muammo bo'lganda birinchi qadam?", options: ["Xato xabarini o'qish", "Hammasini o'chirish", "Uyga ketish", "Kompyuterni o'chirish"], correct: 0 },
          { q: "AI yordamchidan qanday foydalanish to'g'ri?", options: ["Tushuntirishni so'rash", "Hamma kodni yozdirib, o'zimniki deyish", "Umuman foydalanmaslik shart", "Parol so'rash"], correct: 0 },
          { q: "Zaxira nusxa nima uchun kerak?", options: ["Fayl yo'qolsa tiklash uchun", "Chiroyli bo'lishi uchun", "Kerak emas", "Sekinlashtirish uchun"], correct: 0 },
          { q: "Checkpoint nima?", options: ["Oraliq tekshiruv", "Yakuniy baho", "Dam olish", "O'yin"], correct: 0 },
          { q: "Skrinshotlar nima uchun kerak?", options: ["Taqdimotda jarayonni ko'rsatish", "Kompyuter xotirasini to'ldirish", "Hech narsa", "Rangni o'zgartirish"], correct: 0 },
        ],
      },
      {
        title: "Yakuniy loyihani tayyorlash",
        kind: "project",
        goals: ["Loyihani to'liq yakunlash va sayqallash", "Taqdimot tayyorlash", "Mashq taqdimoti"],
        slides: [
          { emoji: "💎", title: "Sayqallash", points: ["Xatolarni tuzating.", "Dizaynni bir xil qiling: ranglar, shriftlar.", "Matnlarni imlo bo'yicha tekshiring.", "Do'stingiz loyihangizni \"sinovchi\" sifatida sinab ko'rsin."] },
          { emoji: "🎤", title: "Taqdimot tuzilishi (3 daqiqa)", points: ["1. Salomlashish va loyiha nomi (15 s).", "2. G'oya: nima va kim uchun (30 s).", "3. Namoyish (1.5 daq).", "4. Qanday qildim, nima qiyin bo'ldi (30 s).", "5. Rahmat + savollar (15 s)."] },
          { emoji: "📑", title: "Taqdimot slaydlari", points: ["3–5 ta slayd yetarli.", "Katta rasmlar, kam matn.", "PowerPoint, Canva yoki AI slayd vositasi."] },
          { emoji: "🔁", title: "Mashq", points: ["Sherigingizga 2 marta taqdim qiling.", "Vaqtni o'lchang — 3 daqiqadan oshmasin.", "Hayajon — normal! Chuqur nafas oling 🙂"] },
        ],
        practice: [
          "Loyihaning oxirgi qismini yakunlang.",
          "\"Sinovchi\" do'stingiz loyihani sinasin — topilgan xatolarni tuzating.",
          "3–5 slaydli taqdimot tayyorlang.",
          "Juftlikda 2 marta mashq taqdimoti qiling (vaqt bilan).",
          "Hamma fayllarni bitta papkaga yig'ing va saqlang.",
        ],
        homework: "Taqdimotingizni uyda oilangiz oldida mashq qiling. Ota-onangizni \"Mini Hackathon\"ga taklif qiling!",
        rubric: ["Loyiha to'liq ishlaydi", "Dizayn yagona, xatosiz", "3–5 slaydli taqdimot", "Taqdimot 3 daqiqaga sig'adi"],
        quiz: [
          { q: "Taqdimot qancha davom etishi kerak?", options: ["Taxminan 3 daqiqa", "30 daqiqa", "10 soniya", "1 soat"], correct: 0 },
          { q: "Taqdimotning eng uzun qismi?", options: ["Namoyish", "Salomlashish", "Rahmat", "Sarlavha"], correct: 0 },
          { q: "\"Sinovchi\" nima qiladi?", options: ["Loyihani sinab, xatolarni topadi", "Loyihani o'chiradi", "Baho qo'yadi faqat", "Hech narsa"], correct: 0 },
          { q: "Taqdimot slaydlarida nima ko'p bo'lsin?", options: ["Katta rasmlar, kam matn", "Mayda matn", "Faqat jadval", "Bo'sh slaydlar"], correct: 0 },
          { q: "Hayajonlansangiz nima qilasiz?", options: ["Chuqur nafas olib, mashq qilganingizni eslaysiz", "Qochib ketasiz", "Gapirmaysiz", "Yig'laysiz"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Taqdimot va bitiruv",
    days: [
      {
        title: "Loyiha prezentatsiyasi",
        kind: "event",
        goals: ["Yakuniy loyihani sinfga taqdim etish", "Savollarga javob berish", "Boshqalarni baholash va qo'llab-quvvatlash"],
        slides: [
          { emoji: "🎤", title: "Taqdimot kuni!", points: ["Har bir o'quvchi/juftlik — **3 daqiqa** + 1–2 savol.", "Tartib qur'a bilan aniqlanadi.", "Tomoshabinlar — diqqatli va do'stona."] },
          { emoji: "📊", title: "Baholash mezonlari", points: ["💡 G'oya va ijodkorlik.", "🛠️ Texnik bajarilish.", "🎨 Dizayn.", "🎤 Taqdimot mahorati."] },
          { emoji: "⭐", title: "Tomoshabin vazifasi", points: ["Har taqdimotdan keyin: **1 ta yoqqan narsa** va **1 ta savol**.", "Baholash varag'iga 1–5 yulduz."] },
          { emoji: "🏆", title: "Nominatsiyalar", points: ["🥇 Eng yaxshi sayt.", "🎮 Eng yaxshi o'yin.", "🤖 Eng ijodiy AI loyiha.", "🎤 Eng yaxshi notiq."] },
        ],
        practice: [
          "Qur'a tashlash va taqdimot tartibini belgilash.",
          "Har bir o'quvchi 3 daqiqalik taqdimot qiladi.",
          "Tomoshabinlar baholash varag'ini to'ldiradi.",
          "Nominatsiyalar uchun ovoz berish.",
          "O'qituvchi har bir loyihaga qisqa fikr bildiradi.",
        ],
        homework: "O'qituvchi va sinfdoshlar fikri asosida loyihangizni yaxshilang — ertaga ota-onalar oldida ko'rsatasiz!",
        rubric: ["G'oya va ijodkorlik", "Texnik bajarilish", "Dizayn", "Taqdimot mahorati", "Savollarga javob"],
        quiz: [
          { q: "Taqdimotdan keyin tomoshabin nima qiladi?", options: ["1 ta yoqqan narsa va 1 ta savol aytadi", "Jim o'tiradi", "Faqat tanqid qiladi", "Chiqib ketadi"], correct: 0 },
          { q: "Qaysi biri baholash mezoni emas?", options: ["G'oya", "Dizayn", "Kompyuter narxi", "Taqdimot"], correct: 2 },
          { q: "Savolga javobini bilmasangiz?", options: ["\"Yaxshi savol, buni o'rganib ko'raman\" deysiz", "Yolg'on javob berasiz", "E'tibor bermaysiz", "Xafa bo'lasiz"], correct: 0 },
          { q: "6 oyda o'rganilmagan mavzu?", options: ["Scratch", "Photoshop", "HTML/CSS", "Avtomobil haydash"], correct: 3 },
          { q: "Yaxshi tomoshabin qanday bo'ladi?", options: ["Diqqatli va do'stona", "Telefon o'ynaydi", "Gapiradi", "Uxlaydi"], correct: 0 },
        ],
      },
      {
        title: "Ota-onalar oldida «Mini Hackathon»",
        kind: "event",
        goals: ["Cheklangan vaqtda jamoaviy vazifani bajarish", "Ota-onalarga ko'nikmalarni namoyish qilish", "Jamoada ishlash"],
        visual: "prompt-builder",
        visualPreset: "rasm",
        slides: [
          { emoji: "⚡", title: "Hackathon nima?", points: ["**Hackathon** — qisqa vaqtda jamoa bo'lib loyiha yaratish musobaqasi.", "Bizda: **45 daqiqa**, jamoada 3–4 kishi.", "Ota-onalar — tomoshabin va hakam!"] },
          { emoji: "🎯", title: "Vazifa (misol)", points: ["Mavzu: **\"Bizning shaharimiz — kelajakda\"**.", "Jamoa tayyorlaydi: AI rasm + 1 sahifalik sayt (HTML/CSS) + 30 soniyalik taqdimot.", "Yoki: Scratch'da mini o'yin."] },
          { emoji: "👥", title: "Jamoa rollari", points: ["🎨 **Dizayner** — AI rasm va ranglar.", "💻 **Dasturchi** — HTML/CSS yoki Scratch.", "✍️ **Muallif** — matnlar.", "🎤 **Notiq** — taqdimot."] },
          { emoji: "⏱️", title: "Tartib", points: ["5 daq — mavzu e'loni va reja.", "45 daq — ish.", "20 daq — jamoalar taqdimoti (har biri 2–3 daq).", "10 daq — ota-onalar ovozi va taqdirlash."] },
        ],
        practice: [
          "Jamoalarga bo'linish va rollarni taqsimlash.",
          "Mavzu e'loni va 5 daqiqalik reja.",
          "45 daqiqa jamoaviy ish (ko'rgazmadagi prompt konstruktoridan foydalanish mumkin).",
          "Ota-onalar oldida jamoa taqdimotlari.",
          "Ota-onalar ovozi bilan g'olib jamoani aniqlash.",
        ],
        homework: "Ertangi bitiruv marosimiga tayyorlaning: kursdan eng yoqqan 3 narsani yozib keling — sertifikat topshirilganda aytasiz!",
        rubric: ["Mavzuga moslik", "Jamoaviy ish (hamma rolda)", "Texnik natija (rasm + sayt/o'yin)", "Taqdimot", "Vaqtga rioya"],
        quiz: [
          { q: "Hackathon nima?", options: ["Qisqa vaqtda jamoa bo'lib loyiha yaratish musobaqasi", "Kompyuter o'yini", "Dars jadvali", "Antivirus"], correct: 0 },
          { q: "Jamoada kim taqdimot qiladi?", options: ["Notiq", "Dizayner", "Faqat o'qituvchi", "Hech kim"], correct: 0 },
          { q: "Jamoada ishlashning muhim qoidasi?", options: ["Har kim o'z roliga javobgar va bir-biriga yordam beradi", "Hammani bir kishi qiladi", "Bahslashish", "Jim o'tirish"], correct: 0 },
          { q: "Hackathonda asosiy ish uchun qancha vaqt bor?", options: ["45 daqiqa", "5 daqiqa", "3 kun", "10 soat"], correct: 0 },
          { q: "AI rasm kimning vazifasi?", options: ["Dizayner", "Notiq", "Ota-onalar", "Hakam"], correct: 0 },
        ],
      },
      {
        title: "Sertifikat topshirish va taqdirlash marosimi 🎓",
        kind: "event",
        goals: ["6 oylik yo'lni birga eslash", "Yutuqlarni nishonlash", "Keyingi o'rganish yo'nalishlarini tanlash"],
        slides: [
          { emoji: "🎓", title: "Tabriklaymiz!", points: ["Siz **72 dars**ni tamomladingiz!", "Endi siz: kompyuter ustasi, video montajchi, AI ijodkori, Scratch dasturchi, Photoshop dizayneri va veb-dasturchisiz! 🚀"] },
          { emoji: "🗺️", title: "Bizning yo'limiz", points: ["1-oy 🖥️ Kompyuter savodxonligi.", "2-oy 🎬 Video va AI.", "3-oy 🐱 Scratch.", "4-oy 🎨 Photoshop.", "5-oy 🌐 HTML/CSS.", "6-oy 🚀 Amaliy loyihalar."] },
          { emoji: "🔭", title: "Keyin nima o'rganish mumkin?", points: ["🐍 **Python** — haqiqiy dasturlash tili.", "🟨 **JavaScript** — saytlarni jonlantirish.", "🎮 **Roblox Studio / Unity** — o'yin yaratish.", "🤖 **Robototexnika** — Arduino, micro:bit.", "🎨 **Figma** — UI/UX dizayn."] },
          { emoji: "💌", title: "Eslab qoling", points: ["Har kuni oz-ozdan o'rganing.", "Xato qilishdan qo'rqmang — xato ham o'qituvchi!", "Bilganingizni boshqalarga o'rgating.", "Internetda xavfsiz va halol bo'ling."] },
        ],
        practice: [
          "6 oylik slayd-shou: eng yaxshi ishlarimizni birga tomosha qilamiz.",
          "Har o'quvchi kursdan eng yoqqan 3 narsani aytadi.",
          "Sertifikatlar va nominatsiya sovg'alarini topshirish.",
          "Umumiy rasmga tushish 📸.",
          "Keyingi o'rganish yo'nalishi bo'yicha maslahatlar.",
        ],
        homework: "Yo'q — bayram! 🎉 Portfolio saytingizni yangilab boring va keyingi yo'nalishingizni tanlang.",
        quiz: [
          { q: "Kurs davomida nechta dars bo'ldi?", options: ["72", "12", "24", "100"], correct: 0 },
          { q: "Saytlarni jonlantiradigan dasturlash tili?", options: ["JavaScript", "HTML", "Excel", "Paint"], correct: 0 },
          { q: "3-oyda qaysi dasturlash muhitini o'rgandik?", options: ["Scratch", "Python", "Unity", "Figma"], correct: 0 },
          { q: "Xato qilganda to'g'ri munosabat?", options: ["Xatodan o'rganish", "Taslim bo'lish", "Yashirish", "Boshqani ayblash"], correct: 0 },
          { q: "Qaysi biri robototexnika platformasi?", options: ["Arduino", "Canva", "CapCut", "Word"], correct: 0 },
        ],
      },
    ],
  },
];
