import type { WeekDraft } from "./types";

// 4-OY: SCRATCH — O'YINLAR YARATISH
// Har hafta bitta o'yin, 3 bosqichda: 1) sahna va qahramon, 2) asosiy mexanika, 3) ball, qiyinlik, bezash.
export const month4: WeekDraft[] = [
  {
    title: "Snake 🐍",
    days: [
      {
        title: "Snake: sahna va ilon boshini boshqarish",
        kind: "lesson",
        goals: ["O'yin rejasini tuzish", "Ilon boshini strelkalar bilan boshqarish", "Katak-katak (to'r) harakatini tushunish"],
        visual: "game",
        visualPreset: "snake",
        slides: [
          { emoji: "🐍", title: "Snake o'yini", points: ["Ilon doim yuradi, siz faqat **yo'nalishni** tanlaysiz.", "Olma yesa — **uzayadi** va ball oladi.", "Devorga yoki o'z dumiga tegsa — **o'yin tugaydi**.", "1970-yillardan beri eng mashhur o'yinlardan biri!"] },
          { emoji: "📝", title: "O'yin rejasi", points: ["Sprite'lar: **Bosh** (yashil kvadrat), **Olma**.", "O'zgaruvchilar: **Ball**, **Uzunlik**.", "Bu dars: bosh harakati. Keyingi dars: olma va dum. 3-dars: Game Over."] },
          { emoji: "🟩", title: "Boshni chizish", points: ["Yangi sprite → 🖌️ **Paint** → 20×20 yashil kvadrat.", "Ko'zlar qo'shing — qaysi tomonga qarayotgani bilinsin.", "Aylanish uslubi: «**chap-o'ng emas, aylanmasin**» (don't rotate) — kvadrat qiyshaymasin."] },
          { emoji: "🎮", title: "Yo'nalish va harakat", points: ["Strelka faqat **yo'nalishni** o'zgartiradi.", "Harakat esa doimiy tsiklda: har qadamda 20 piksel (1 katak).", "Kutish (0.15 s) — ilon tezligi."], code: "🏁 bayroq bosilganda\nx: 0 y: 0 ga bor\n90 yo'nalishga qara\ndoim takrorla\n  20 qadam yur\n  0.15 soniya kut\n\nyuqori strelka bosilganda\n  0 yo'nalishga qara\n(pastga: 180, chapga: −90, o'ngga: 90)" },
          { emoji: "🚫", title: "Orqaga burilmaslik", points: ["Ilon o'ngga ketayotganda birdan chapga burilsa — o'ziga uriladi!", "Shart: «agar <yo'nalish = 90 emas> bo'lsa → −90 ga qara».", "Bu — 3-oyda o'rgangan «emas» operatori!"] },
        ],
        practice: [
          "Ko'rgazmadagi Snake namunasini 2 daqiqa o'ynang — qanday qoidalari bor?",
          "Scratch'da yangi loyiha: `Snake_Ism`. Fonni to'q rangga o'zgartiring.",
          "20×20 yashil «Bosh» sprite'ini chizing va aylanmaydigan qiling.",
          "Doimiy harakat tsiklini yozing (20 qadam + 0.15 kut).",
          "4 ta strelka uchun yo'nalish skriptlarini yozing, orqaga burilishni taqiqlang.",
        ],
        homework: "Snake loyihasini uyda qayta oching: tezlikni o'zgartirib ko'ring (0.1 va 0.25 kut). Qaysi biri qulayroq? Boshga ko'zlar chizing.",
        quiz: [
          { q: "Snake'da strelka nimani o'zgartiradi?", options: ["Faqat yo'nalishni", "Ilon rangini", "Ballni", "Fonni"], correct: 0 },
          { q: "Yuqoriga qarash uchun yo'nalish?", options: ["0", "90", "180", "−90"], correct: 0 },
          { q: "Ilon tezligini nima belgilaydi?", options: ["Tsikldagi «kut» vaqti", "Sprite o'lchami", "Fon rangi", "Tovush"], correct: 0 },
          { q: "Nega ilon to'g'ridan-to'g'ri orqaga burilmasligi kerak?", options: ["O'z dumiga urilib qoladi", "Rang o'zgaradi", "Scratch ruxsat bermaydi", "Ball kamayadi"], correct: 0 },
          { q: "Kvadrat bosh qiyshaymasligi uchun aylanish uslubi?", options: ["aylanmasin (don't rotate)", "hamma tomonga", "chap-o'ng", "tasodifiy"], correct: 0 },
          { q: "Bir katak 20 piksel bo'lsa, har qadamda necha qadam yuramiz?", options: ["20", "1", "10", "100"], correct: 0 },
        ],
      },
      {
        title: "Snake: olma va o'suvchi dum (klonlar)",
        kind: "lesson",
        goals: ["Olmani tasodifiy joyda paydo qilish", "Dumni klonlar bilan yasash", "Uzunlik o'zgaruvchisi bilan dumni boshqarish"],
        visual: "game",
        visualPreset: "snake",
        slides: [
          { emoji: "🍎", title: "Olma", points: ["Olma sprite'i tasodifiy katakda paydo bo'ladi.", "Katakka tekislash uchun: x = (−11 dan 11 gacha tasodifiy son) × 20.", "Bosh olmaga tegsa: Ball +1, Uzunlik +1, olma yangi joyga."], code: "Olma:\n🏁 bayroq bosilganda\nx: ((−11 dan 11 gacha tasodifiy) × 20)\ny: ((−8 dan 8 gacha tasodifiy) × 20) ga bor\ndoim takrorla\n  agar <Bosh ga tegdimi?> bo'lsa\n    Ball ni 1 ga o'zgartir\n    Uzunlik ni 1 ga o'zgartir\n    (yangi tasodifiy joyga bor)" },
          { emoji: "🧬", title: "Dum — klonlar sehri", points: ["Bosh har qadamda o'z joyida **klon qoldiradi**.", "Klon «Uzunlik × 0.15» soniya turib, keyin **o'chadi**.", "Shunday qilib dum doim bosh ortidan ergashadi!"], code: "Bosh — doim takrorla ichida:\n  o'zimning klonimni yarat\n  20 qadam yur\n  0.15 soniya kut\n\nklon sifatida boshlanganda\n  kostyumni Dum ga almashtir\n  (Uzunlik × 0.15) soniya kut\n  bu klonni o'chir" },
          { emoji: "📏", title: "Uzunlik o'zgaruvchisi", points: ["Boshida: Uzunlik = 3.", "Olma yeganda: Uzunlik +1 → klonlar uzoqroq yashaydi → dum uzun.", "Sahnada Ball ko'rsatkichini qoldiring, Uzunlik'ni yashiring."] },
          { emoji: "🎨", title: "Dum kostyumi", points: ["Bosh sprite'iga 2-kostyum: **Dum** (to'qroq yashil).", "Klon darhol «Dum» kostyumiga o'tadi — bosh va dum farqlanadi.", "Dum rangi 3-darsda to'qnashuvni aniqlash uchun kerak bo'ladi!"] },
        ],
        practice: [
          "Olma sprite'ini qo'shing va katakka tekislangan tasodifiy joyga qo'ying.",
          "Ball va Uzunlik o'zgaruvchilarini yarating, boshida 0 va 3 ga o'rnating.",
          "Bosh olmaga tegsa: Ball +1, Uzunlik +1, olma yangi joyga o'tsin.",
          "Bosh har qadamda klon qoldirsin; klon «Dum» kostyumida bo'lib, Uzunlik × 0.15 soniyadan keyin o'chsin.",
          "5 ta olma yeb, dum uzayayotganini tekshiring.",
        ],
        homework: "Olma yeyilganda tovush («Chomp») qo'shing va har 5 ball'da ilon biroz tezlashsin (kutish vaqtini kamaytiring).",
        quiz: [
          { q: "Snake dumi nimalardan yasaladi?", options: ["Bosh qoldirgan klonlardan", "Olma kostyumlaridan", "Fon rasmidan", "Tovushlardan"], correct: 0 },
          { q: "Dum nega uzayadi?", options: ["Uzunlik oshgani uchun klonlar uzoqroq yashaydi", "Klonlar kattalashadi", "Fon o'zgaradi", "Tezlik kamayadi"], correct: 0 },
          { q: "Natija: klon necha soniya yashaydi?", code: "Uzunlik = 4\nklon: (Uzunlik × 0.15) soniya kut → o'chir", options: ["0.6", "4", "0.15", "4.15"], correct: 0 },
          { q: "Olma katakka tekis turishi uchun x qanday hisoblanadi?", options: ["Tasodifiy son × 20", "Tasodifiy son + 20", "Faqat 0", "x = y"], correct: 0 },
          { q: "Olma yeyilganda qaysi o'zgaruvchilar oshadi?", options: ["Ball va Uzunlik", "Faqat Vaqt", "Hayot", "Hech biri"], correct: 0 },
          { q: "Bosh va dumni qanday farqlaymiz?", options: ["Klon boshqa (Dum) kostyumiga o'tadi", "Farqlab bo'lmaydi", "Dum ko'rinmaydi", "Tovush bilan"], correct: 0 },
        ],
      },
      {
        title: "Snake: Game Over, ball va tezlik",
        kind: "project",
        goals: ["Devor va dumga to'qnashuvni aniqlash", "Game Over ekrani va Rekord", "O'yinni to'liq yakunlash va sinash"],
        visual: "game",
        visualPreset: "snake",
        slides: [
          { emoji: "💥", title: "To'qnashuv", points: ["Devor: «**chekkaga tegdimi?**».", "Dum: «**Dum rangiga tegdimi?**» (to'q yashil).", "Ikkalasi «yoki» bilan birlashtiriladi."], code: "agar <<chekkaga tegdimi?> yoki <(to'q yashil) rangiga tegdimi?>> bo'lsa\n  Game Over xabarini yubor\n  hammasini to'xtat" },
          { emoji: "🏁", title: "Game Over ekrani", points: ["Fon: «O'yin tugadi!».", "«Balingiz: » + Ball — birlashtir bloki bilan.", "Agar Ball > Rekord → Rekord = Ball."] },
          { emoji: "⚡", title: "Qiyinlik", points: ["O'zgaruvchi «Kutish» = 0.15.", "Har olmada: «Kutish ni −0.005 ga o'zgartir» (0.06 dan kam bo'lmasin).", "Ilon tobora tezlashadi — qiziqroq!"] },
          { emoji: "✨", title: "Bezash", points: ["Start ekrani: «Snake — probel bilan boshlang».", "Fon musiqasi, olma yeyish tovushi.", "Tilla olma: 5 ball (tasodifiy chiqadi)."] },
        ],
        practice: [
          "Devor va dum to'qnashuvini «yoki» bilan yozing.",
          "Start va Game Over fonlarini chizing, xabarlar bilan ulang.",
          "Game Over'da ball va rekordni ko'rsating.",
          "Tezlashishni qo'shing va 3 marta o'ynab sinang.",
          "Sherigingiz o'yiningizni o'ynasin — 1 ta xato topsa, tuzating.",
        ],
        homework: "Snake'ni «Share» qiling (ota-ona ruxsati bilan) va havolani saqlang. Qo'shimcha: devorlardan o'tib, qarama-qarshi tomondan chiqadigan «Portal rejimi» qo'shing.",
        rubric: ["Ilon strelkalar bilan boshqariladi, orqaga burilmaydi", "Olma tasodifiy katakda chiqadi, dum uzayadi", "Devor/dum to'qnashuvi → Game Over", "Ball va Rekord ko'rsatiladi", "Start ekrani va tezlashish bor"],
        quiz: [
          { q: "Devorga tegishni qaysi blok aniqlaydi?", options: ["chekkaga tegdimi?", "sichqoncha bosildimi?", "tasodifiy son", "birlashtir"], correct: 0 },
          { q: "Dumga tegishni qanday aniqlaymiz?", options: ["«… rangiga tegdimi?» — dum rangi bilan", "«probel bosildimi?»", "«x pozitsiyasi»", "Aniqlab bo'lmaydi"], correct: 0 },
          { q: "Ikki shartdan biri bajarilsa o'yin tugashi uchun?", options: ["yoki", "va", "emas", "birlashtir"], correct: 0 },
          { q: "Ilon tezlashishi uchun?", options: ["Kutish vaqtini kamaytiramiz", "Kutish vaqtini oshiramiz", "Sprite'ni kattalashtiramiz", "Fonni almashtiramiz"], correct: 0 },
          { q: "Natija: Rekord nechaga teng bo'ladi?", code: "Rekord = 12, Ball = 15\nagar <Ball > Rekord> bo'lsa → Rekord ni Ball ga o'rnat", options: ["15", "12", "27", "3"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Google Dino — ayiq bilan 🐻",
    days: [
      {
        title: "Dino: ayiq sprite, yurish animatsiyasi va yer",
        kind: "lesson",
        goals: ["Google Dino o'yinining g'oyasini tushunish", "Bear-walking sprite bilan yurish animatsiyasi", "Harakatlanayotgan yer effektini yaratish"],
        visual: "game",
        visualPreset: "dino",
        slides: [
          { emoji: "🦖", title: "Google Dino", points: ["Chrome'da internet uzilganda chiqadigan o'yin!", "Qahramon joyida yuradi, to'siqlar unga qarab keladi.", "Vazifa: **sakrab o'tish**. Qancha uzoq yashasangiz — shuncha ko'p ball.", "Bizda dinozavr o'rniga — **ayiq** 🐻."] },
          { emoji: "🐻", title: "Ayiq sprite", points: ["Sprite kutubxonasi → **Bear-walking** (Hayvonlar bo'limi).", "Unda 8 ta kostyum bor — yurish animatsiyasi tayyor!", "O'lcham: 60%. Joyi: x = −160, y = −100."], code: "🏁 bayroq bosilganda\nx: −160 y: −100 ga bor\no'lchamni 60 % ga o'rnat\ndoim takrorla\n  keyingi kostyum\n  0.08 soniya kut" },
          { emoji: "🏞️", title: "Harakatdagi dunyo", points: ["Ayiq **joyida** yuradi — atrof harakatlanadi.", "Yer sprite'i: uzun jigarrang chiziq, chapga siljiydi.", "x < −240 bo'lsa → x = 240 (qayta boshidan) — cheksiz yer!"] },
          { emoji: "☁️", title: "Parallaks (qo'shimcha)", points: ["Bulutlar sekin, yer tez harakatlansa — **chuqurlik** hissi paydo bo'ladi.", "Bu usul haqiqiy o'yinlarda ham ishlatiladi."] },
        ],
        practice: [
          "Ko'rgazmadagi ayiqli Dino'ni o'ynang: nima harakatlanadi, nima joyida turadi?",
          "Yangi loyiha `Dino_Ism`: Bear-walking sprite'ini qo'shing.",
          "Yurish animatsiyasini yozing (keyingi kostyum + 0.08 kut).",
          "Yer sprite'ini chizing va chapga cheksiz siljiydigan qiling.",
          "2 ta bulut qo'shing — yerdan sekinroq harakatlansin.",
        ],
        homework: "Fonni chiroyli qiling: osmon gradienti, quyosh, uzoqdagi tog'lar. Ayiq o'lchamini va animatsiya tezligini o'zingizga moslang.",
        quiz: [
          { q: "Dino o'yinida qahramon qanday harakatlanadi?", options: ["Joyida yuradi, to'siqlar unga keladi", "Butun sahna bo'ylab yuguradi", "Umuman harakatlanmaydi", "Faqat uchadi"], correct: 0 },
          { q: "Ayiq sprite'ining kutubxonadagi nomi?", options: ["Bear-walking", "Cat", "Dinosaur1", "Ball"], correct: 0 },
          { q: "Yurish animatsiyasi uchun qaysi bloklar?", options: ["keyingi kostyum + kut", "10 qadam yur", "tovushni chal", "fonni almashtir"], correct: 0 },
          { q: "Yer cheksiz ko'rinishi uchun?", options: ["Chapga siljib, chetdan chiqsa o'ngdan qayta boshlaydi", "Juda uzun chizamiz", "Fon rasmini almashtiramiz", "Yer kerak emas"], correct: 0 },
          { q: "Bulutlar yerdan sekin harakatlansa nima hissi paydo bo'ladi?", options: ["Chuqurlik (parallaks)", "Tezlik yo'qoladi", "Rang o'zgaradi", "O'yin to'xtaydi"], correct: 0 },
        ],
      },
      {
        title: "Dino: sakrash fizikasi va to'siqlar",
        kind: "lesson",
        goals: ["«y tezligi» va gravitatsiya bilan haqiqiy sakrash", "Faqat yerda turganda sakrash", "To'siqlarni klonlar bilan yaratish"],
        visual: "game",
        visualPreset: "dino",
        slides: [
          { emoji: "🦘", title: "Sakrash", points: ["Probel bosilganda **va** ayiq yerda bo'lsa: «y tezligi» = 14.", "Har qadamda: y += «y tezligi», «y tezligi» −= 1.", "Yerga yetsa: y = −100, «y tezligi» = 0."], code: "doim takrorla\n  agar <<probel bosildimi?> va <y = −100>> bo'lsa\n    y tezligi ni 14 ga o'rnat\n  y ni (y tezligi) ga o'zgartir\n  y tezligi ni −1 ga o'zgartir\n  agar <y < −100> bo'lsa\n    y ni −100 ga o'rnat\n    y tezligi ni 0 ga o'rnat" },
          { emoji: "🌵", title: "To'siq sprite", points: ["Kaktus yoki tosh chizing (yoki kutubxonadan).", "Asl sprite yashirin, **klonlar** yaratadi.", "Klon: x = 240 dan boshlab chapga «Tezlik» bilan siljiydi, x < −240 bo'lsa o'chadi."], code: "doim takrorla\n  o'zimning klonimni yarat\n  (1 dan 2.5 gacha tasodifiy son) soniya kut\n\nklon sifatida boshlanganda\nx: 240 y: −110 ga bor\nko'rsat\nx < −240 bo'lguncha takrorla\n  x ni (0 − Tezlik) ga o'zgartir\nbu klonni o'chir" },
          { emoji: "🎲", title: "Tasodif", points: ["To'siqlar orasidagi vaqt tasodifiy — bashorat qilib bo'lmaydi!", "2 xil kostyum: kichik kaktus va katta tosh — «tasodifiy kostyum»."] },
          { emoji: "🧪", title: "Sinash", points: ["Sakrash balandligi yetarlimi? (14 → 12 → 16 sinab ko'ring)", "Havoda ikki marta sakrab bo'lmasligini tekshiring."] },
        ],
        practice: [
          "«y tezligi» o'zgaruvchisini yarating va sakrash skriptini yozing.",
          "Ayiq faqat yerda turganda sakrasin («va» sharti).",
          "To'siq sprite'ini chizib, klonlar bilan o'ngdan chapga harakatlantiring.",
          "To'siqlar orasiga tasodifiy vaqt qo'ying.",
          "Sakrash balandligi va to'siq tezligini sinab, qulay qiymatlarni toping.",
        ],
        homework: "Uchuvchi to'siq (qush 🐦) qo'shing — u balandroqdan uchadi, ostidan o'tish uchun sakramaslik kerak! Qo'shimcha: pastga egilish (↓) kostyumi.",
        quiz: [
          { q: "Gravitatsiyani qanday yasaymiz?", options: ["Har qadamda «y tezligi» ni kamaytiramiz", "y ni har doim 0 qilamiz", "Sprite'ni yashiramiz", "x ni oshiramiz"], correct: 0 },
          { q: "Havoda qayta sakramaslik uchun qaysi shart?", options: ["probel bosildimi VA yerdami", "probel bosildimi YOKI yerdami", "faqat probel", "shart kerak emas"], correct: 0 },
          { q: "Natija: 2 qadamdan keyin y nechaga teng?", code: "y = −100, y tezligi = 14\nhar qadamda: y ni (y tezligi) ga o'zgartir,\n            y tezligi ni −1 ga o'zgartir", options: ["−73", "−72", "−86", "−100"], correct: 0 },
          { q: "To'siqlar qayerdan chiqadi?", options: ["O'ngdan (x = 240)", "Chapdan", "Tepadan", "O'rtadan"], correct: 0 },
          { q: "To'siq klonini qachon o'chiramiz?", options: ["Chap chetdan chiqqanda (x < −240)", "Hech qachon", "Paydo bo'lishi bilan", "Ayiq sakraganda"], correct: 0 },
          { q: "To'siqlar orasidagi vaqt nega tasodifiy?", options: ["O'yinni bashorat qilib bo'lmasin", "Tezroq ishlashi uchun", "Majburiy qoida", "Tovush uchun"], correct: 0 },
        ],
      },
      {
        title: "Dino: to'qnashuv, ball, tezlashish va rekord",
        kind: "project",
        goals: ["Ayiq va to'siq to'qnashuvi", "Vaqt bilan o'sadigan ball va tezlik", "Rekord va qayta boshlash"],
        visual: "game",
        visualPreset: "dino",
        slides: [
          { emoji: "💥", title: "To'qnashuv", points: ["Ayiqda: «agar <To'siq ga tegdimi?> bo'lsa → Game Over xabarini yubor».", "Game Over'da: ayiq «xafa» kostyumiga o'tadi, hammasi to'xtaydi."] },
          { emoji: "⭐", title: "Ball", points: ["Ball — **vaqt** bilan o'sadi: har 0.1 soniyada +1.", "Har 100 ballda «Ding!» tovushi — Google Dino'dagidek."], code: "O'yin boshlandi xabari kelganda\nBall ni 0 ga o'rnat\nTezlik ni 6 ga o'rnat\ndoim takrorla\n  Ball ni 1 ga o'zgartir\n  Tezlik ni 0.02 ga o'zgartir\n  0.1 soniya kut" },
          { emoji: "⚡", title: "Tezlashish", points: ["«Tezlik» asta-sekin oshadi — to'siqlar tezroq keladi.", "To'siq klonlari «Tezlik» o'zgaruvchisidan foydalanadi."] },
          { emoji: "🏆", title: "Rekord va qayta o'ynash", points: ["Agar Ball > Rekord → Rekord = Ball.", "Game Over ekranida: «Probel — qayta o'ynash».", "Qayta boshlashda barcha klonlarni o'chirish: «O'yin boshlandi» kelganda → bu klonni o'chir."] },
        ],
        practice: [
          "To'qnashuvni yozing va Game Over xabarini yuboring.",
          "Vaqt bilan o'sadigan Ball va Tezlik'ni qo'shing.",
          "To'siqlar «Tezlik» o'zgaruvchisi bilan harakatlansin.",
          "Rekord va «Probel — qayta o'ynash» ni qo'shing.",
          "Sinfda «Kim eng ko'p ball oladi?» mini-musobaqasi.",
        ],
        homework: "Tun va kun almashinuvi qo'shing: har 500 ballda fon qorong'ilashsin va yana yorishsin. O'yinni Share qiling.",
        rubric: ["Ayiq animatsiya bilan yuradi", "Sakrash gravitatsiya bilan, havoda qayta sakramaydi", "To'siqlar klonlar bilan tasodifiy chiqadi", "To'qnashuv → Game Over, Ball va Rekord", "O'yin tezlashadi va qayta boshlanadi"],
        quiz: [
          { q: "Dino o'yinida ball nimaga bog'liq?", options: ["Qancha vaqt yashaganingizga", "Nechta olma yeganingizga", "Sichqoncha bosishlariga", "Ranglarga"], correct: 0 },
          { q: "O'yin tobora qiyinlashishi uchun?", options: ["Tezlik o'zgaruvchisini asta oshiramiz", "Ayiqni kattalashtiramiz", "Ball'ni kamaytiramiz", "To'siqlarni o'chiramiz"], correct: 0 },
          { q: "Qayta boshlashda eski to'siqlar nima qilinadi?", options: ["Klonlar o'chiriladi", "Qoladi", "Kattalashadi", "Rangi o'zgaradi"], correct: 0 },
          { q: "Natija: 2 soniyadan keyin Ball nechaga teng?", code: "doim takrorla\n  Ball ni 1 ga o'zgartir\n  0.1 soniya kut", options: ["20", "2", "10", "200"], correct: 0 },
          { q: "To'qnashuvni qaysi blok aniqlaydi?", options: ["To'siq ga tegdimi?", "chekkaga tegdimi?", "tasodifiy son", "kut"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Balloon shooter 🎈",
    days: [
      {
        title: "Balloon shooter: nishon va sahna",
        kind: "lesson",
        goals: ["Sichqonchaga ergashuvchi nishon yasash", "Sichqoncha kursorini yashirish g'oyasi", "O'yin sahnasini tayyorlash"],
        visual: "game",
        visualPreset: "balloon",
        slides: [
          { emoji: "🎯", title: "O'yin g'oyasi", points: ["Pastdan rang-barang **sharlar** ko'tariladi.", "Sichqoncha bilan **nishonga olib** bosasiz — shar yoriladi!", "30 soniyada eng ko'p shar yoring."] },
          { emoji: "➕", title: "Nishon sprite", points: ["🖌️ Paint'da nishon chizing: aylana + ikki chiziq (qizil).", "Markazini to'g'ri qo'ying — **kostyum markazi** nishon o'rtasida bo'lsin!", "Nishon doim sichqonchaga ergashadi."], code: "🏁 bayroq bosilganda\nqatlamni eng oldinga o'tkaz\ndoim takrorla\n  sichqoncha kursori ga bor" },
          { emoji: "🌤️", title: "Sahna", points: ["Fon: osmon (kutubxonadan «Blue Sky» yoki o'zingiz chizing).", "Pastda o'tlar yoki shahar — sharlar shu yerdan chiqadi.", "Ball va Vaqt o'zgaruvchilari sahnada ko'rinsin."] },
          { emoji: "🧱", title: "Qatlamlar", points: ["Nishon har doim sharlar **ustida** bo'lishi kerak.", "«**qatlamni eng oldinga o'tkaz**» bloki (Ko'rinish bo'limi)."] },
        ],
        practice: [
          "Ko'rgazmadagi Balloon shooter'ni o'ynang — tilla shar va bombani toping!",
          "Yangi loyiha `Balloon_Ism`, osmon fonini qo'shing.",
          "Nishon sprite'ini chizing, markazini to'g'rilang.",
          "Nishon doim sichqoncha kursoriga ergashsin va eng oldinda tursin.",
          "Ball va Vaqt o'zgaruvchilarini yarating.",
        ],
        homework: "Shar sprite'ini tayyorlang: kutubxonadagi «Balloon1» ning 3 ta kostyumi yoki o'zingiz chizgan shar. Yorilish tovushini (Pop) sprite'ga qo'shing.",
        quiz: [
          { q: "Nishon sichqonchaga ergashishi uchun blok?", options: ["sichqoncha kursori ga bor", "10 qadam yur", "istalgan joyga bor", "chekkaga tegsa, qayt"], correct: 0 },
          { q: "Nishon sharlar ustida ko'rinishi uchun?", options: ["qatlamni eng oldinga o'tkaz", "yashir", "o'lchamni 10 % qil", "fonni almashtir"], correct: 0 },
          { q: "Kostyum markazi nega muhim?", options: ["Nishon aniq sichqoncha nuqtasida bo'lishi uchun", "Rang uchun", "Tovush uchun", "Muhim emas"], correct: 0 },
          { q: "Balloon shooter'da sharlar qayerdan chiqadi?", options: ["Pastdan", "Tepadan", "Chapdan", "Markazdan"], correct: 0 },
          { q: "Nishon qaysi skript ichida sichqonchaga boradi?", options: ["doim takrorla", "10 marta takrorla", "agar", "klon sifatida boshlanganda"], correct: 0 },
        ],
      },
      {
        title: "Balloon shooter: shar klonlari va yorish",
        kind: "lesson",
        goals: ["Sharlarni klonlar bilan pastdan chiqarish", "Tasodifiy x, tezlik va rang", "Bosilganda yorish: tovush, ball, o'chirish"],
        visual: "game",
        visualPreset: "balloon",
        slides: [
          { emoji: "🎈", title: "Shar klonlari", points: ["Asl shar yashirin, har 0.6 soniyada klon yaratadi.", "Klon: tasodifiy x, y = −180, tasodifiy rang.", "Tepaga uchadi, tepadan chiqsa — o'chadi."], code: "🏁 bayroq bosilganda\nyashir\ndoim takrorla\n  o'zimning klonimni yarat\n  0.6 soniya kut\n\nklon sifatida boshlanganda\nx: (−220 dan 220 gacha tasodifiy) y: −180 ga bor\nrang effektini (0 dan 200 gacha tasodifiy) ga o'rnat\nko'rsat\ny > 190 bo'lguncha takrorla\n  y ni 3 ga o'zgartir\nbu klonni o'chir" },
          { emoji: "💥", title: "Yorish", points: ["«**bu sprite bosilganda**» — klonlarda ham ishlaydi!", "Pop tovushi, Ball +1, «bu klonni o'chir».", "Qo'shimcha: yorilish kostyumi (portlash) 0.1 soniya."], code: "bu sprite bosilganda\nPop tovushini chal\nBall ni 1 ga o'zgartir\nbu klonni o'chir" },
          { emoji: "🎚️", title: "Tasodifiy tezlik", points: ["O'zgaruvchi «**faqat shu sprite uchun**» — har klonda o'z qiymati!", "Klon: «mening tezligim» = 2 dan 5 gacha tasodifiy son.", "y ni «mening tezligim» ga o'zgartir — har shar boshqa tezlikda."] },
          { emoji: "🤔", title: "Muammo: nishon bosishni to'sadi!", points: ["Nishon sharlar ustida bo'lsa, bosish nishonga tushadi.", "Yechim: sharda «agar <sichqoncha bosildimi?> va <sichqoncha kursoriga tegdimi?> bo'lsa»."] },
        ],
        practice: [
          "Asl sharni yashirib, har 0.6 soniyada klon yaratadigan qiling.",
          "Klonlar pastdan tasodifiy x va rang bilan chiqib, tepaga uchsin.",
          "Har klonga «faqat shu sprite uchun» tezlik bering.",
          "Shar bosilganda: Pop, Ball +1, klon o'chsin (nishon muammosini ham hal qiling).",
          "1 daqiqa o'ynab, sharlar ko'p/kamligini sozlang.",
        ],
        homework: "Yorilganda sharning o'rnida qisqa «+1» yozuvi chiqsin (alohida sprite yoki kostyum). Shar kostyumlarini 3 xil qiling.",
        quiz: [
          { q: "Har bir shar o'z tezligiga ega bo'lishi uchun o'zgaruvchi qanday yaratiladi?", options: ["«faqat shu sprite uchun»", "«barcha sprite'lar uchun»", "Ro'yxat sifatida", "Yaratib bo'lmaydi"], correct: 0 },
          { q: "Shar tepadan chiqib ketganda nima qilamiz?", options: ["bu klonni o'chir", "Hech narsa", "Ball +1", "O'yinni tugatamiz"], correct: 0 },
          { q: "«bu sprite bosilganda» klonlarda ishlaydimi?", options: ["Ha, har klon alohida", "Yo'q, faqat aslida", "Faqat birinchi klonda", "Faqat sahnada"], correct: 0 },
          { q: "Sharlar turli rangda bo'lishi uchun?", options: ["rang effektini tasodifiy songa o'rnatamiz", "10 ta sprite chizamiz", "Fonni almashtiramiz", "Tovush qo'shamiz"], correct: 0 },
          { q: "Natija: 3 soniyada taxminan nechta shar chiqadi?", code: "doim takrorla\n  o'zimning klonimni yarat\n  0.6 soniya kut", options: ["5", "3", "18", "1"], correct: 0 },
          { q: "Yorish paytidagi to'g'ri tartib?", options: ["Tovush → Ball +1 → klonni o'chir", "Klonni o'chir → tovush → Ball", "Faqat Ball", "Fon almashtirish"], correct: 0 },
        ],
      },
      {
        title: "Balloon shooter: taymer, maxsus sharlar va Game Over",
        kind: "project",
        goals: ["30 soniyalik taymer", "Tilla shar (+5) va bomba (−3)", "Game Over ekrani va rekord"],
        visual: "game",
        visualPreset: "balloon",
        slides: [
          { emoji: "⏱️", title: "Taymer", points: ["Vaqt = 30, har soniyada −1.", "Vaqt = 0 → «Game Over» xabari."], code: "Sahna:\n🏁 bayroq bosilganda\nVaqt ni 30 ga o'rnat\nVaqt = 0 bo'lguncha takrorla\n  1 soniya kut\n  Vaqt ni −1 ga o'zgartir\nGame Over xabarini yubor" },
          { emoji: "🌟", title: "Maxsus sharlar", points: ["Klon yaratilganda: «Tur» = 1 dan 10 gacha tasodifiy son.", "Tur = 1 → **tilla** kostyum, +5 ball.", "Tur = 2 → **bomba** 💣, −3 ball!", "Boshqa — oddiy shar, +1."] },
          { emoji: "📈", title: "Qiyinlik", points: ["Vaqt kamaygan sari sharlar tezlashsin: tezlik + (30 − Vaqt) / 10.", "Oxirgi 10 soniyada klonlar tezroq yaratilsin."] },
          { emoji: "🏁", title: "Yakun", points: ["Game Over'da: barcha klonlar o'chsin, nishon yashirinsin.", "«Balingiz: … Rekord: …» ekrani."] },
        ],
        practice: [
          "Sahnada 30 soniyalik taymer yozing.",
          "Tasodifiy «Tur» bilan tilla shar va bomba qo'shing.",
          "Qiyinlik: vaqt o'tgani sari sharlar tezlashsin.",
          "Game Over ekrani, rekord va qayta o'ynash.",
          "Sinfdoshlar bilan «30 soniya challenge».",
        ],
        homework: "Kombo tizimi qo'shing: ketma-ket 5 ta shar xatosiz yorilsa — bonus +10. O'yinni Share qiling.",
        rubric: ["Nishon sichqonchaga ergashadi", "Sharlar klonlar bilan tasodifiy chiqadi", "Yorish: tovush, ball, o'chirish", "Tilla shar va bomba ishlaydi", "30 s taymer, Game Over va Rekord"],
        quiz: [
          { q: "Tur = 1 dan 10 gacha tasodifiy bo'lsa, tilla shar (Tur = 1) chiqish ehtimoli?", options: ["10 tadan 1", "2 tadan 1", "Har doim", "Hech qachon"], correct: 0 },
          { q: "Bomba yorilsa nima bo'ladi?", options: ["Ball kamayadi (−3)", "Ball +5", "Vaqt qo'shiladi", "Hech narsa"], correct: 0 },
          { q: "Taymer tugaganda qaysi xabar yuboriladi?", options: ["Game Over", "O'yin boshlandi", "Sakra", "Pop"], correct: 0 },
          { q: "Natija: Ball nechaga teng?", code: "Ball = 10\n2 ta oddiy shar (+1), 1 ta tilla (+5), 1 ta bomba (−3)", options: ["14", "18", "11", "7"], correct: 0 },
          { q: "Taymer qaysi blok bilan yoziladi?", options: ["… bo'lguncha takrorla + 1 soniya kut", "doim takrorla faqat", "sprite bosilganda", "klon sifatida boshlanganda"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Mole strike 🔨 va o'yinlar festivali",
    days: [
      {
        title: "Mole strike: teshiklar va bolg'a",
        kind: "lesson",
        goals: ["9 teshikli sahna chizish", "Bolg'a sprite'i sichqonchaga ergashadi va uradi", "Teshik koordinatalarini ro'yxatda saqlash"],
        visual: "game",
        visualPreset: "mole",
        slides: [
          { emoji: "🐹", title: "O'yin g'oyasi", points: ["9 ta teshikdan **ko'rsichqon** tasodifiy chiqadi.", "U yashiringuncha **bolg'a** bilan urib qolasiz!", "30 soniyada eng ko'p ko'rsichqon — g'olib."] },
          { emoji: "🕳️", title: "Sahna", points: ["Fon: yashil maydon, 3 × 3 = 9 ta jigarrang teshik.", "Teshiklarni tekis joylang: x = −130, 0, 130; y = 90, −10, −110."] },
          { emoji: "📋", title: "Ro'yxat (List)", points: ["**Ro'yxat** — bitta o'zgaruvchida ko'p qiymat.", "«TeshikX» ro'yxati: −130, 0, 130, −130, 0, 130, −130, 0, 130.", "«TeshikY» ro'yxati: 90, 90, 90, −10, −10, −10, −110, −110, −110.", "«**TeshikX ning 5-elementi**» → 0 (markaziy teshik)."], code: "🏁 bayroq bosilganda\nTeshikX dan hammasini o'chir\nTeshikY dan hammasini o'chir\n−130 ni TeshikX ga qo'sh   90 ni TeshikY ga qo'sh\n   0 ni TeshikX ga qo'sh   90 ni TeshikY ga qo'sh\n ... (9 ta juftlik)" },
          { emoji: "🔨", title: "Bolg'a", points: ["Doim sichqoncha kursoriga boradi.", "Sichqoncha bosilganda: «urish» kostyumi 0.1 soniya, keyin qaytadi.", "Qatlam: eng oldinda."] },
        ],
        practice: [
          "Ko'rgazmadagi Mole strike'ni o'ynang — ko'rsichqon qanchalik tez yashirinadi?",
          "Yangi loyiha `Mole_Ism`: 9 teshikli fonni chizing.",
          "TeshikX va TeshikY ro'yxatlarini yarating va to'ldiring.",
          "Bolg'a sprite'ini chizing (2 kostyum: tik va urish).",
          "Bolg'a sichqonchaga ergashsin va bosilganda ursin.",
        ],
        homework: "Ro'yxatlar bilan mashq: «Mevalar» ro'yxatini tuzing (5 ta meva), sprite bosilganda tasodifiy mevani aytsin: «Mevalar ning (1 dan 5 gacha tasodifiy)-elementi».",
        quiz: [
          { q: "Ro'yxat (List) nima?", options: ["Bitta o'zgaruvchida ko'p qiymat", "Bitta son", "Sprite", "Fon"], correct: 0 },
          { q: "Natija nima?", code: "TeshikX = [−130, 0, 130, −130, 0, 130, ...]\n(TeshikX ning 3-elementi)", options: ["130", "0", "−130", "3"], correct: 0 },
          { q: "3 × 3 maydonda nechta teshik?", options: ["9", "6", "3", "12"], correct: 0 },
          { q: "Bolg'a urishini qanday ko'rsatamiz?", options: ["«urish» kostyumiga o'tib, qaytamiz", "Sprite'ni o'chiramiz", "Fonni almashtiramiz", "Ball qo'shamiz"], correct: 0 },
          { q: "Nega koordinatalarni ro'yxatda saqlaymiz?", options: ["Tasodifiy raqam bilan kerakli teshikni oson topish uchun", "Chiroyli bo'lishi uchun", "Majburiy qoida", "Tovush uchun"], correct: 0 },
        ],
      },
      {
        title: "Mole strike: ko'rsichqon, urish va ball",
        kind: "lesson",
        goals: ["Ko'rsichqonni tasodifiy teshikdan chiqarish", "Vaqt o'tsa yashirish, urilsa ball", "Qiyinlikni ballga bog'lash"],
        visual: "game",
        visualPreset: "mole",
        slides: [
          { emoji: "🎲", title: "Tasodifiy teshik", points: ["n = 1 dan 9 gacha tasodifiy son.", "x: «TeshikX ning n-elementi», y: «TeshikY ning n-elementi».", "Ko'rsat → kut → yashir → yana tasodifiy kut."], code: "🏁 bayroq bosilganda\nyashir\ndoim takrorla\n  (0.3 dan 1 gacha tasodifiy) soniya kut\n  n ni (1 dan 9 gacha tasodifiy son) ga o'rnat\n  x: (TeshikX ning n-elementi)\n  y: (TeshikY ning n-elementi) ga bor\n  ko'rsat\n  (Turish vaqti) soniya kut\n  yashir" },
          { emoji: "🔨", title: "Urish", points: ["Ko'rsichqon bosilganda: «Bonk» tovushi, Ball +1, «urilgan» kostyum, yashir.", "Muammo: bolg'a ko'rsichqon ustida bo'lsa bosish bolg'aga tushadi!", "Yechim: ko'rsichqonda «agar <sichqoncha bosildimi?> va <Bolg'a ga tegdimi?> bo'lsa»."] },
          { emoji: "📈", title: "Qiyinlik", points: ["«Turish vaqti» = 1.1 soniya.", "Har urishda: «Turish vaqti ni −0.03 ga o'zgartir» (0.45 dan kam emas).", "Qancha ko'p ursangiz — shuncha tez yashirinadi!"] },
          { emoji: "🚫", title: "Xato bosish", points: ["Qo'shimcha: bo'sh joyga bossangiz — Ball −1.", "Bu o'yinchini diqqatli bo'lishga majbur qiladi."] },
        ],
        practice: [
          "Ko'rsichqon sprite'ini qo'shing (kutubxona yoki o'zingiz chizing).",
          "Tasodifiy teshikdan chiqib-yashiriladigan skriptni yozing.",
          "Urilganda: tovush, Ball +1, yashirish.",
          "«Turish vaqti» bilan qiyinlikni qo'shing.",
          "Sherigingiz bilan navbat bilan o'ynab, qiyinlikni sozlang.",
        ],
        homework: "Oltin ko'rsichqon qo'shing: 10 tadan 1 marta chiqadi, +5 ball. Qo'shimcha: bir vaqtda 2 ta ko'rsichqon (klonlar bilan).",
        quiz: [
          { q: "Ko'rsichqon qaysi teshikdan chiqishini nima belgilaydi?", options: ["1 dan 9 gacha tasodifiy son va ro'yxat", "Har doim 1-teshik", "Sichqoncha", "Fon"], correct: 0 },
          { q: "O'yin qiyinlashishi uchun?", options: ["Turish vaqtini kamaytiramiz", "Turish vaqtini oshiramiz", "Teshiklarni kattalashtiramiz", "Ball'ni o'chiramiz"], correct: 0 },
          { q: "Natija: 5 ta urishdan keyin Turish vaqti?", code: "Turish vaqti = 1.1\nhar urishda: −0.03", options: ["0.95", "1.05", "0.8", "1.25"], correct: 0 },
          { q: "Bolg'a bosishni to'smasligi uchun qaysi shart?", options: ["sichqoncha bosildimi VA Bolg'a ga tegdimi", "faqat probel", "chekkaga tegdimi", "x = 0"], correct: 0 },
          { q: "Ko'rsichqon ko'rinib turgandan keyin nima qiladi?", options: ["Turish vaqti o'tgach yashirinadi", "Abadiy qoladi", "Sahnadan uchib ketadi", "Kattalashadi"], correct: 0 },
          { q: "Urilganda qaysi tartib to'g'ri?", options: ["Tovush → Ball +1 → yashir", "Yashir → hech narsa", "Ball −1", "Fonni almashtir"], correct: 0 },
        ],
      },
      {
        title: "Mole strike yakuni va «Scratch o'yinlar festivali» 🎪",
        kind: "event",
        goals: ["Mole strike'ni taymer va Game Over bilan yakunlash", "4 ta o'yinni sinfga namoyish qilish", "Boshqalarning o'yinlarini o'ynab, baholash"],
        visual: "game",
        visualPreset: "mole",
        slides: [
          { emoji: "⏱️", title: "Mole strike yakuni", points: ["30 soniyalik taymer (Balloon shooter'dagidek).", "Game Over: «Balingiz: … Rekord: …».", "Start ekrani va fon musiqasi."] },
          { emoji: "🎪", title: "O'yinlar festivali!", points: ["Har kim **4 ta o'yinini** ko'rsatadi: Snake, Dino, Balloon shooter, Mole strike.", "Sinfdoshlar kompyuterma-kompyuter aylanib o'ynaydi.", "Har o'yin uchun «⭐ 1–5» baholash varag'i."] },
          { emoji: "🏅", title: "Nominatsiyalar", points: ["🐍 Eng yaxshi Snake", "🐻 Eng chiroyli Dino", "🎈 Eng qiziqarli Balloon shooter", "🔨 Eng qiyin Mole strike", "💡 Eng ijodiy qo'shimcha (o'yinga o'zi qo'shgan yangilik)"] },
          { emoji: "🧠", title: "Nimalarni o'rgandik?", points: ["Klonlar, ro'yxatlar, tasodif, gravitatsiya, xabarlar, taymer, rekord.", "Bular — haqiqiy o'yin dasturchilari ishlatadigan g'oyalar!", "Keyingi oyda — veb-saytlar 🌐, o'yinlaringizni u yerga ham qo'yamiz."] },
        ],
        practice: [
          "Mole strike'ga taymer, Game Over va Rekord qo'shing (20 daqiqa).",
          "4 ta o'yinni ham oxirgi marta tekshiring va Share qiling.",
          "Festival: sinfdoshlarning o'yinlarini o'ynab, baholash varag'ini to'ldiring.",
          "Har kim 1 daqiqada o'z sevimli o'yini va unga qo'shgan yangiligini gapiradi.",
          "Nominatsiyalar bo'yicha ovoz berish va taqdirlash 🏆.",
        ],
        homework: "4 ta o'yiningiz havolalarini daftarga yozing — 5-oyda portfolio saytingizning «Mening o'yinlarim» bo'limiga qo'yamiz!",
        rubric: ["Mole strike: taymer, Game Over, Rekord", "4 ta o'yin ishlaydi va Share qilingan", "Kamida bitta o'yinda o'zining qo'shimchasi bor", "Taqdimotda qaysi bloklarni ishlatganini tushuntiradi", "Boshqalarni hurmat bilan baholaydi"],
        quiz: [
          { q: "4-oyda qaysi o'yinlarni yaratdik?", options: ["Snake, Dino, Balloon shooter, Mole strike", "Tetris, Mario, Pacman, Chess", "Faqat Snake", "Minecraft"], correct: 0 },
          { q: "Qaysi o'yinlarda klonlar asosiy rol o'ynadi?", options: ["Snake (dum) va Balloon shooter (sharlar)", "Faqat Mole strike", "Hech birida", "Faqat Start ekranida"], correct: 0 },
          { q: "Mole strike'da teshik koordinatalari nimada saqlanadi?", options: ["Ro'yxatlarda (TeshikX, TeshikY)", "Fonda", "Tovushda", "Kostyumda"], correct: 0 },
          { q: "Dino'dagi sakrash qaysi tushunchaga asoslangan?", options: ["Gravitatsiya (y tezligi)", "Klon", "Ro'yxat", "Rang effekti"], correct: 0 },
          { q: "O'yinni boshqalarga ko'rsatish uchun Scratch'da?", options: ["Share tugmasi", "Delete", "Stop", "Undo"], correct: 0 },
        ],
      },
    ],
  },
];
