import type { WeekDraft } from "./types";

// 5-OY: WEB DASTURLASH (HTML/CSS)
export const month5: WeekDraft[] = [
  {
    title: "HTML asoslari",
    days: [
      {
        title: "HTML asoslari (h1, p, img, a)",
        kind: "lesson",
        goals: ["Veb-sahifa qanday ishlashini tushunish", "HTML teg tushunchasi", "h1, p, img, a teglarini ishlatish"],
        visual: "code",
        visualPreset: "html",
        slides: [
          { emoji: "🌐", title: "Veb-sahifa nima?", points: ["Brauzerda (Chrome, Edge) ochiladigan har bir sahifa — **veb-sahifa**.", "U **HTML** tilida yozilgan.", "HTML — sahifa **skeleti**: sarlavha, matn, rasm, havola."] },
          { emoji: "🏷️", title: "Teg (tag) nima?", points: ["Teg — burchakli qavs ichidagi so'z: `<p>`.", "Ko'pchilik teglar **juft**: ochiluvchi `<p>` va yopiluvchi `</p>`.", "Yopiluvchi tegda **/** belgisi bor!"], code: "<p>Salom, dunyo!</p>" },
          { emoji: "🔠", title: "Sarlavha va matn", points: ["`<h1>` — eng katta sarlavha, `<h2>`…`<h6>` — kichikroq.", "`<p>` — xatboshi (paragraf).", "`<b>` — qalin, `<i>` — qiya, `<br>` — yangi qator."], code: "<h1>Mening sahifam</h1>\n<p>Men <b>10 yoshdaman</b>.</p>" },
          { emoji: "🖼️", title: "Rasm va havola", points: ["`<img src=\"rasm.jpg\" alt=\"tavsif\">` — rasm (yopiluvchi tegi yo'q!).", "`src` — rasm manzili, `alt` — rasm ko'rinmasa chiqadigan matn.", "`<a href=\"https://...\">Matn</a>` — havola (link)."], code: "<img src=\"mushuk.jpg\" alt=\"Mushuk\">\n<a href=\"https://scratch.mit.edu\">Scratch</a>" },
          { emoji: "🧩", title: "Atribut", points: ["Teg ichidagi qo'shimcha ma'lumot: `src`, `href`, `alt`.", "Yozilishi: `nomi=\"qiymati\"`.", "Qo'shtirnoqni unutmang!"] },
        ],
        practice: [
          "Jonli muharrirda \"HTML asoslari\" namunasini oching va ismni o'zingiznikiga almashtiring.",
          "`<h2>` bilan yangi bo'lim qo'shing: \"Sevimli taomim\".",
          "`<p>` ichida 2 ta so'zni `<b>` bilan qalin qiling.",
          "O'zingizga yoqqan rasm havolasini `<img>` bilan qo'ying.",
          "Sevimli saytingizga `<a>` havolasini qo'shing va index.html ni yuklab oling.",
        ],
        homework: "Daftarga 8 ta teg va vazifasini yozing: h1, h2, p, b, i, br, img, a. Har biriga bittadan misol yozing.",
        quiz: [
          { q: "Eng katta sarlavha tegi?", options: ["<h1>", "<h6>", "<p>", "<big>"], correct: 0 },
          { q: "Yopiluvchi teg qanday yoziladi?", options: ["</p>", "<p/>", "<\\p>", "(p)"], correct: 0 },
          { q: "Rasm qo'yish tegi?", options: ["<img>", "<a>", "<pic>", "<image>"], correct: 0 },
          { q: "Havola qaysi atribut bilan beriladi?", code: "<a ___=\"https://uz.wikipedia.org\">Vikipediya</a>", options: ["href", "src", "alt", "link"], correct: 0 },
          { q: "Rasm ko'rinmasa chiqadigan matn atributi?", options: ["alt", "src", "href", "title"], correct: 0 },
          { q: "Bu kodda xato qayerda?", code: "<p>Salom, dunyo!<p>", options: ["Yopiluvchi tegda / yo'q", "h1 bo'lishi kerak", "Vergul ortiqcha", "Xato yo'q"], correct: 0 },
          { q: "HTML nima?", options: ["Veb-sahifa skeleti (belgilash tili)", "Rasm dasturi", "O'yin", "Brauzer"], correct: 0 },
        ],
      },
      {
        title: "Oddiy veb-sahifa yaratish",
        kind: "lesson",
        goals: ["HTML hujjat tuzilishi (html, head, body)", "Kompyuterda .html fayl yaratish va brauzerda ochish", "Kod yozish muharriri bilan ishlash"],
        visual: "code",
        visualPreset: "html",
        slides: [
          { emoji: "🦴", title: "HTML hujjat skeleti", points: ["Har bir sahifa shunday boshlanadi:"], code: "<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset=\"utf-8\">\n    <title>Mening sahifam</title>\n  </head>\n  <body>\n    <h1>Salom!</h1>\n  </body>\n</html>" },
          { emoji: "🧠", title: "head va body", points: ["`<head>` — ko'rinmas ma'lumot: sahifa nomi (`<title>`), kodlash.", "`<body>` — sahifada **ko'rinadigan** hamma narsa.", "`<title>` — brauzer yorlig'idagi (tab) nom."] },
          { emoji: "💻", title: "Fayl yaratish", points: ["**Notepad** yoki **VS Code** ni oching.", "Kodni yozing va **index.html** deb saqlang.", "Faylni ikki marta bosing — brauzerda ochiladi!", "O'zgartirsangiz: saqlang (Ctrl+S) → brauzerda **F5**."] },
          { emoji: "📐", title: "Chiroyli kod qoidalari", points: ["Ichki teglarni **2 probel** bilan suring (indent).", "Har bir teg — yangi qatorda.", "Fayl nomlarida probel ishlatmang: `mening_sahifam.html`."] },
        ],
        practice: [
          "Notepad yoki VS Code'da HTML skeletini yozing.",
          "`<title>` ga ismingizni yozing.",
          "`<body>` ga sarlavha, 2 ta paragraf va 1 ta rasm qo'shing.",
          "`index.html` deb saqlab, brauzerda oching.",
          "Matnni o'zgartiring → Ctrl+S → F5 — o'zgarishni kuzating.",
        ],
        homework: "\"Mening maktabim\" sahifasini yarating: sarlavha, maktab haqida 3 ta paragraf, 1 ta rasm, maktab saytiga (yoki xaritaga) havola.",
        quiz: [
          { q: "Sahifada ko'rinadigan narsalar qaysi teg ichida?", options: ["<body>", "<head>", "<title>", "<meta>"], correct: 0 },
          { q: "Brauzer yorlig'idagi sahifa nomi qaysi teg?", options: ["<title>", "<h1>", "<p>", "<body>"], correct: 0 },
          { q: "HTML fayl kengaytmasi?", options: [".html", ".docx", ".jpg", ".exe"], correct: 0 },
          { q: "O'zgarishni brauzerda ko'rish uchun?", options: ["Saqlash va F5", "Kompyuterni o'chirish", "Faylni o'chirish", "Hech narsa"], correct: 0 },
          { q: "Qaysi fayl nomi to'g'ri?", options: ["mening_sahifam.html", "mening sahifam.html", "mening/sahifam.html", "sahifam"], correct: 0 },
          { q: "`<head>` ichida nima bo'ladi?", options: ["Sahifa haqida ko'rinmas ma'lumot", "Rasmlar", "Asosiy matn", "Havolalar"], correct: 0 },
        ],
      },
      {
        title: "Mini loyiha — «Mening ismim sahifasi»",
        kind: "project",
        goals: ["O'zi haqida to'liq sahifa yaratish", "Barcha o'rganilgan teglarni qo'llash", "Sahifani sinfga ko'rsatish"],
        visual: "code",
        visualPreset: "html",
        slides: [
          { emoji: "👤", title: "Loyiha vazifasi", points: ["**\"Men haqimda\"** sahifasi.", "Ism (h1), men haqimda (p), sevimli narsalarim (h2 + p), rasm, havola.", "Kamida **8 ta teg** ishlatilsin."] },
          { emoji: "🗂️", title: "Sahifa rejasi", points: ["1. Katta sarlavha — ismingiz.", "2. Qisqa tanishuv: yoshim, sinfim, shahrim.", "3. Sevimli narsalarim.", "4. Rasm (avatar yoki chizmangiz).", "5. Havola — sevimli saytim."] },
          { emoji: "🔐", title: "Internet xavfsizligi", points: ["Sahifaga **uy manzili, telefon, maktab raqami** yozmang.", "O'z yuz rasmingiz o'rniga **avatar** yoki chizma ishlating.", "Faqat ismingiz yetarli."] },
          { emoji: "🔍", title: "Tekshirish", points: ["Hamma teglar yopilganmi?", "Rasm ochiladimi?", "Havola ishlaydimi?"] },
        ],
        practice: [
          "Reja bo'yicha sahifa kodini yozing (jonli muharrirda yoki VS Code'da).",
          "Kamida 8 xil teg ishlatganingizni sanang.",
          "Avatar yoki Paint'dagi chizmangizni rasm sifatida qo'ying.",
          "Tekshirish ro'yxati bo'yicha xatolarni tuzating.",
          "Sahifani sinfga ko'rsating.",
        ],
        homework: "Sahifangizga \"Mening orzuim\" bo'limini qo'shing: h2 sarlavha, 2 paragraf va orzuingizga oid rasm.",
        rubric: ["8+ xil teg", "Reja bo'yicha 5 bo'lim", "Rasm va havola ishlaydi", "Shaxsiy ma'lumot yo'q", "Kod tartibli (indent)"],
        quiz: [
          { q: "Veb-sahifaga nimani yozmaslik kerak?", options: ["Uy manzili va telefon", "Sevimli taom", "Ism", "Hobbi"], correct: 0 },
          { q: "Sahifadagi eng katta sarlavha uchun?", options: ["<h1>", "<p>", "<a>", "<br>"], correct: 0 },
          { q: "Kodda nima xato?", code: "<img src=\"avatar.png\" alt=\"Avatar\"></img>", options: ["img tegining yopiluvchisi kerak emas", "src noto'g'ri", "alt kerak emas", "Xato yo'q"], correct: 0 },
          { q: "Havola ishlashini qanday tekshiramiz?", options: ["Brauzerda bosib ko'ramiz", "Kodni o'chiramiz", "Faylni qayta nomlaymiz", "Tekshirib bo'lmaydi"], correct: 0 },
          { q: "Qaysi teg yangi qatorga o'tkazadi?", options: ["<br>", "<b>", "<h1>", "<img>"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "Jadval, ro'yxat, rasm va havolalar",
    days: [
      {
        title: "HTML'da jadval va ro'yxat",
        kind: "lesson",
        goals: ["Tartibli (ol) va tartibsiz (ul) ro'yxatlar", "Jadval: table, tr, th, td", "Ma'lumotni tushunarli ko'rsatish"],
        visual: "code",
        visualPreset: "list",
        slides: [
          { emoji: "📋", title: "Ro'yxatlar", points: ["`<ul>` — nuqtali (tartibsiz) ro'yxat.", "`<ol>` — raqamli (tartibli) ro'yxat.", "Har bir band — `<li>`."], code: "<ul>\n  <li>Olma</li>\n  <li>Banan</li>\n</ul>\n<ol>\n  <li>Uyg'onish</li>\n  <li>Nonushta</li>\n</ol>" },
          { emoji: "▦", title: "Jadval", points: ["`<table>` — jadval.", "`<tr>` — qator (table row).", "`<th>` — sarlavha katak (qalin).", "`<td>` — oddiy katak (table data)."], code: "<table border=\"1\">\n  <tr><th>Kun</th><th>Fan</th></tr>\n  <tr><td>Dushanba</td><td>IT</td></tr>\n</table>" },
          { emoji: "🔢", title: "Qachon qaysi?", points: ["Retsept qadamlari → `<ol>`.", "Xarid ro'yxati → `<ul>`.", "Dars jadvali, reyting → `<table>`."] },
          { emoji: "🪆", title: "Ichma-ich ro'yxat", points: ["`<li>` ichida yana `<ul>` bo'lishi mumkin.", "Masalan: Mevalar → Olma, Nok; Sabzavotlar → Sabzi."] },
        ],
        practice: [
          "Jonli muharrirda \"Ro'yxat va jadval\" namunasini oching.",
          "Sevimli 5 ta o'yiningiz `<ol>` ro'yxatini tuzing (1-o'rin eng sevimli).",
          "Xarid ro'yxatini `<ul>` bilan yozing.",
          "Haftalik dars jadvalingizni `<table>` bilan tuzing (kamida 3 ustun, 5 qator).",
          "Ichma-ich ro'yxat yarating: Hayvonlar → Uy hayvonlari / Yovvoyi hayvonlar.",
        ],
        homework: "\"Oilamizning haftalik menyusi\" jadvalini HTML'da tuzing: kunlar, nonushta, tushlik, kechki ovqat.",
        quiz: [
          { q: "Raqamli ro'yxat tegi?", options: ["<ol>", "<ul>", "<li>", "<table>"], correct: 0 },
          { q: "Ro'yxatning har bir bandi?", options: ["<li>", "<tr>", "<td>", "<p>"], correct: 0 },
          { q: "Jadvalda qator tegi?", options: ["<tr>", "<td>", "<th>", "<table>"], correct: 0 },
          { q: "Jadvaldagi sarlavha katak?", options: ["<th>", "<td>", "<tr>", "<h1>"], correct: 0 },
          { q: "Natijada nechta band ko'rinadi?", code: "<ul>\n  <li>Qizil</li>\n  <li>Yashil</li>\n  <li>Ko'k</li>\n</ul>", options: ["3", "1", "2", "4"], correct: 0 },
          { q: "Retsept qadamlari uchun qaysi ro'yxat mos?", options: ["<ol>", "<ul>", "<table>", "<img>"], correct: 0 },
        ],
      },
      {
        title: "Rasm va link qo'shish (chuqurroq)",
        kind: "lesson",
        goals: ["Rasm o'lchamini width/height bilan boshqarish", "Ichki va tashqi havolalar, yangi oynada ochish", "Rasmni havolaga aylantirish"],
        visual: "code",
        visualPreset: "html",
        slides: [
          { emoji: "📏", title: "Rasm o'lchami", points: ["`width=\"300\"` — kenglik pikselda.", "Faqat width bersangiz — balandlik o'zi mos keladi.", "Rasm fayli HTML bilan **bir papkada** bo'lsa: `src=\"rasm.jpg\"`."], code: "<img src=\"mushuk.jpg\" alt=\"Mushuk\" width=\"300\">" },
          { emoji: "🔗", title: "Havola turlari", points: ["**Tashqi**: `href=\"https://google.com\"`.", "**Ichki**: boshqa sahifangizga `href=\"hobbi.html\"`.", "**Yangi oynada**: `target=\"_blank\"`.", "**Email**: `href=\"mailto:ism@misol.uz\"`."] },
          { emoji: "🖱️", title: "Rasm-havola", points: ["`<a>` ichiga `<img>` qo'ysak — rasm bosiladigan bo'ladi!"], code: "<a href=\"https://scratch.mit.edu\" target=\"_blank\">\n  <img src=\"scratch.png\" alt=\"Scratch\" width=\"120\">\n</a>" },
          { emoji: "📁", title: "Papka tuzilishi", points: ["`sayt/index.html`", "`sayt/hobbi.html`", "`sayt/rasmlar/mushuk.jpg` → `src=\"rasmlar/mushuk.jpg\"`."], tip: "Fayl va papka nomlarida faqat lotin harflari, raqam va _ ishlating." },
        ],
        practice: [
          "Jonli muharrirda rasm kengligini 100, 200, 400 qilib o'zgartiring.",
          "3 ta tashqi havola qo'shing, ikkitasi yangi oynada ochilsin.",
          "Rasmni bosiladigan havolaga aylantiring.",
          "Kompyuterda `sayt` papkasi yarating: index.html, hobbi.html, rasmlar/.",
          "index.html dan hobbi.html ga va orqaga ichki havola qo'ying.",
        ],
        homework: "Ikki sahifali mini-sayt: index.html (men haqimda) va rasmlar.html (galereya — 4 ta rasm). Sahifalar bir-biriga havola bilan bog'langan bo'lsin.",
        quiz: [
          { q: "Havolani yangi oynada ochish atributi?", options: ["target=\"_blank\"", "new=\"yes\"", "open=\"window\"", "href=\"new\""], correct: 0 },
          { q: "Rasm kengligini 200 px qilish?", options: ["width=\"200\"", "size=\"200\"", "height=\"200px\"", "big=\"200\""], correct: 0 },
          { q: "Rasm `rasmlar` papkasida. To'g'ri src?", options: ["rasmlar/mushuk.jpg", "mushuk.jpg/rasmlar", "mushuk/rasmlar.jpg", "http://mushuk"], correct: 0 },
          { q: "Rasmni bosiladigan qilish uchun?", options: ["<img> ni <a> ichiga qo'yamiz", "<img> ga href yozamiz", "<p> ichiga qo'yamiz", "Imkonsiz"], correct: 0 },
          { q: "O'z saytimizdagi boshqa sahifaga havola?", options: ["href=\"hobbi.html\"", "href=\"https://hobbi\"", "src=\"hobbi.html\"", "alt=\"hobbi\""], correct: 0 },
        ],
      },
      {
        title: "Mini loyiha — «Mening hobbi sahifam»",
        kind: "project",
        goals: ["Ro'yxat, jadval, rasm va havolalarni bitta sahifada birlashtirish", "Ma'lumotni tuzilgan holda taqdim etish"],
        visual: "code",
        visualPreset: "list",
        slides: [
          { emoji: "⚽", title: "Loyiha", points: ["Sevimli hobbingiz haqida sahifa: sport, rasm, o'yin, kitob, musiqa...", "Tuzilishi: sarlavha → tanishuv → ro'yxat → jadval → rasmlar → havolalar."] },
          { emoji: "🧾", title: "Majburiy elementlar", points: ["`<h1>` va kamida 2 ta `<h2>`.", "1 ta `<ul>` yoki `<ol>`.", "1 ta `<table>` (kamida 3×3).", "2+ rasm, 2+ havola."] },
          { emoji: "💡", title: "Misol: Futbol", points: ["Ro'yxat: sevimli jamoalarim.", "Jadval: o'yinchi | jamoa | raqam.", "Rasmlar: to'p, stadion.", "Havolalar: jamoa sayti."] },
          { emoji: "✅", title: "Yakuniy tekshiruv", points: ["Kod tartibli (indent).", "Hamma rasmlar ochiladi, alt yozilgan.", "Havolalar ishlaydi."] },
        ],
        practice: [
          "Hobbi tanlang va sahifa rejasini yozing.",
          "Majburiy elementlarni qo'shib sahifa kodini yozing.",
          "Jadvalni to'ldiring (kamida 3×3).",
          "Rasmlar va havolalarni tekshiring.",
          "Sahifani sherigingizga ko'rsatib, 1 ta maslahat oling.",
        ],
        homework: "Hobbi sahifangizni ikkinchi sahifa sifatida \"Men haqimda\" saytingizga ulang.",
        rubric: ["h1 + 2 ta h2", "Ro'yxat bor", "Jadval 3×3+", "2+ rasm (alt bilan)", "2+ ishlaydigan havola"],
        quiz: [
          { q: "Jadvalda 3 ustun bo'lishi uchun har `<tr>` da nechta `<td>`?", options: ["3", "1", "2", "6"], correct: 0 },
          { q: "Hobbi sahifasida jamoalar ro'yxati uchun?", options: ["<ul> yoki <ol>", "<table> faqat", "<img>", "<title>"], correct: 0 },
          { q: "Har bir rasmda nima bo'lishi kerak?", options: ["alt atributi", "href", "target", "border"], correct: 0 },
          { q: "Ikkinchi darajali sarlavha?", options: ["<h2>", "<h1>", "<p>", "<li>"], correct: 0 },
          { q: "Kod tartibli bo'lishi uchun?", options: ["Ichki teglarni surib yozish (indent)", "Hammasini bir qatorga yozish", "Teglarni yopmaslik", "Katta harflar"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "CSS asoslari",
    days: [
      {
        title: "CSS asoslari (ranglar, shriftlar)",
        kind: "lesson",
        goals: ["CSS nima va HTML bilan qanday bog'lanadi", "Selektor, xususiyat, qiymat", "Rang, shrift, o'lcham berish"],
        visual: "code",
        visualPreset: "css",
        slides: [
          { emoji: "🎨", title: "CSS nima?", points: ["HTML — **skelet**, CSS — **kiyim**!", "CSS sahifaning ko'rinishini boshqaradi: rang, shrift, joylashuv.", "CSS — Cascading Style Sheets."] },
          { emoji: "🧱", title: "CSS qoidasi", points: ["**Selektor** — nimani bezaymiz (`h1`).", "**Xususiyat** — nimasini (`color`).", "**Qiymat** — qanday (`red`).", "Har qator oxirida **;** nuqtali vergul!"], code: "h1 {\n  color: purple;\n  font-size: 40px;\n}" },
          { emoji: "🌈", title: "Ranglar", points: ["Nom bilan: `red`, `blue`, `gold`.", "HEX kod: `#7c3aed` (binafsha).", "`color` — matn rangi, `background` — fon rangi."] },
          { emoji: "🔤", title: "Shriftlar", points: ["`font-family: Arial, sans-serif;` — shrift turi.", "`font-size: 20px;` — o'lcham.", "`font-weight: bold;` — qalinlik.", "`text-align: center;` — markazga."] },
          { emoji: "🔌", title: "CSS ni ulash", points: ["`<style>` tegi ichida — `<head>` da.", "Yoki alohida fayl: `<link rel=\"stylesheet\" href=\"style.css\">`.", "Alohida fayl — katta saytlar uchun qulay."] },
        ],
        practice: [
          "Jonli muharrirda \"CSS bilan bezash\" namunasini oching.",
          "`h1` rangini o'zgartiring (nom va HEX bilan sinab ko'ring).",
          "`body` fonini o'zingizga yoqqan rangga almashtiring.",
          "`p` uchun shrift, o'lcham va markazga tekislash bering.",
          "\"Men haqimda\" sahifangizga `<style>` qo'shib, uni bezang.",
        ],
        homework: "Sahifangiz uchun 3 rangli \"rang palitrasi\" tanlang (masalan, coolors.co saytidan) va ularni CSS'da h1, body va p ga qo'llang.",
        quiz: [
          { q: "CSS nimani boshqaradi?", options: ["Sahifa ko'rinishini", "Sahifa skeletini", "Kompyuter xotirasini", "Internet tezligini"], correct: 0 },
          { q: "Matn rangini beruvchi xususiyat?", options: ["color", "background", "font-size", "text"], correct: 0 },
          { q: "Kodda qaysi qism selektor?", code: "p {\n  color: blue;\n}", options: ["p", "color", "blue", "{ }"], correct: 0 },
          { q: "CSS qoidasining har qatori nima bilan tugaydi?", options: [";", ".", ",", ":"], correct: 0 },
          { q: "Matnni markazga qo'yish?", options: ["text-align: center;", "align: middle;", "center: yes;", "font: center;"], correct: 0 },
          { q: "Alohida CSS faylni ulash tegi?", options: ["<link>", "<a>", "<img>", "<css>"], correct: 0 },
          { q: "`#ff0000` qaysi rang?", options: ["Qizil", "Yashil", "Ko'k", "Qora"], correct: 0 },
        ],
      },
      {
        title: "Sahifani bezash (box model, klasslar)",
        kind: "lesson",
        goals: ["Box model: margin, padding, border", "class selektori bilan ishlash", "Burchak yumaloqligi va soya"],
        visual: "code",
        visualPreset: "css",
        slides: [
          { emoji: "📦", title: "Box model", points: ["Har bir element — **quti**.", "**padding** — ichki bo'sh joy (quti ichida).", "**border** — chegara chizig'i.", "**margin** — tashqi bo'sh joy (qutilar orasida)."], code: ".karta {\n  padding: 20px;\n  border: 2px solid #7c3aed;\n  margin: 16px;\n}" },
          { emoji: "🏷️", title: "Klass (class)", points: ["Bir xil ko'rinishni bir nechta elementga berish.", "HTML: `<div class=\"karta\">`.", "CSS: `.karta { ... }` — nuqta bilan!"] },
          { emoji: "🟪", title: "Chiroyli qutilar", points: ["`border-radius: 16px;` — yumaloq burchak.", "`box-shadow: 0 4px 12px #0002;` — soya.", "`max-width: 400px; margin: auto;` — markazda."] },
          { emoji: "🖱️", title: "Hover effekti", points: ["`:hover` — sichqoncha ustiga kelganda.", "Tugma yoki karta rangini o'zgartirish."], code: "button:hover {\n  background: gold;\n}" },
        ],
        practice: [
          "Jonli muharrirdagi `.karta` ning padding, margin va border-radius qiymatlarini o'zgartirib kuzating.",
          "3 ta `<div class=\"karta\">` yarating — bitta CSS qoidasi hammasini bezasin.",
          "Kartalarga soya va yumaloq burchak bering.",
          "Tugmaga `:hover` effekti qo'shing.",
          "Hobbi sahifangizni kartalar bilan qayta bezang.",
        ],
        homework: "\"Sevimli hayvonlar\" sahifasi: 4 ta karta, har birida rasm, nom va 1 gap. Hover'da karta biroz kattalashsin (`transform: scale(1.05)`).",
        quiz: [
          { q: "Quti ichidagi bo'sh joy?", options: ["padding", "margin", "border", "width"], correct: 0 },
          { q: "Qutilar orasidagi tashqi bo'sh joy?", options: ["margin", "padding", "color", "font"], correct: 0 },
          { q: "CSS'da klass selektori qanday yoziladi?", options: [".karta", "#karta", "karta()", "<karta>"], correct: 0 },
          { q: "Yumaloq burchak xususiyati?", options: ["border-radius", "round", "corner", "radius-box"], correct: 0 },
          { q: "Sichqoncha ustiga kelganda effekt?", options: [":hover", ":click", ":mouse", ":over"], correct: 0 },
          { q: "HTML'da klass qanday beriladi?", code: "<div ____=\"karta\">...</div>", options: ["class", "id", "style", "href"], correct: 0 },
        ],
      },
      {
        title: "Mini loyiha — «Chiroyli veb-sahifa»",
        kind: "project",
        goals: ["HTML va CSS'ni birgalikda qo'llash", "Yagona dizayn uslubini yaratish", "Alohida style.css fayl bilan ishlash"],
        visual: "code",
        visualPreset: "css",
        slides: [
          { emoji: "✨", title: "Loyiha", points: ["Oldingi sahifalaringizdan birini **to'liq qayta bezang**.", "Alohida **style.css** fayl ishlating.", "Bir xil rang palitrasi va shriftlar."] },
          { emoji: "🎯", title: "Talablar", points: ["3 rangli palitra.", "Google Fonts'dan 1 ta shrift (ixtiyoriy).", "Kamida 1 ta klass, 1 ta hover effekt.", "Karta yoki qutilar: padding, border-radius, soya."] },
          { emoji: "🔤", title: "Google Fonts", points: ["fonts.google.com → shrift tanlang (masalan, Nunito).", "`<link>` kodini `<head>` ga qo'ying.", "CSS: `font-family: 'Nunito', sans-serif;`."] },
          { emoji: "🏆", title: "Galereya", points: ["Dars oxirida hamma sahifalar ekranda ko'rsatiladi.", "\"Eng chiroyli sahifa\" uchun ovoz berish!"] },
        ],
        practice: [
          "Sahifangiz uchun style.css yarating va `<link>` bilan ulang.",
          "Palitra ranglarini body, sarlavhalar va kartalarga qo'llang.",
          "Kamida bitta klass va hover effekt qo'shing.",
          "Shriftni Google Fonts'dan ulang (ixtiyoriy).",
          "Galereyada sahifangizni ko'rsating.",
        ],
        homework: "Sahifangizni telefon ekranida ko'rib chiqing (brauzerda Ctrl+Shift+M). Qaysi joylari noqulay ekanini yozib keling.",
        rubric: ["style.css alohida fayl", "3 rangli palitra", "Klass va hover effekt", "Box model to'g'ri ishlatilgan", "Yagona uslub"],
        quiz: [
          { q: "Alohida CSS fayl kengaytmasi?", options: [".css", ".html", ".txt", ".js"], correct: 0 },
          { q: "Google Fonts shriftini ulash uchun nima qo'yamiz?", options: ["<head> ga <link>", "<body> ga <img>", "<a> teg", "Hech narsa"], correct: 0 },
          { q: "Nima uchun alohida style.css qulay?", options: ["Bir faylni o'zgartirsak, hamma sahifa o'zgaradi", "Sayt sekinlashadi", "Rasm qo'shiladi", "Majburiy emas va foydasiz"], correct: 0 },
          { q: "Dizaynda yagona uslub nimani anglatadi?", options: ["Bir xil ranglar va shriftlar", "Har sahifada boshqa rang", "Faqat qora-oq", "Shriftsiz"], correct: 0 },
          { q: "Telefon ko'rinishini brauzerda tekshirish?", options: ["Ctrl + Shift + M (DevTools)", "Ctrl + P", "F1", "Alt + F4"], correct: 0 },
        ],
      },
    ],
  },
  {
    title: "HTML + CSS: portfolio",
    days: [
      {
        title: "HTML + CSS qo'shma loyihasi (layout)",
        kind: "lesson",
        goals: ["Semantik teglar: header, nav, section, footer", "Flexbox bilan elementlarni qatorga joylash", "Navigatsiya menyusi yaratish"],
        visual: "code",
        visualPreset: "portfolio",
        slides: [
          { emoji: "🏗️", title: "Sahifa tuzilishi", points: ["`<header>` — sarlavha qismi.", "`<nav>` — menyu.", "`<section>` — bo'limlar.", "`<footer>` — sahifa pastki qismi."] },
          { emoji: "↔️", title: "Flexbox", points: ["`display: flex;` — ichidagi elementlar **qatorga** tiziladi.", "`gap: 16px;` — oralig'i.", "`justify-content: center;` — gorizontal markaz.", "`flex-wrap: wrap;` — sig'masa keyingi qatorga."], code: ".menyu {\n  display: flex;\n  gap: 16px;\n  justify-content: center;\n}" },
          { emoji: "🧭", title: "Menyu", points: ["`<nav>` ichida havolalar.", "Havola tagidagi chiziqni olib tashlash: `text-decoration: none;`.", "Hover'da rang o'zgarsin."] },
          { emoji: "▦", title: "Grid (qo'shimcha)", points: ["`display: grid; grid-template-columns: repeat(3, 1fr);` — 3 ustunli to'r.", "Galereya va kartalar uchun juda qulay."] },
        ],
        practice: [
          "Jonli muharrirda \"Portfolio\" namunasini oching va tuzilishini o'rganing.",
          "header, nav, section, footer bilan o'z sahifa skeletingizni tuzing.",
          "nav menyusini flexbox bilan gorizontal qiling.",
          "3 ta kartani grid bilan 3 ustunga joylang.",
          "Footer'ga \"© 2026 Ismingiz\" yozing.",
        ],
        homework: "Portfolio uchun kontent tayyorlang: o'zingiz haqida 3 gap, 6 ta eng yaxshi ishingiz (Scratch, Photoshop, video, taqdimot...) ro'yxati va rasmlari.",
        quiz: [
          { q: "Sahifa pastki qismi tegi?", options: ["<footer>", "<header>", "<nav>", "<bottom>"], correct: 0 },
          { q: "Menyu uchun semantik teg?", options: ["<nav>", "<menu-bar>", "<ul> faqat", "<section>"], correct: 0 },
          { q: "Elementlarni qatorga tizish?", options: ["display: flex;", "display: none;", "color: flex;", "flex: text;"], correct: 0 },
          { q: "Flex elementlar orasidagi masofa?", options: ["gap", "margin-flex", "space", "padding-gap"], correct: 0 },
          { q: "Havola tagidagi chiziqni olib tashlash?", options: ["text-decoration: none;", "underline: off;", "border: none;", "line: 0;"], correct: 0 },
          { q: "3 ustunli to'r uchun?", code: ".galereya {\n  display: grid;\n  grid-template-columns: ______;\n}", options: ["repeat(3, 1fr)", "3 columns", "flex 3", "1fr"], correct: 0 },
        ],
      },
      {
        title: "Oddiy portfolio sayt",
        kind: "lesson",
        goals: ["Portfolio nima va nima uchun kerak", "Ko'p sahifali sayt tuzilishi", "O'z ishlarini chiroyli taqdim etish"],
        visual: "code",
        visualPreset: "portfolio",
        slides: [
          { emoji: "💼", title: "Portfolio nima?", points: ["**Portfolio** — eng yaxshi ishlaringiz to'plami.", "Dizaynerlar, dasturchilar, rassomlar ishga kirganda ko'rsatadi.", "Sizning 5 oylik yutuqlaringiz — bitta saytda!"] },
          { emoji: "🗺️", title: "Sayt xaritasi", points: ["`index.html` — bosh sahifa: men haqimda.", "`ishlarim.html` — galereya: rasmlar, loyihalar.", "`aloqa.html` — (ixtiyoriy) forma — 6-oyda!", "Har sahifada **bir xil** header, menyu va footer."] },
          { emoji: "🃏", title: "Loyiha kartasi", points: ["Rasm (skrinshot).", "Nomi: \"Olma terish o'yini\".", "1 gap: nima va qaysi dasturda.", "Havola: Scratch loyihasi yoki video."], code: "<div class=\"loyiha\">\n  <img src=\"rasmlar/oyin.png\" alt=\"O'yin\">\n  <h3>Olma terish o'yini</h3>\n  <p>Scratch'da yaratdim.</p>\n</div>" },
          { emoji: "📱", title: "Moslashuvchan (responsive)", points: ["`<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">`.", "`max-width: 100%` — rasmlar telefonga sig'adi.", "Flex-wrap — kartalar telefonda ustma-ust."] },
        ],
        practice: [
          "Kompyuterda `portfolio` papkasini tuzing: index.html, ishlarim.html, style.css, rasmlar/.",
          "Bosh sahifaga header, menyu, \"Men haqimda\" va footer qo'ying.",
          "ishlarim.html'da kamida 4 ta loyiha kartasi yarating.",
          "Ikkala sahifa bir xil style.css dan foydalansin.",
          "Telefon ko'rinishini tekshiring (viewport + max-width).",
        ],
        homework: "Portfolioga yana 2 ta loyiha kartasi qo'shing va barcha rasmlarga alt yozing.",
        quiz: [
          { q: "Portfolio nima?", options: ["Eng yaxshi ishlar to'plami", "O'yin", "Parollar ro'yxati", "Brauzer"], correct: 0 },
          { q: "Saytning bosh sahifasi fayl nomi odatda?", options: ["index.html", "main.css", "home.jpg", "start.exe"], correct: 0 },
          { q: "Rasmlar telefon ekraniga sig'ishi uchun?", options: ["max-width: 100%", "width: 5000px", "display: none", "font-size: 0"], correct: 0 },
          { q: "Hamma sahifalar bir xil ko'rinishi uchun?", options: ["Bitta umumiy style.css", "Har biriga boshqa rang", "CSS ishlatmaslik", "Rasmsiz"], correct: 0 },
          { q: "Telefon uchun zarur meta teg?", options: ["viewport", "charset faqat", "title", "author"], correct: 0 },
        ],
      },
      {
        title: "Mini loyiha — «Mening portfolio sahifam»",
        kind: "project",
        goals: ["To'liq portfolio saytni yakunlash", "5 oylik ishlarni taqdim etish", "Sayt sifatini tekshirish"],
        visual: "code",
        visualPreset: "portfolio",
        slides: [
          { emoji: "🏁", title: "Yakuniy portfolio", points: ["2+ sahifa, umumiy menyu va footer.", "6+ loyiha kartasi: Word/PowerPoint, Excel, video, AI, Scratch, Photoshop.", "Chiroyli CSS dizayn."] },
          { emoji: "🔍", title: "Sifat tekshiruvi", points: ["Barcha havolalar ishlaydimi?", "Rasmlar ochiladimi, alt bormi?", "Telefonda yaxshi ko'rinadimi?", "Imlo xatolari yo'qmi?"] },
          { emoji: "🧑‍⚖️", title: "O'zaro baholash", points: ["Sherigingiz saytini \"mehmon\" sifatida ko'rib chiqing.", "2 ta yulduz ⭐ (yoqqan narsa) + 1 ta tilak 🙏 (yaxshilash)."] },
          { emoji: "🚀", title: "Keyingi qadam", points: ["6-oyda saytingizni **internetga joylaymiz** — hamma ko'ra oladi!", "Faylni ZIP qilib saqlab qo'ying."] },
        ],
        practice: [
          "Portfolio sahifalarini yakunlang (6+ loyiha kartasi).",
          "Sifat tekshiruvi ro'yxati bo'yicha xatolarni tuzating.",
          "Sherigingiz bilan saytlarni almashib, \"2 yulduz + 1 tilak\" bering.",
          "Tilak asosida 1 ta narsani yaxshilang.",
          "Portfolio papkasini ZIP qilib saqlang.",
        ],
        homework: "Portfolio saytingizni oilangizga ko'rsating. 6-oyda uni internetga joylash uchun tayyor bo'lsin!",
        rubric: ["2+ sahifa, umumiy menyu", "6+ loyiha kartasi", "Havolalar va rasmlar ishlaydi", "Telefonda moslashuvchan", "Toza, yagona dizayn"],
        quiz: [
          { q: "Sherik saytini baholash usuli?", options: ["2 yulduz + 1 tilak", "Faqat xatolar", "Faqat baho", "Hech narsa"], correct: 0 },
          { q: "Portfolio papkasini saqlab qo'yish uchun?", options: ["ZIP arxiv", "O'chirish", "Qayta nomlash", "Chop etish"], correct: 0 },
          { q: "6-oyda portfolio bilan nima qilamiz?", options: ["Internetga (hostingga) joylaymiz", "O'chiramiz", "Excel'ga o'tkazamiz", "Scratch'ga yuklaymiz"], correct: 0 },
          { q: "Sifat tekshiruviga nima kirmaydi?", options: ["Havolalar ishlashi", "Rasmlar ochilishi", "Kompyuter rangi", "Imlo xatolari"], correct: 2 },
          { q: "Portfolio uchun eng yaxshi loyiha kartasi tarkibi?", options: ["Rasm, nom, tavsif, havola", "Faqat nom", "Faqat parol", "Bo'sh karta"], correct: 0 },
        ],
      },
    ],
  },
];
